import {createRequire} from 'node:module';
import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import net from 'node:net';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.OWNER_QA_DIR||path.join(root,'qa/p220-connections');fs.mkdirSync(out,{recursive:true});
const {chromium}=createRequire(root+'/package.json')('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'as-p220-')));
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;const server=spawn('python3',['tests/owner/serve_ai_fixture.py','--port',String(port),'--data-dir',dir+'/data','--delay-seconds','0.5'],{cwd:root,stdio:['ignore','ignore','pipe']});let browser,serr='';server.stderr.on('data',d=>serr+=d);const count=()=>fs.existsSync(dir+'/calls.json')?JSON.parse(fs.readFileSync(dir+'/calls.json')).length:0;
try{
for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serr);try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1100}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/503/.test(m.text()))errors.push(m.text())});
await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('p220-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-P220-only-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-P220-only-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
// Shared model settings entry must land on the form, including after guarded research edits.
await page.goto(base+'/research');await page.getByRole('button',{name:'模型连接设置',exact:true}).click();await page.waitForURL(base+'/settings/connections');await page.getByRole('button',{name:'保存模型连接',exact:true}).waitFor();await page.getByRole('button',{name:'模型连接设置',exact:true}).waitFor({state:'hidden'});
await page.goto(base+'/research');await page.locator('.assistant-workbench').first().getByLabel('研究问题',{exact:true}).fill('Synthetic unsaved navigation check');await page.getByRole('button',{name:'模型连接设置',exact:true}).click();await page.getByRole('dialog',{name:'离开研究助手'}).waitFor();await page.getByRole('button',{name:'继续研究',exact:true}).click();assert.equal(new URL(page.url()).pathname,'/research');assert.equal(await page.locator('.assistant-workbench').first().getByLabel('研究问题',{exact:true}).inputValue(),'Synthetic unsaved navigation check');
await page.getByRole('button',{name:'模型连接设置',exact:true}).click();await page.getByRole('button',{name:'离开',exact:true}).click();await page.waitForURL(base+'/settings/connections');await page.getByRole('button',{name:'保存模型连接',exact:true}).waitFor();
await page.goto(base+'/portfolio');await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const askPanel=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await askPanel.waitFor();await askPanel.getByLabel('给 Ask Awesome 的消息',{exact:true}).fill('Synthetic retained assistant draft');await askPanel.getByRole('button',{name:'模型连接设置',exact:true}).click();await page.waitForURL(base+'/settings/connections');await askPanel.waitFor({state:'hidden'});await page.getByRole('button',{name:'保存模型连接',exact:true}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await askPanel.waitFor();assert.equal(await askPanel.getByLabel('给 Ask Awesome 的消息',{exact:true}).inputValue(),'Synthetic retained assistant draft');await askPanel.getByRole('button',{name:'模型连接设置',exact:true}).waitFor({state:'hidden'});await askPanel.getByRole('button',{name:'关闭助手',exact:true}).click();assert.equal(count(),0);
const model=page.getByLabel('模型 ID（不是服务名称或邮箱）',{exact:true}),key=page.getByLabel('你自己的模型服务 API Key',{exact:true}),save=page.getByRole('button',{name:'保存模型连接',exact:true}),test=page.getByRole('button',{name:'测试连接',exact:true});
assert.equal(await model.inputValue(),'deepseek-flash');assert.equal(await test.isDisabled(),true);await model.fill('Deepseek');await key.fill('Synthetic-not-real');await save.click();await page.getByText('请选择或填写实际模型 ID，例如 deepseek-flash；DeepSeek 是服务名称。',{exact:true}).first().waitFor();assert.equal(count(),0);
await page.getByRole('button',{name:'deepseek-flash',exact:true}).click();await save.click();await page.getByText('连接配置已保存。Key 输入框已清空，下一步点击下方「测试连接」。',{exact:true}).waitFor();assert.equal(await key.inputValue(),'');assert.equal(count(),0);
await test.click();await page.getByRole('dialog',{name:'确认测试模型连接'}).waitFor();assert.equal(count(),0);await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(count(),0);
await test.click();await page.getByRole('button',{name:'确认发送测试',exact:true}).click();await page.getByText('连接测试成功',{exact:true}).waitFor();assert.equal(count(),1);await page.getByText('deepseek / deepseek-flash · 本进程调用成功',{exact:true}).waitFor();await page.getByText('连接测试成功',{exact:true}).waitFor();
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.model-panel').scrollIntoViewIfNeeded();await delay(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+`/model-${width}.png`});}
await page.reload();await model.waitFor();assert.equal(await model.inputValue(),'deepseek-flash');await page.getByRole('button',{name:'重新测试连接',exact:true}).waitFor();assert.equal(await key.inputValue(),'');assert.equal(count(),1);
await model.fill('custom-model');assert.equal(await page.getByRole('button',{name:'重新测试连接',exact:true}).isDisabled(),true);await key.fill('Synthetic-new-not-real');await save.click();await page.getByText('deepseek / custom-model · 尚未验证真实调用',{exact:true}).waitFor();assert.equal(count(),1);
await page.route('**/api/v1/owner/ai-generate',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'connection_unavailable',message:'服务商拒绝 API Key，请检查 Key 是否有效。'}})}));await page.getByRole('button',{name:'测试连接',exact:true}).click();await page.getByRole('button',{name:'确认发送测试',exact:true}).click();await page.getByText(/服务商拒绝 API Key.*没有自动重试/).waitFor();await delay(1300);assert.equal(count(),1);await page.screenshot({path:out+'/model-error-320.png'});assert.deepEqual(errors,[]);
// Exercise the fixed chat composer, confirmation, exact reply, and follow-up context.
await page.unroute('**/api/v1/owner/ai-generate');await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await askPanel.waitFor();const chatInput=askPanel.getByLabel('给 Ask Awesome 的消息',{exact:true});
const previews=[];page.on('request',req=>{if(req.url().endsWith('/api/v1/owner/ai-preview'))previews.push(req.postDataJSON())});
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});const question=`自由输入 ${width}：用三个要点解释市盈率的局限。`;await chatInput.fill(question);assert.equal(await chatInput.inputValue(),question);const box=await chatInput.boundingBox();assert.ok(box&&box.y+box.height<=1000);assert.equal(await askPanel.getByRole('heading',{name:'研究助手',exact:true}).count(),0);await askPanel.getByRole('button',{name:'发送',exact:true}).click();const confirmation=page.getByRole('dialog',{name:'确认发送对话',exact:true});await confirmation.waitFor();assert.equal(count(),width===1440?1:2);await confirmation.getByRole('button',{name:'返回修改',exact:true}).click();await confirmation.waitFor({state:'hidden'});assert.equal(await chatInput.inputValue(),question);assert.equal(count(),width===1440?1:2);await askPanel.getByRole('button',{name:'发送',exact:true}).click();await confirmation.getByRole('button',{name:'确认发送',exact:true}).click();await confirmation.waitFor({state:'hidden'});await askPanel.locator('.chat-answer p').filter({hasText:'Synthetic answer: '+question}).waitFor();assert.equal(await chatInput.isEditable(),true);assert.equal(await chatInput.inputValue(),'');assert.equal(count(),width===1440?2:3);await page.screenshot({path:out+`/ask-chat-${width}.png`});}
const followup=JSON.parse(previews.at(-1).context);assert.equal(followup.conversation.length,1);assert.match(followup.conversation[0].question,/1440/);assert.match(followup.conversation[0].answer,/Synthetic answer/);assert.equal(followup.material,'');
await chatInput.fill('未发送的追问');await askPanel.getByRole('button',{name:'关闭助手',exact:true}).click();await askPanel.waitFor({state:'hidden'});await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await askPanel.waitFor();assert.equal(await chatInput.inputValue(),'未发送的追问');assert.equal(await askPanel.locator('.chat-turn').count(),2);
for(const [width,height] of [[320,800],[390,480]]){await page.setViewportSize({width,height});const box=await chatInput.boundingBox();assert.ok(box&&box.y>=0&&box.y+box.height<=height);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+`/ask-chat-${width}x${height}.png`});}
await page.setViewportSize({width:390,height:1000});await askPanel.locator('.chat-material > summary').click();await askPanel.getByLabel('对话附加材料',{exact:true}).fill('X'.repeat(20000));await askPanel.locator('.chat-material > summary').click();await askPanel.getByRole('button',{name:'发送',exact:true}).click();await askPanel.getByText(/对话历史与材料超过本次长度限制/).waitFor();assert.equal(count(),3);assert.equal(await chatInput.inputValue(),'未发送的追问');await askPanel.getByRole('button',{name:'新对话',exact:true}).click();const reset=page.getByRole('dialog',{name:'新对话',exact:true});await reset.getByRole('button',{name:'保留对话',exact:true}).click();assert.equal(await askPanel.locator('.chat-turn').count(),2);await askPanel.getByRole('button',{name:'新对话',exact:true}).click();await reset.getByRole('button',{name:'开始新对话',exact:true}).click();await askPanel.getByRole('heading',{name:'想讨论什么？',exact:true}).waitFor();assert.equal(await chatInput.inputValue(),'');assert.equal(await askPanel.getByLabel('对话附加材料',{exact:true}).inputValue().catch(()=>''),'X'.repeat(20000));assert.equal(count(),3);
assert.deepEqual(errors,[]);
fs.writeFileSync(out+'/result.json',JSON.stringify({passed:true,calls:count(),consoleErrors:errors,checks:['oversized history blocks before network without truncation','new conversation cancellation retains turns and confirmed reset retains material','fixed composer visible on desktop/mobile/short viewport','preview cancellation preserves input and makes zero calls','follow-up includes prior conversation only in confirmed payload','close/reopen preserves turns and unsent question','shared settings entry targets connection form','cancel research navigation retains input and confirmed leave reaches form','global assistant closes on settings navigation and retains draft without provider calls','DeepSeek preset and invalid brand rejected','save configuration 0 provider calls and key cleared','cancel test 0 provider calls','confirmed test exactly 1 provider call','success result survives status refresh','320/390/768/1440 no page overflow','reload restores active model without Key','edited model disables test until saved','actionable failure no automatic retry']},null,2));console.log('P220 browser passed');
}finally{if(browser)await browser.close();if(server.exitCode===null){const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped;}fs.rmSync(dir,{recursive:true,force:true})}
