import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import net from 'node:net';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.OWNER_QA_DIR||path.join(root,'qa/p220-public'),{chromium}=createRequire(root+'/package.json')('playwright'),dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'as-p220-public-')));
fs.mkdirSync(out,{recursive:true});
const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p))})});const base=`http://127.0.0.1:${port}`,server=spawn('python3',['tests/owner/serve_market_fixture.py','--port',String(port),'--data-dir',dir+'/data'],{cwd:root,stdio:['ignore','ignore','pipe']});let browser,serr='';server.stderr.on('data',d=>serr+=d);const calls=()=>fs.existsSync(dir+'/calls.json')?JSON.parse(fs.readFileSync(dir+'/calls.json')):[];
try{for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serr);try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('public-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-public-only-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-public-only-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();await page.goto(base+'/settings/connections');
const choose=async(name,option)=>{await page.locator('.el-select').filter({has:page.getByRole('combobox',{name,exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:option,exact:true}).click()};
assert.equal(await page.getByLabel('你自己的 Alpha Vantage API Key').count(),0);assert.equal(calls().length,0);
for(const [option,label,sy,currency,canonical] of [['美国市场 · USD','美国市场标的代码','AAPL','USD','AAPL'],['沪深 A 股 · CNY','沪深 A 股代码','600104','CNY','600104'],['港股 · HKD','港股代码','0700','HKD','00700']]){await choose('行情市场',option);await page.getByLabel(label,{exact:true}).fill(sy);await delay(1100);await page.getByRole('button',{name:'主动查询日级价格',exact:true}).click();await page.getByRole('heading',{name:`${canonical} · ${currency} 190.00000000`,exact:true}).waitFor();await page.getByRole('button',{name:'确认保存价格快照',exact:true}).click();await page.getByText('价格快照已保存',{exact:true}).last().waitFor();}
await delay(1100);await page.getByRole('button',{name:'主动查询最近日线',exact:true}).click();await page.getByRole('heading',{name:'00700 · 90 根日线',exact:true}).waitFor();await page.getByRole('button',{name:'确认保存日线快照',exact:true}).click();await page.getByText('日线来源快照已保存',{exact:true}).waitFor();
const expected=calls().length;assert.equal(expected,4);assert.ok(calls().every(x=>x.host==='query1.finance.yahoo.com'));
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.settings-panel').filter({has:page.locator('.panel-title').getByText('行情服务',{exact:true})}).scrollIntoViewIfNeeded();await delay(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+`/public-${width}.png`})}
await choose('行情来源','自有 API · Alpha Vantage / EODHD');await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).waitFor();assert.equal(calls().length,expected);await choose('行情来源','公共日线 · 无需 API Key');await page.route('**/api/v1/owner/quote-fetch-public',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{code:'public_market_unavailable',message:'公共行情暂不可用，未保存。'}})}));await page.getByRole('button',{name:'主动查询日级价格',exact:true}).click();await page.getByText('公共行情暂不可用，未保存。',{exact:true}).first().waitFor();await delay(1200);assert.equal(calls().length,expected);await page.unroute('**/api/v1/owner/quote-fetch-public');
await page.goto(base+'/research');await page.getByLabel('标的代码',{exact:true}).fill('00700');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('main .technical-evidence').getByText(/趋势：上行排列/).waitFor();assert.equal(calls().length,expected);assert.deepEqual(errors,[]);fs.writeFileSync(out+'/public-result.json',JSON.stringify({passed:true,calls:expected,checks:['zero Key and zero startup request','US CN HK identity and price preview/save','public history preview/save and Research material read','four viewport widths no overflow','source switching has no provider call','public failure no automatic API fallback or retry'],errors},null,2));console.log('Public market browser passed');
}finally{if(browser)await browser.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(dir,{recursive:true,force:true})}
