// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');const output=fs.mkdtempSync(path.join(os.tmpdir(),'awesome-cockpit-fx-'));console.log('Cockpit FX evidence: '+output);
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const resultPath=path.join(output,'result.json');
const server=spawn(process.env.OWNER_PYTHON || 'python3',['tests/owner/serve_market_fixture.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type())&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const today=new Date().toISOString().slice(0,10);const ids={};
 for(const currency of ['USD','HKD']){const id=crypto.randomUUID();ids[currency]=id;await api('/api/v1/owner/accounts','POST',{id,operation_id:crypto.randomUUID(),name:`Synthetic ${currency}`,currency,opening_cash:'1000'});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,account_id:id,symbol:currency==='USD'?'ZZZ':'AAA',side:'buy',quantity:'2',price:'10',fee:'1',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol:currency==='USD'?'ZZZ':'AAA',currency,price:'20',previous_close:currency==='HKD'?'18':null,as_of:today,source:'Synthetic quote'}})}
 await page.goto(base+'/cockpit');await page.getByText('先补齐价格、汇率或刷新数据',{exact:true}).waitFor();const metric=label=>page.locator('.snapshot-metric').filter({has:page.locator('span',{hasText:label})});assert.equal(await metric('总资产').locator('strong').textContent(),'—');
 await page.goto(base+'/settings/connections');await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'行情来源',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:'自有 API · Alpha Vantage / EODHD',exact:true}).click();await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).fill('Synthetic-provider-key');await page.getByRole('button',{name:'启用行情连接',exact:true}).click();await page.getByLabel('美国市场标的代码',{exact:true}).fill('ZZZ');await page.getByRole('button',{name:'主动查询日级价格',exact:true}).click();await page.getByText('供应商昨收：18 USD；不推测缺失值。',{exact:true}).waitFor();await page.getByRole('button',{name:'确认保存价格快照',exact:true}).click();await page.getByText('价格快照已保存',{exact:true}).waitFor();await page.goto(base+'/cockpit');await page.getByText('先补齐价格、汇率或刷新数据',{exact:true}).waitFor();
 await api('/api/v1/owner/fx-rates','POST',{operation_id:crypto.randomUUID(),revision:0,currency:'HKD',rate:'0.125',as_of:today,expires_on:today,source:'Synthetic FX'});await page.getByRole('button',{name:'刷新',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.snapshot-metric strong')?.textContent==='1,146.38');assert.equal(await metric('今日估值变化').locator('strong').textContent(),'4.50');assert.equal(await metric('累计盈亏').locator('strong').textContent(),'21.38');assert.equal(await metric('累计盈亏').locator('strong').getAttribute('class'),'is-positive');assert.equal(await metric('今日估值变化').locator('strong').getAttribute('class'),'is-positive');assert.equal(await metric('当前仓位').locator('strong').textContent(),'3.93%');assert.equal(await metric('现金比例').locator('strong').textContent(),'96.07%');
 assert.equal(await page.locator('.card-title').innerText(),'核心持仓');assert.match(await page.locator('.position-row').first().innerText(),/ZZZ/);assert.match(await page.locator('.position-row').first().innerText(),/仓位 88.89%/);assert.match(await page.locator('.position-row').first().innerText(),/累计 \+90.48%/);
 const contextToggle=page.locator('.context-toggle');assert.equal(await contextToggle.getAttribute('aria-expanded'),'false');await contextToggle.click();assert.equal(await contextToggle.getAttribute('aria-expanded'),'true');assert.equal(await page.locator('.context-accounts article').count(),2);assert.match(await page.locator('.context-accounts').innerText(),/Synthetic USD · USD/);assert.match(await page.locator('.context-accounts').innerText(),/Synthetic HKD · HKD/);await page.getByRole('link',{name:'查看固定快照趋势与诊断来源'}).waitFor();await contextToggle.click();
 await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const ask=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(ask);await ask.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ask.getByText('核对载入的材料',{exact:true}).waitFor();const material=JSON.parse(await ask.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(material.base_valuation.accounts.find(a=>a.account_id===ids.HKD).fx_evidence.source,'Synthetic FX');assert.ok(material.base_valuation.accounts.every(a=>!('positions' in a)));await ask.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:path.join(output,`cockpit-fx-${width}.png`),animations:'disabled'});if(width===320){await page.getByText('基线与口径',{exact:true}).click();await page.getByRole('button',{name:'保存检查基线',exact:true}).waitFor();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:path.join(output,'cockpit-valuation-open-320.png'),animations:'disabled'});await page.getByText('基线与口径',{exact:true}).click()}}
 for(const [price,tone] of [['1','is-negative'],['10.5','is-neutral']]){
  for(const currency of ['USD','HKD']){const symbol=currency==='USD'?'ZZZ':'AAA';const record=(await api('/api/v1/owner/business')).records.find(r=>r.kind==='quote'&&r.currency===currency&&r.symbol===symbol);await api('/api/v1/owner/business','POST',{id:record.id,operation_id:crypto.randomUUID(),revision:record.revision,kind:'quote',data:{symbol,currency,price,previous_close:'10.5',as_of:today,source:'Synthetic sign boundary'}})}
  await page.getByRole('button',{name:'刷新',exact:true}).click();await page.waitForFunction(tone=>document.querySelectorAll('.snapshot-metric strong')[2]?.className===tone,tone);assert.equal(await metric('今日估值变化').locator('strong').getAttribute('class'),tone);await page.locator('.dashboard-summary .el-loading-mask').waitFor({state:'hidden'});await page.screenshot({path:path.join(output,`cockpit-${tone}-320.png`),animations:'disabled'});
 }
 await page.getByRole('button',{name:'隐藏金额',exact:true}).click();assert.equal(await metric('总资产').locator('strong').textContent(),'••••');assert.equal(await metric('累计盈亏').locator('strong').getAttribute('class'),'');await contextToggle.click();assert.deepEqual(await page.locator('.context-accounts article span').allTextContents(),['••••','••••']);await contextToggle.click();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ask);await ask.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ask.getByText('金额处于隐藏状态；如需载入驾驶舱材料，请先主动显示金额。',{exact:true}).waitFor();await ask.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'显示金额',exact:true}).click();
 await page.clock.setFixedTime(new Date(Date.now()+86400000));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>document.querySelector('.snapshot-metric strong')?.textContent==='—');await page.getByText('先补齐价格、汇率或刷新数据',{exact:true}).waitFor();assert.match(await page.locator('.position-row').first().innerText(),/累计 —/);await page.route('**/api/v1/owner/business',async route=>{const response=await route.fetch();const data=await response.json();data.base_valuation.evaluated_on=today;data.base_valuation.evaluated_market_dates={UTC:today,'Asia/Hong_Kong':today,'Asia/Shanghai':today};await route.fulfill({response,json:data})});
 await page.clock.setFixedTime(new Date(today+'T15:59:00Z'));await page.goto(base+'/cockpit');await page.waitForFunction(()=>{const e=document.querySelector('.snapshot-metric strong');return e&&e.textContent!=='—'});
 await page.clock.setFixedTime(new Date(today+'T16:01:00Z'));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>document.querySelector('.snapshot-metric strong')?.textContent==='—');
 await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ask);await ask.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ask.getByText(/请先刷新/).waitFor();await ask.getByRole('button',{name:'关闭助手',exact:true}).click();
 await page.unroute('**/api/v1/owner/business');await page.clock.setFixedTime(new Date());await page.goto(base+'/cockpit');await page.waitForFunction(()=>{const e=document.querySelector('.snapshot-metric strong');return e&&e.textContent!=='—'});
 assert.deepEqual(errors,[]);fs.writeFileSync(resultPath,JSON.stringify({passed:true,widths:[1440,390,320],missing_fx_status:true,usd_totals:true,usd_ratios:true,assistant_evidence:true,no_full_positions_in_fx:true,privacy_guard:true,pnl_positive_style:true,pnl_negative_style:true,pnl_zero_neutral:true,privacy_hides_direction:true,cross_day_hidden:true,asian_midnight_hidden:true,asian_midnight_material_rejected:true,refresh_recovers:true,provider_previous_close:true,day_price_effect:true,errors,real_provider:false}));console.log('Cockpit FX browser passed');
} catch(e) {fs.writeFileSync(resultPath,JSON.stringify({passed:false,error:String(e)}));const page=browser?.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:path.join(output,'failure.png')});console.error(await page.locator('body').innerText())}throw e;
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}

async function openAskMaterials(panel){const options=panel.locator('.page-material-options');if(!await options.evaluate(e=>e.open))await options.locator(':scope > summary').click()}
