// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const server=spawn(process.env.OWNER_PYTHON || 'python3',['start_owner.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning'&&/Failed to resolve component/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const aid=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:aid,name:'Simulation USD',currency:'USD',opening_cash:'1000',operation_id:crypto.randomUUID()});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:aid,symbol:'TEST',side:'buy',quantity:'2',price:'10',fee:'0',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:'TEST',currency:'USD',price:'20',as_of:new Date().toISOString().slice(0,10),source:'Synthetic price for simulation'}});


 const decision=await api('/api/v1/owner/documents','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'decision',title:'Execution basis',symbol:'TEST',content:'Synthetic evidence',support:'Synthetic support',counter_case:'Synthetic contrary',invalidation:'Synthetic stop',risk_limit:'Synthetic limit',review_on:new Date().toISOString().slice(0,10),research_ref:null});await api('/api/v1/owner/plans','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),title:'Execution plan',decision_ref:{id:decision.id,revision:1},plan_type:'build_up',trigger:'Manual review',steps:['First purchase'],risk_limit:'Budget',stop_condition:'Evidence changed',review_on:new Date().toISOString().slice(0,10),status:'ready'});
 await page.goto(base+'/plan/build-up');
 await page.getByRole('button',{name:'编辑计划',exact:true}).click();
 const edit=page.getByRole('dialog',{name:'编辑计划',exact:true});await edit.getByText('设置建仓目标',{exact:true}).click();assert.equal(await edit.getByRole('checkbox',{name:'设置建仓目标',exact:true}).isChecked(),true);await edit.getByLabel('建仓账户',{exact:true}).press('Enter');await page.getByRole('option').filter({hasText:'Simulation USD'}).click();await edit.getByLabel('目标股数',{exact:true}).fill('4');await edit.getByLabel('目标预算（含成交费用，可留空）',{exact:true}).fill('19');await edit.getByText('设置回撤加仓条件',{exact:true}).click();await edit.getByLabel('锚定价格',{exact:true}).fill('100');await page.setViewportSize({width:320,height:1000});await edit.getByText('设置回撤加仓条件',{exact:true}).scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+'/qa/plan-strategy-form-320.png',animations:'disabled'});await page.setViewportSize({width:1440,height:1000});await edit.getByRole('button',{name:'保存计划',exact:true}).click();await edit.waitFor({state:'hidden'});await page.getByText('0 / 4 股',{exact:true}).waitFor();await page.getByText('回撤 5%',{exact:true}).waitFor();assert.match(await page.locator('.plan-card').first().innerText(),/条件价格 ≤ 95/);
 await page.getByRole('button',{name:'关联已有成交',exact:true}).click();const dialog=page.getByRole('dialog',{name:'关联计划执行成交',exact:true});await dialog.getByLabel('已录入成交',{exact:true}).press('Enter');await page.getByRole('option').filter({hasText:'Simulation USD'}).click();await dialog.getByLabel('执行说明',{exact:true}).fill('Synthetic actual fill evidence');await dialog.getByRole('button',{name:'确认关联',exact:true}).click();await dialog.waitFor({state:'hidden'});await page.getByText('Synthetic actual fill evidence',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts[0].trades.length,1);
 await page.getByText('2 / 4 股',{exact:true}).waitFor();await page.getByRole('heading',{name:'建仓时间线 · USD',exact:true}).waitFor();assert.equal(await page.locator('.timeline-section rect').count(),1);for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.timeline-section').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/plan-timeline-${width}.png`,animations:'disabled'});}await page.getByText('50.00%',{exact:true}).waitFor();await page.getByText('实际投入已超过计划预算。',{exact:true}).waitFor();for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.plan-progress').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/plan-target-${width}.png`,animations:'disabled'});}
 const t=(await api('/api/v1/owner/ledger')).accounts[0].trades[0];await api('/api/v1/owner/trades','POST',{id:t.id,revision:t.revision,operation_id:crypto.randomUUID(),account_id:t.account_id,symbol:t.symbol,side:t.side,quantity:t.quantity,price:'11',fee:t.fee,executed_at:t.executed_at});await page.getByRole('button',{name:'刷新执行记录',exact:true}).click();await page.getByText('成交已修改或删除；此处保留关联时快照，请核对后撤销或重新关联。',{exact:true}).waitFor();assert.match(await page.locator('.execution-section').innerText(),/@ 10 USD/);await page.getByText('待核对 / 4 股',{exact:true}).waitFor();await page.getByText('1 笔关联成交待核对，未计入图表。',{exact:true}).waitFor();assert.equal(await page.locator('.timeline-section rect').count(),0);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.execution-section').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/p49-execution-${width}.png`,animations:'disabled'});}
 await page.getByRole('button',{name:'撤销关联',exact:true}).click();await page.locator('.el-popconfirm').getByRole('button',{name:'撤销关联',exact:true}).click();await page.getByText('执行成交记录 · 0 笔',{exact:true}).waitFor();await page.getByText('0 / 4 股',{exact:true}).waitFor();await page.getByText('已撤销关联（1）',{exact:true}).click();await page.getByText('Synthetic actual fill evidence',{exact:false}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts[0].trades.length,1);assert.deepEqual(errors,[]);
 const plansNow=await api('/api/v1/owner/plans'),original=plansNow.plans[0],currentTrade=plansNow.trades[0];
 await api('/api/v1/owner/plan-executions','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),plan_id:original.id,plan_revision:original.revision,step_index:0,trade_id:currentTrade.id,trade_revision:currentTrade.revision,note:'Rechecked current trade'});
 const hkd=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:hkd,name:'HKD execution',currency:'HKD',opening_cash:'100',operation_id:crypto.randomUUID()});
 const ht=await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:hkd,symbol:'TEST',side:'buy',quantity:'1',price:'5',fee:'0.2',executed_at:new Date().toISOString()});
 const hp=await api('/api/v1/owner/plans','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),title:'HKD execution plan',decision_ref:original.decision_ref,plan_type:'build_up',trigger:'Manual',steps:['First purchase'],risk_limit:'Budget',stop_condition:'Evidence',review_on:original.review_on,status:'ready'});
 await api('/api/v1/owner/plan-executions','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),plan_id:hp.id,plan_revision:hp.revision,step_index:0,trade_id:ht.id,trade_revision:ht.revision,note:'HKD independent currency'});
 await page.getByRole('button',{name:'刷新计划',exact:true}).click();await page.getByRole('heading',{name:'建仓时间线 · HKD',exact:true}).waitFor();await page.getByRole('heading',{name:'建仓时间线 · USD',exact:true}).waitFor();assert.equal(await page.locator('.timeline-section .chart-card').count(),2);assert.equal(await page.locator('.timeline-section rect').count(),2);
 const hkdChart=page.locator('.timeline-section .chart-card').filter({hasText:'建仓时间线 · HKD'});await hkdChart.locator('summary').click();assert.match(await hkdChart.locator('tbody').innerText(),/5.2/);assert.deepEqual(errors,[]);
 await page.setViewportSize({width:1440,height:1000});await page.getByLabel('搜索计划',{exact:true}).fill('HKD');await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const planAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(planAsk);await planAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await planAsk.getByText('核对载入的材料',{exact:true}).waitFor();const planMaterial=JSON.parse(await planAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(planMaterial.scope,'filtered_plans_and_execution_evidence');assert.equal(planMaterial.plans.length,1);assert.equal(planMaterial.plans[0].id,hp.id);assert.equal(planMaterial.executions.length,1);assert.equal(planMaterial.executions[0].trade.id,ht.id);assert.equal(planMaterial.executions[0].trade.currency,'HKD');assert.equal(planMaterial.filters.search,'HKD');assert.ok(!('trades' in planMaterial));await planAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 await page.getByRole('button',{name:'查看固定依据',exact:true}).click();await page.getByRole('button',{name:'在助手中核对这份历史计划',exact:true}).click();await openAskMaterials(planAsk);await planAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await page.waitForFunction(()=>{const e=document.querySelector('.assistant-scroll > details pre');return e&&JSON.parse(e.textContent).material.scope==='fixed_plan_evidence'});const historicalPlan=JSON.parse(await planAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(historicalPlan.snapshot.id,hp.id);assert.equal(historicalPlan.snapshot.decision_ref.id,original.decision_ref.id);assert.ok(!('progress' in historicalPlan.snapshot));assert.ok(!('executions' in historicalPlan));await planAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'改用当前页面材料',exact:true}).click();
 console.log('P49 execution browser passed');fs.writeFileSync(root+'/qa/p49-execution-results.json',JSON.stringify({passed:true,checks:['structured pullback rule through UI','rule threshold from anchor','narrow rule editor','separate USD and HKD timelines','chronological trade chart','stale trade excluded from chart','edit target through UI','quantity progress and fee inclusive budget','changed trade suspends progress','archive recomputes progress','link actual persisted trade','no duplicated trade','changed trade warns retaining snapshot','archive evidence retained','three viewports']}));
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}


async function openAskMaterials(panel){const options=panel.locator('.page-material-options');if(!await options.evaluate(e=>e.open))await options.locator(':scope > summary').click()}
