// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const full=process.env.OWNER_MARKET_FULL==='1';
const flat=process.env.OWNER_MARKET_FLAT==='1',resultPath=root+(full?'/qa/market-history-full-results.json':flat?'/qa/market-history-flat-results.json':'/qa/market-history-browser-results.json');
const server=spawn(process.env.OWNER_PYTHON || 'python3',['tests/owner/serve_market_fixture.py',...(flat?['--flat']:[]),'--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const callCount=()=>fs.existsSync(path.join(dir,'calls.json'))?JSON.parse(fs.readFileSync(path.join(dir,'calls.json'),'utf8')).length:0;
 await page.goto(base+'/settings/connections');await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).fill('synthetic-browser-key');await page.getByRole('button',{name:'启用行情连接',exact:true}).click();await page.getByRole('button',{name:'主动查询最近日线',exact:true}).waitFor();
 await page.getByLabel('美国市场标的代码',{exact:true}).fill('TEST');if(full){await page.locator('.el-form-item').filter({hasText:'日线历史范围'}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:'长历史（保留最近260根）',exact:true}).click()}await page.getByRole('button',{name:'主动查询最近日线',exact:true}).click();await page.getByRole('heading',{name:`TEST · ${full?260:90} 根日线`,exact:true}).waitFor();assert.equal((await api('/api/v1/owner/market-history')).snapshots.length,0);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'calls.json'))).length,1);
 await page.getByRole('button',{name:'确认保存日线快照',exact:true}).click();await page.getByText('日线来源快照已保存',{exact:true}).waitFor();const saved=(await api('/api/v1/owner/market-history')).snapshots;assert.equal(saved.length,1);assert.equal(saved[0].candles[0].close,full?'141':'101');assert.equal(saved[0].received_points,full?300:90);assert.equal(saved[0].price_basis,'raw_unadjusted');assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'calls.json'))).length,1);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth)}
 const accountId=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:accountId,operation_id:crypto.randomUUID(),name:'Synthetic research account',currency:'USD',opening_cash:'10000'});for(const [symbol,quantity] of [['TEST','3'],['OTHER','7']]){await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,account_id:accountId,symbol,side:'buy',quantity,price:'10',fee:'0',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol,currency:'USD',price:'10',as_of:new Date().toISOString().slice(0,10),source:'Synthetic price'}})}await api('/api/v1/owner/constitution','POST',{operation_id:crypto.randomUUID(),revision:0,config:{policy:{warning_percent:'20',max_percent:'30',shock_percent:'10',custom_rules:[]},require_reason_before_trade:false,prohibited_actions:[]}});
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/research');await page.getByLabel('标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('.command-conclusion').getByRole('heading',{name:'仓位达到或超过已保存纪律上限',exact:true}).waitFor();await page.locator('main .position-evidence').getByText('30.00% / 阈值 30%',{exact:true}).waitFor();const technical=page.locator('main .technical-evidence');await technical.getByText(flat?'趋势：区间 · RSI14：观察窗口无涨跌，未定义':'趋势：上行排列 · RSI14：100',{exact:true}).waitFor();if(!flat){await technical.getByText('RSI 进入超买区',{exact:true}).waitFor();await technical.getByText('趋势与动能暂时同向',{exact:true}).waitFor()}else assert.equal(await technical.getByText('RSI 进入超买区',{exact:true}).count(),0);assert.equal(await technical.locator('dt').filter({hasText:'MA120'}).evaluate(e=>e.nextElementSibling.textContent),full?'340.5':'待补');if(full)assert.equal(await technical.locator('dt').filter({hasText:'MA250'}).evaluate(e=>e.nextElementSibling.textContent),'275.5');await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const ask=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(ask);await ask.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ask.getByText('核对载入的材料',{exact:true}).waitFor();const material=JSON.parse(await ask.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(material.market_technical.source.candle_count,full?260:90);assert.ok(!('candles' in material.market_technical.source));await ask.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();const report=page.getByRole('dialog',{name:'固定研究报告',exact:true});await report.getByRole('button',{name:'第一步：预览当前报告',exact:true}).click();await report.locator('.technical-evidence').getByText(flat?'趋势：区间 · RSI14：观察窗口无涨跌，未定义':'趋势：上行排列 · RSI14：100',{exact:true}).waitFor();await report.getByRole('button',{name:'第二步：确认保存这份报告',exact:true}).click();await report.getByText('已保存固定报告',{exact:true}).waitFor();const reports=(await api('/api/v1/owner/research-reports')).reports;assert.equal(reports[0].packet.position_intelligence.risk_level,'critical');assert.equal(reports[0].packet.position_intelligence.constitution_evidence.revision,1);assert.equal(reports[0].packet.market_technical.source.id,saved[0].id);assert.equal(reports[0].packet.market_technical.technical.rsi14,flat?null:100);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'calls.json'))).length,1);await report.getByRole('button',{name:'关闭固定报告',exact:true}).click();await report.waitFor({state:'hidden'});
 await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol:'TEST',currency:'USD',price:'9',as_of:new Date().toISOString().slice(0,10),source:'Synthetic cost-line price'}});await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('main .position-evidence').getByText('Synthetic research account · 价格明显低于持仓成本',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/research-reports')).reports[0].packet.position_intelligence.context_signals.length,0);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.locator('main .position-evidence').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),`awesome-cost-context-${width}.png`),animations:'disabled'});await technical.scrollIntoViewIfNeeded();await page.screenshot({path:root+`/qa/research-technical-${full?'full-':flat?'flat-':''}${width}.png`,animations:'disabled'})}
 assert.deepEqual(errors,[]);fs.writeFileSync(resultPath,JSON.stringify({passed:true,provider_calls:1,preview_writes:0,saved_snapshots:1,real_provider:false,research_technical:true,frozen_source_binding:true,discipline_critical:true,native_market_signals:true,cost_signal_and_fixed_history:true,flat_window:flat,full_history:full,model_source_projection:true}));console.log('Market history browser passed');
} catch(e) {fs.writeFileSync(resultPath,JSON.stringify({passed:false,error:String(e)}));const page=browser?.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:root+'/qa/market-history-failure.png'});console.error(await page.locator('body').innerText())}throw e;
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}

async function openAskMaterials(panel){const options=panel.locator('.page-material-options');if(!await options.evaluate(e=>e.open))await options.locator(':scope > summary').click()}
