// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const server=spawn(process.env.OWNER_PYTHON || 'python3',['start_owner.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();const brandedAsk=page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true});assert.match(await brandedAsk.innerText(),/Ask AI/);assert.equal(await brandedAsk.locator('img').getAttribute('src'),'/logo.svg');await brandedAsk.click();await page.getByRole('dialog',{name:'Ask Awesome',exact:true}).waitFor();assert.equal(await brandedAsk.getAttribute('aria-expanded'),'true');await page.getByRole('button',{name:'关闭助手',exact:true}).click();assert.equal(await brandedAsk.getAttribute('aria-expanded'),'false');
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});







 await page.getByRole('button',{name:'新增账户',exact:true}).first().click();
 await page.getByLabel('账户名称',{exact:true}).fill('CSV USD');await page.getByLabel('期初现金',{exact:true}).fill('1000');
 assert.equal(await page.getByRole('radio',{name:'FIFO',exact:true}).isChecked(),true);
 await page.getByRole('button',{name:'创建',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 const created=(await api('/api/v1/owner/ledger')).accounts[0];assert.equal(created.cost_method,'fifo');const aid=created.id;
 assert.match(await page.locator('.book-meta').innerText(),/FIFO/);assert.match(await page.locator('.el-table__row').first().innerText(),/0.00 USD/);
 await page.getByRole('button',{name:'编辑',exact:true}).click();await page.getByRole('dialog').waitFor();
 await page.getByLabel('券商',{exact:true}).fill('Synthetic broker');assert.equal(await page.getByRole('radio',{name:'FIFO',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'保存修改',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByText('Synthetic broker · FIFO成本',{exact:true}).waitFor();
 const edited=(await api('/api/v1/owner/ledger')).accounts[0];assert.equal(edited.revision,2);assert.equal(edited.cash,'1000');assert.equal(edited.cost_method,'fifo');

 await page.goto(base+'/settings');await page.waitForURL('**/settings/account');await page.getByRole('button',{name:'导入与导出',exact:true}).click();await page.getByRole('heading',{name:'导入与导出',exact:true}).waitFor();const templateWait=page.waitForEvent('download');await page.getByRole('button',{name:'下载 CSV 模板',exact:true}).click();const template=await templateWait;await template.saveAs(dir+'/template.csv');const header=fs.readFileSync(dir+'/template.csv','utf8');assert.equal(header,'record_id,symbol,side,quantity,price,fee,executed_at\n'.replace('\\n','\n'));
 const csv=header+'r1,TEST,buy,2,10,1,'+new Date().toISOString()+'\n';const input=page.locator('input[type=file]');await input.setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByRole('button',{name:'预览导入',exact:true}).click();await page.getByRole('button',{name:'确认导入成交',exact:true}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts[0].trades.length,0);assert.match(await page.locator('.import-preview').innerText(),/1000 → 979/);await page.setViewportSize({width:320,height:900});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.locator('.import-preview').scrollIntoViewIfNeeded();await page.screenshot({path:root+'/qa/vue-browser-preview-320.png',animations:'disabled'});await page.setViewportSize({width:1440,height:1000});await api('/api/v1/owner/accounts','POST',{id:crypto.randomUUID(),name:'Changed ledger',currency:'USD',opening_cash:'0',operation_id:crypto.randomUUID()});await page.getByRole('button',{name:'确认导入成交',exact:true}).click();await page.getByText('传输未完成',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts.find(a=>a.id===aid).trades.length,0);await page.getByRole('button',{name:'预览导入',exact:true}).click();await page.getByRole('button',{name:'确认导入成交',exact:true}).click();await page.getByText('已导入 1 笔，跳过 0 笔重复记录。',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts.find(a=>a.id===aid).cash,'979');
 await input.setInputFiles({name:'same.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await page.getByRole('button',{name:'预览导入',exact:true}).click();await page.getByText('没有新增成交，无需导入。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'确认导入成交',exact:true}).count(),0);await input.setInputFiles({name:'conflict.csv',mimeType:'text/csv',buffer:Buffer.from(csv.replace(',2,10,',',3,10,'))});await page.getByRole('button',{name:'预览导入',exact:true}).click();await page.getByText('存在错误或冲突，整批不会写入。',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'确认导入成交',exact:true}).count(),0);
 const exportWait=page.waitForEvent('download');await page.getByRole('button',{name:'下载业务 JSON',exact:true}).click();const exported=await exportWait;await exported.saveAs(dir+'/business.json');const data=JSON.parse(fs.readFileSync(dir+'/business.json','utf8'));assert.equal(data.format,'awesome-stock-owner-business');assert.doesNotMatch(JSON.stringify(data),/Synthetic-Portfolio-2026|digest_hex|synthetic-key/);assert.match(JSON.stringify(data),/csv-/);
 await input.setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from([0xff,0xfe,0xff])});await page.getByRole('button',{name:'预览导入',exact:true}).click();await page.getByText('文件不是有效UTF-8，请转换编码后重试。',{exact:true}).waitFor();assert.equal(await page.locator('.import-preview').count(),0);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:root+`/qa/vue-browser-debug-${width}.png`,animations:'disabled'});console.log(width,await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,over:[...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,12).map(e=>[e.tagName,e.className,e.getBoundingClientRect().width])})));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.locator('.el-message').first().waitFor({state:'hidden'});await page.screenshot({path:root+`/qa/vue-browser-${width}.png`,animations:'disabled'});}

 // Account cards use real persisted snapshots, and never aggregate USD with HKD.
 await api('/api/v1/owner/accounts','POST',{id:crypto.randomUUID(),name:'HKD book',currency:'HKD',opening_cash:'500',operation_id:crypto.randomUUID()});
 await page.goto(base+'/portfolio/accounts');const book=page.locator('.book-card').filter({hasText:'CSV USD'});
 await book.getByText('缺少有效价格',{exact:false}).waitFor();assert.equal(await book.locator('.book-value').innerText(),'— USD');assert.match(await book.innerText(),/1 项缺价/);
 const quoteId=crypto.randomUUID();
 await api('/api/v1/owner/business','POST',{id:quoteId,revision:0,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:'TEST',currency:'USD',price:'20',as_of:new Date().toISOString().slice(0,10),source:'Synthetic account valuation'}});
 await page.reload();await book.getByText('按已记录价格',{exact:false}).waitFor();assert.equal(await book.locator('.book-value').innerText(),'40.00 USD');assert.match(await book.innerText(),/折算收益 19.00 USD/);assert.match(await book.innerText(),/第一大持仓 TEST/);assert.match(await book.innerText(),/美元持仓占比 100.00%/);
 assert.match(await page.locator('.summary-card').filter({hasText:'HKD 账本'}).innerText(),/0.00 USD/);const valuedRow=page.locator('.el-table__row').filter({hasText:'CSV USD'});assert.match(await valuedRow.innerText(),/Synthetic broker/);assert.equal(await valuedRow.locator('.account-native-value').innerText(),'40.00 USD');assert.equal(await valuedRow.locator('.account-total-return').innerText(),'19.00 USD');assert.equal(await valuedRow.locator('.account-leading').innerText(),'TEST');
 await page.getByRole('button',{name:'汇率依据',exact:true}).click();const fxDialog=page.getByRole('dialog',{name:'汇率依据',exact:true});await fxDialog.getByLabel('兑换美元汇率',{exact:true}).fill('0.125');await fxDialog.getByLabel('汇率来源',{exact:true}).fill('Synthetic FX source');await fxDialog.getByRole('button',{name:'保存汇率',exact:true}).click();await fxDialog.waitFor({state:'hidden'});assert.equal((await api('/api/v1/owner/fx-rates')).rates[0].rate,'0.125');
 await page.getByRole('button',{name:'汇率依据',exact:true}).click();await fxDialog.getByText('当前版本 1；保存后保留旧版本。',{exact:true}).waitFor();await fxDialog.getByLabel('兑换美元汇率',{exact:true}).fill('0.13');await fxDialog.getByRole('button',{name:'保存汇率',exact:true}).click();await fxDialog.waitFor({state:'hidden'});assert.equal((await api('/api/v1/owner/fx-rates')).versions.length,2);assert.match(await page.locator('.summary-card').filter({hasText:'主账本'}).innerText(),/CSV USD/);
 // Foreign holdings drive ranking only with a current rate; never use cash as holding value.
 const hkdId=(await api('/api/v1/owner/ledger')).accounts.find(a=>a.name==='HKD book').id;
 await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:hkdId,symbol:'FXTEST',side:'buy',quantity:'4',price:'10',fee:'0',executed_at:new Date().toISOString()});
 await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:'FXTEST',currency:'HKD',price:'80',as_of:new Date().toISOString().slice(0,10),source:'Synthetic foreign quote'}});
 await page.reload();const hkdBook=page.locator('.book-card').filter({hasText:'HKD book'});await hkdBook.getByText('41.60 USD',{exact:true}).waitFor();assert.match(await hkdBook.locator('.book-native').innerText(),/320.00 HKD/);assert.match(await hkdBook.innerText(),/美元持仓占比 50.98%/);assert.equal(await page.locator('.book-card').first().locator('.book-name').innerText(),'HKD book');
 await page.getByRole('button',{name:'汇率依据',exact:true}).click();const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);await fxDialog.getByLabel('汇率日期',{exact:true}).fill(yesterday);await fxDialog.getByLabel('汇率有效至',{exact:true}).fill(yesterday);await fxDialog.getByRole('button',{name:'保存汇率',exact:true}).click();await fxDialog.waitFor({state:'hidden'});await hkdBook.getByText('— USD',{exact:true}).waitFor();assert.match(await hkdBook.innerText(),/汇率过期/);assert.match(await hkdBook.locator('.converted-return').innerText(),/— USD/);assert.match(await hkdBook.innerText(),/美元持仓占比 —/);assert.equal(await page.locator('.summary-card').filter({hasText:'主账本'}).locator('.summary-value').innerText(),'—');
 await page.getByRole('button',{name:'汇率依据',exact:true}).click();const today=new Date().toISOString().slice(0,10);await fxDialog.getByLabel('汇率日期',{exact:true}).fill(today);await fxDialog.getByLabel('汇率有效至',{exact:true}).fill(today);await fxDialog.getByLabel('兑换美元汇率',{exact:true}).fill('0.14');await fxDialog.getByRole('button',{name:'保存汇率',exact:true}).click();await fxDialog.waitFor({state:'hidden'});await hkdBook.getByText('44.80 USD',{exact:true}).waitFor();assert.match(await hkdBook.locator('.converted-return').innerText(),/39.20 USD/);assert.match(await page.locator('.summary-card').filter({hasText:'HKD 账本'}).innerText(),/44.80 USD/);assert.match(await page.locator('.summary-card').filter({hasText:'主账本'}).innerText(),/52.83% · 44.80 USD/);assert.match(await hkdBook.innerText(),/美元持仓占比 52.83%/);assert.match(await page.locator('.summary-card').filter({hasText:'主账本'}).innerText(),/HKD book/);
 await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const accountAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(accountAsk);await accountAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await accountAsk.getByText('核对载入的材料',{exact:true}).waitFor();const accountMaterial=JSON.parse(await accountAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(accountMaterial.scope,'account_valuation_snapshot');assert.equal(accountMaterial.lead_account_id,hkdId);const fxMaterial=accountMaterial.accounts.find(a=>a.id===hkdId);assert.equal(fxMaterial.usd_valuation.fx_evidence.rate,'0.14');assert.equal(fxMaterial.usd_valuation.holdings_value_usd,'44.80');assert.ok(accountMaterial.accounts.every(a=>!('trades' in a)));assert.doesNotMatch(JSON.stringify(accountMaterial),/Synthetic-Portfolio-2026/);await accountAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 // A date change invalidates yesterday's display even when revalidation fails.
 const accountClock=Date.now();await page.route('**/api/v1/owner/base-valuation',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic valuation refresh unavailable'}})}));await page.clock.setFixedTime(new Date(accountClock+86400000));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.getByText('Synthetic valuation refresh unavailable',{exact:true}).waitFor();assert.equal(await hkdBook.locator('.book-value').innerText(),'— USD');assert.match(await hkdBook.locator('.book-native').innerText(),/等待更新估值/);assert.equal(await page.locator('.summary-card').filter({hasText:'主账本'}).locator('.summary-value').innerText(),'—');
 await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(accountAsk);await accountAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await accountAsk.getByText('账户估值尚未就绪，请先在账户页完成刷新。',{exact:true}).waitFor();assert.equal(JSON.parse(await accountAsk.locator('.assistant-scroll > details pre').textContent()).material.evaluated_on,accountMaterial.evaluated_on);await accountAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 await page.unroute('**/api/v1/owner/base-valuation');await page.clock.setFixedTime(new Date(accountClock));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.getByRole('button',{name:'重新加载',exact:true}).click();await hkdBook.getByText('44.80 USD',{exact:true}).waitFor();assert.equal(await page.getByText('Synthetic valuation refresh unavailable',{exact:true}).count(),0);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);const accountTable=page.locator('.el-table[aria-label="账户账本"]');for(const edge of [0,1]){await accountTable.locator('.el-scrollbar__wrap').evaluate((el,edge)=>{el.scrollLeft=edge?el.scrollWidth:0},edge);await page.waitForTimeout(100);const fixedBackground=await accountTable.locator('td.el-table-fixed-column--right').first().evaluate(el=>getComputedStyle(el).backgroundColor);assert.ok(!fixedBackground.includes('rgba')&&!fixedBackground.includes('/')&&fixedBackground!=='transparent','fixed actions mask scrolling text');const box=await accountTable.locator('.el-table__row').filter({hasText:'CSV USD'}).getByRole('button',{name:'编辑',exact:true}).boundingBox();assert.ok(box&&box.x>=0&&box.x+box.width<=width,'account edit stays visible while scrolling');}await accountTable.locator('.el-scrollbar__wrap').evaluate(el=>el.scrollLeft=0);await page.screenshot({path:root+`/qa/vue-accounts-valued-${width}.png`,animations:'disabled'});}
 const emptyRow=page.locator('.el-table__row').filter({hasText:'Changed ledger'});
 await emptyRow.getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();
 assert.equal((await api('/api/v1/owner/ledger')).accounts.length,3);
 await emptyRow.getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'删除账户',exact:true}).click();await emptyRow.waitFor({state:'hidden'});
 assert.equal((await api('/api/v1/owner/ledger')).accounts.length,2);
 await page.locator('.el-table__row').filter({hasText:'CSV USD'}).getByRole('button',{name:'删除',exact:true}).click();await page.getByRole('button',{name:'删除账户',exact:true}).click();
 await page.getByText('账户有现金、成交、资金流水或历史业务引用，不能删除。请保留账户以供核对。',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/ledger')).accounts.length,2);
 await api('/api/v1/owner/business','DELETE',{id:quoteId,revision:1,operation_id:crypto.randomUUID()});
 await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:'TEST',currency:'USD',price:'20',as_of:new Date(Date.now()-7*86400000).toISOString().slice(0,10),source:'Synthetic expired price'}});
 await page.reload();await book.getByText('缺少有效价格',{exact:false}).waitFor();assert.equal(await book.locator('.book-value').innerText(),'— USD');assert.match(await book.innerText(),/1 项价格过期/);assert.equal(await page.locator('.el-table__row').filter({hasText:'CSV USD'}).locator('.account-native-value').innerText(),'— USD');
 await page.goto(base+'/research');await page.locator('.lens-panel').waitFor();await page.getByLabel('标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('.report-command').waitFor();assert.equal(await page.locator('.lens-panel').count(),0);assert.equal(await page.locator('.research-hero.is-compact').count(),1);await page.getByRole('button',{name:'调整研究问题',exact:true}).click();await page.locator('.lens-card').filter({hasText:'持仓语境'}).click();assert.equal(await page.locator('.position-card').count(),0);await page.getByRole('button',{name:'收起研究问题',exact:true}).click();assert.equal(await page.locator('.lens-panel').count(),0);for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/research-reading-${width}.png`,animations:'disabled'});}await page.getByRole('button',{name:'调整研究问题',exact:true}).click();await page.locator('.lens-card').filter({hasText:'持仓语境'}).click();await page.getByRole('button',{name:'收起研究问题',exact:true}).click();await page.locator('.position-card').waitFor();
 await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const askPanel=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(askPanel);await askPanel.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await askPanel.getByText('核对载入的材料',{exact:true}).waitFor();const askMaterial=JSON.parse(await askPanel.locator('.assistant-scroll > details pre').textContent());assert.deepEqual(askMaterial.material.symbols,['TEST']);assert.ok(askMaterial.material.research_questions.some(q=>q.id==='position'));await askPanel.getByRole('button',{name:'关闭助手',exact:true}).click();
 // Hard navigation checks every shipped lazy page and its source CSS on a small screen.
 assert.equal(await page.locator('.command-conclusion h2').textContent(),'有持仓但缺少保存判断，先补充可证伪的投资逻辑');await api('/api/v1/owner/documents','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'decision',title:'Synthetic saved thesis',symbol:'TEST',content:'Evidence-based synthetic thesis',support:'Synthetic supporting material',counter_case:'Synthetic contrary material',invalidation:'Synthetic thesis fails',risk_limit:'Synthetic limit',review_on:new Date().toISOString().slice(0,10),research_ref:null});await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.command-conclusion h2')?.textContent==='已有保存判断，后续行动仍需绑定证据和条件');await page.locator('.report-basis summary').click();assert.match(await page.locator('.command-conclusion').innerText(),/Synthetic thesis fails/);await page.locator('.report-basis summary').click();
 const concentrationQuote=crypto.randomUUID();await api('/api/v1/owner/business','POST',{id:concentrationQuote,operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol:'TEST',currency:'USD',price:'200',as_of:new Date().toISOString().slice(0,10),source:'Synthetic concentration fixture'}});await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.command-conclusion h2')?.textContent==='先复核仓位集中度，再判断个股逻辑');assert.match(await page.locator('.command-conclusion').innerText(),/不是你的个人纪律阈值/);
 await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();const historyDialog=page.getByRole('dialog',{name:'固定研究报告',exact:true});await historyDialog.getByRole('button',{name:'第一步：预览当前报告',exact:true}).click();await historyDialog.getByRole('button',{name:'第二步：确认保存这份报告',exact:true}).click();await historyDialog.getByText('已保存固定报告',{exact:true}).waitFor();assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/市值 400/);const fixedReport=(await api('/api/v1/owner/research-reports')).reports[0];assert.equal(fixedReport.packet.rule_report.summary.posture,'risk_review');assert.equal(fixedReport.packet.rule_report.concentration.triggered,true);assert.match(fixedReport.packet.rule_report.concentration.scope,/不含现金/);assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/全组合持仓美元市值占比/);await historyDialog.getByRole('button',{name:'关闭固定报告',exact:true}).click();await historyDialog.waitFor({state:'hidden'});await api('/api/v1/owner/business','POST',{id:concentrationQuote,operation_id:crypto.randomUUID(),revision:1,kind:'quote',data:{symbol:'TEST',currency:'USD',price:'400',as_of:new Date().toISOString().slice(0,10),source:'Changed after fixed research'}});await page.reload();await page.getByLabel('标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('.report-command').waitFor();await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();if(await historyDialog.getByLabel('已保存研究报告',{exact:true}).getAttribute('aria-expanded')!=='true')await historyDialog.locator('.el-select__wrapper').click();await page.getByRole('option',{name:fixedReport.packet.symbol+' · '+fixedReport.updated_at,exact:true}).click();assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/市值 400/);assert.doesNotMatch(await historyDialog.locator('.fixed-research-report').innerText(),/市值 800/);
 await page.route('**/api/v1/owner/research-report-preview',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic preview failure',code:'synthetic_preview_failure'}})}));
 await historyDialog.getByRole('button',{name:'第一步：预览当前报告',exact:true}).click();
 await historyDialog.getByText('Synthetic preview failure',{exact:false}).waitFor();
 assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/市值 400/);
 assert.equal(await historyDialog.getByRole('button',{name:'第二步：确认保存这份报告',exact:true}).count(),0);
 await page.unroute('**/api/v1/owner/research-report-preview');
 await historyDialog.getByRole('button',{name:'关闭固定报告',exact:true}).click();await historyDialog.waitFor({state:'hidden'});
 await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();
 assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/市值 400/);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/p104-research-history-${width}.png`});}await historyDialog.getByRole('button',{name:'关闭固定报告',exact:true}).click();await historyDialog.waitFor({state:'hidden'});
 await page.route('**/api/v1/owner/research-reports',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic history failure',code:'synthetic_history_failure'}})}));
 await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();
 await historyDialog.getByText('Synthetic history failure',{exact:false}).waitFor();
 assert.equal(await historyDialog.locator('.fixed-research-report').count(),0);
 await historyDialog.getByRole('button',{name:'关闭固定报告',exact:true}).click();await historyDialog.waitFor({state:'hidden'});
 await page.unroute('**/api/v1/owner/research-reports');
 const legacyReport=structuredClone(fixedReport);delete legacyReport.packet.rule_report;await page.route('**/api/v1/owner/research-reports',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({reports:[legacyReport]})}));await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();if(await historyDialog.getByLabel('已保存研究报告',{exact:true}).getAttribute('aria-expanded')!=='true')await historyDialog.locator('.el-select__wrapper').click();await page.getByRole('option',{name:fixedReport.packet.symbol+' · '+fixedReport.updated_at,exact:true}).click();assert.match(await historyDialog.locator('.fixed-research-report').innerText(),/未记录规则摘要/);await historyDialog.getByRole('button',{name:'关闭固定报告',exact:true}).click();await historyDialog.waitFor({state:'hidden'});await page.unroute('**/api/v1/owner/research-reports');
 // A mounted research page must re-evaluate expiry when returning after midnight.
 const clockNow=Date.now(),clockToday=new Date(clockNow).toISOString().slice(0,10);await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'evidence',data:{symbol:'TEST',title:'Expiry boundary evidence',metric:'pe',value:'12',source:'Synthetic clock fixture',as_of:clockToday,expires_on:clockToday,verification:'verified'}});await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.snapshot-grid')?.textContent.includes('12'));await page.clock.setFixedTime(new Date(clockNow+4*86400000));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>document.querySelector('.report-actions')?.textContent.includes('Expiry boundary evidence：已过期'));assert.ok(!(await page.locator('.snapshot-grid').innerText()).includes('12'));assert.match(await page.locator('.position-card').innerText(),/—/);await page.clock.setFixedTime(new Date(clockNow));await page.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await page.waitForFunction(()=>document.querySelector('.snapshot-grid')?.textContent.includes('12'));
 // Switching or refreshing research must not attach prior material to a new symbol.
 const assistant=page.locator('main .assistant-workbench');await assistant.getByLabel('研究问题',{exact:true}).fill('Keep this TEST question');await assistant.getByRole('button',{name:'填入当前研究材料',exact:true}).click();const oldContext=await assistant.getByLabel('待发送上下文',{exact:true}).inputValue();
 await page.getByLabel('标的代码',{exact:true}).fill('OTHER');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.getByRole('button',{name:'保留当前研究',exact:true}).click();assert.equal(await page.locator('.report-identity h2').textContent(),'TEST');assert.equal(await assistant.getByLabel('待发送上下文',{exact:true}).inputValue(),oldContext);
 await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.getByRole('button',{name:'载入并清除',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.report-identity h2')?.textContent==='OTHER');assert.equal(await assistant.getByLabel('研究问题',{exact:true}).inputValue(),'');assert.equal(await assistant.getByLabel('待发送上下文',{exact:true}).inputValue(),'');assert.equal(await page.locator('.command-conclusion h2').textContent(),'先补齐关键证据，再决定是否进入观察清单');assert.match(await page.locator('.report-actions').innerText(),/证据缺口/);
 await assistant.getByLabel('研究问题',{exact:true}).fill('Keep on failed refresh');await page.route('**/api/v1/owner/documents',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic refresh failure'})}));await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.getByRole('button',{name:'载入并清除',exact:true}).click();await page.getByText('研究材料未更新',{exact:true}).waitFor();assert.equal(await assistant.getByLabel('研究问题',{exact:true}).inputValue(),'Keep on failed refresh');assert.equal(await page.locator('.report-identity h2').textContent(),'OTHER');await page.unroute('**/api/v1/owner/documents');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.getByRole('button',{name:'载入并清除',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('main .assistant-workbench textarea')?.value);assert.equal(await assistant.getByLabel('研究问题',{exact:true}).inputValue(),'');
 const routes=['/cockpit','/portfolio','/portfolio/accounts','/portfolio/trades','/portfolio/cash','/research','/research/batch','/research/screening','/research/notes','/decisions','/plan/allocation','/plan/pre-trade','/plan/budget','/plan/build-up','/review','/review/rules','/review/diagnosis','/academy','/settings/account','/settings/appearance','/settings/connections','/settings/transfer'];
 const visual=[];
 for(const route of routes){
   await page.goto(base+route);await page.waitForFunction(()=>document.title.endsWith(' · Awesome Stock'));
   await page.locator('main').waitFor();await page.waitForLoadState('networkidle');
   assert.equal(new URL(page.url()).pathname,route);
   assert.ok((await page.locator('main').innerText()).trim().length>0,route);
   for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);const name=route.slice(1).replaceAll('/','-')+'-'+width+'.png';await page.screenshot({path:path.join(root,'qa','route-'+name),animations:'disabled'});visual.push({route,width,screenshot:'route-'+name});}
   if(route==='/review/diagnosis'){const colors=await page.locator('.header-info .title').evaluate(el=>({actual:getComputedStyle(el).color,expected:getComputedStyle(document.documentElement).getPropertyValue('--el-text-color-primary').trim()}));assert.notEqual(colors.actual,'rgb(48, 49, 51)');}
   await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);
 }
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/portfolio/trades');await page.getByLabel('搜索标的',{exact:true}).fill('FXTEST');await page.locator('.ticker-cell').filter({hasText:'FXTEST'}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const ledgerAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(ledgerAsk);await ledgerAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ledgerAsk.getByText('核对载入的材料',{exact:true}).waitFor();const tradeMaterial=JSON.parse(await ledgerAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(tradeMaterial.scope,'filtered_trade_page');assert.equal(tradeMaterial.filters.symbol,'FXTEST');assert.equal(tradeMaterial.records.length,1);assert.equal(tradeMaterial.records[0].symbol,'FXTEST');assert.equal(tradeMaterial.accounts.length,1);assert.equal(tradeMaterial.accounts[0].currency,'HKD');assert.ok(!('holdings' in tradeMaterial.accounts[0]));await ledgerAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(let i=0;i<22;i++)await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:aid,symbol:'PAGE',side:'buy',quantity:'1',price:'1',fee:'0',executed_at:new Date().toISOString()});
 await page.goto(base+'/portfolio/trades');await page.getByLabel('搜索标的',{exact:true}).fill('PAGE');await page.locator('.el-pagination').waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ledgerAsk);await ledgerAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ledgerAsk.getByText('核对载入的材料',{exact:true}).waitFor();const firstTradePage=JSON.parse(await ledgerAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(firstTradePage.total_filtered,22);assert.equal(firstTradePage.records.length,20);assert.equal(firstTradePage.page,1);await ledgerAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.locator('.el-pagination .btn-next').click();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ledgerAsk);await ledgerAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await page.waitForFunction(()=>{const e=document.querySelector('.assistant-scroll > details pre');return e&&JSON.parse(e.textContent).material.page===2});const secondTradePage=JSON.parse(await ledgerAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(secondTradePage.records.length,2);assert.equal(secondTradePage.total_filtered,22);assert.ok(secondTradePage.records.every(r=>!firstTradePage.records.some(p=>p.id===r.id)));await ledgerAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(const [account_id,amount] of [[aid,'5'],[hkdId,'7']])await api('/api/v1/owner/cash-flows','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id,direction:'deposit',amount,occurred_at:new Date().toISOString(),note:'Synthetic filtered cash'});
 await page.goto(base+'/portfolio/cash');await page.locator('.cash-filter .el-select__wrapper').click();await page.getByRole('option',{name:'HKD book · HKD',exact:true}).click();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ledgerAsk);await ledgerAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ledgerAsk.getByText('核对载入的材料',{exact:true}).waitFor();const cashMaterial=JSON.parse(await ledgerAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(cashMaterial.scope,'filtered_cash_flows');assert.equal(cashMaterial.account_filter,hkdId);assert.equal(cashMaterial.records.length,1);assert.equal(cashMaterial.records[0].amount,'7');assert.equal(cashMaterial.accounts.length,1);assert.ok(!('trades' in cashMaterial.accounts[0]));assert.ok(!('holdings' in cashMaterial.accounts[0]));await ledgerAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 const historicalFlow=(await api('/api/v1/owner/ledger')).accounts.find(a=>a.id===hkdId).cash_flows[0];await api('/api/v1/owner/cash-flows','POST',{id:historicalFlow.id,revision:historicalFlow.revision,operation_id:crypto.randomUUID(),account_id:hkdId,direction:'deposit',amount:'8',occurred_at:historicalFlow.occurred_at,note:'Synthetic revised cash'});await api('/api/v1/owner/cash-flows','DELETE',{id:historicalFlow.id,revision:historicalFlow.revision+1,operation_id:crypto.randomUUID()});
 await page.reload();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(ledgerAsk);await ledgerAsk.locator('.el-select__wrapper').first().click();await page.getByRole('option',{name:'全部账户的资金修改历史',exact:true}).click();await openAskMaterials(ledgerAsk);await ledgerAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await ledgerAsk.getByText('核对载入的材料',{exact:true}).waitFor();const historicalCash=JSON.parse(await ledgerAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(historicalCash.scope,'cash_revision_history');assert.equal(historicalCash.account_filter,null);const flowVersions=historicalCash.records.filter(r=>r.id===historicalFlow.id);assert.equal(flowVersions.length,3);assert.ok(flowVersions.some(r=>r.deleted));assert.ok(flowVersions.some(r=>r.amount==='7'));assert.match(historicalCash.notice,/不能重复计入当前余额/);assert.equal(historicalCash.accounts.find(a=>a.id===hkdId).deposits,'0');await ledgerAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 const scopedRule=await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'rule',data:{title:'Scoped review rule',condition:'Synthetic condition',action:'Manual review',scope:'Synthetic scope',enabled:false}});
 await page.goto(base+'/review/rules');await page.getByText(/当前区间共 .* 条复盘/).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const rulesAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(rulesAsk);await rulesAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await rulesAsk.getByText('核对载入的材料',{exact:true}).waitFor();const ruleMaterial=JSON.parse(await rulesAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(ruleMaterial.scope,'rules_and_review_trend');assert.equal(ruleMaterial.rules.find(r=>r.id===scopedRule.id).enabled,false);assert.equal(ruleMaterial.trend_status,'queried');assert.equal(ruleMaterial.trend.from,ruleMaterial.range.from);assert.ok(!('accounts' in ruleMaterial));await rulesAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByLabel('开始日期',{exact:true}).fill(new Date(Date.now()-86400000).toISOString().slice(0,10));await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(rulesAsk);await rulesAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await page.waitForFunction(()=>{const e=document.querySelector('.assistant-scroll > details pre');return e&&JSON.parse(e.textContent).material.trend_status==='needs_query'});const noTrend=JSON.parse(await rulesAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(noTrend.trend,null);assert.notEqual(noTrend.range.from,ruleMaterial.range.from);await rulesAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 const referenceNote={id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'note',title:'Pinned reference source',symbol:'PINNED',content:'Original research version',support:'',counter_case:'',invalidation:'',risk_limit:'',review_on:'',research_ref:null};await api('/api/v1/owner/documents','POST',referenceNote);
 const pinnedDecision=await api('/api/v1/owner/documents','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'decision',title:'Pinned reference decision',symbol:'PINNED',content:'Judgment using original research',support:'Synthetic support',counter_case:'Synthetic contrary',invalidation:'Synthetic stop',risk_limit:'Synthetic limit',review_on:new Date().toISOString().slice(0,10),research_ref:{id:referenceNote.id,revision:1}});await api('/api/v1/owner/documents','POST',{...referenceNote,revision:1,operation_id:crypto.randomUUID(),content:'New research version must not replace old reference'});
 await page.goto(base+'/decisions');await page.getByLabel('搜索记录',{exact:true}).fill('Pinned reference decision');await page.locator('.entry-card').filter({hasText:'Pinned reference decision'}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const decisionAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(decisionAsk);await decisionAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await decisionAsk.getByText('核对载入的材料',{exact:true}).waitFor();const pinnedMaterial=JSON.parse(await decisionAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(pinnedMaterial.records.length,1);assert.equal(pinnedMaterial.referenced_research.length,1);assert.equal(pinnedMaterial.referenced_research[0].record.revision,1);assert.equal(pinnedMaterial.referenced_research[0].record.content,'Original research version');assert.doesNotMatch(JSON.stringify(pinnedMaterial),/New research version/);await decisionAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 await api('/api/v1/owner/documents','DELETE',{id:pinnedDecision.id,revision:1,operation_id:crypto.randomUUID()});await page.reload();await page.getByLabel('搜索记录',{exact:true}).fill('Pinned reference decision');await page.getByText('没有符合条件的记录',{exact:true}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(decisionAsk);await decisionAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await decisionAsk.getByText('核对载入的材料',{exact:true}).waitFor();assert.equal(JSON.parse(await decisionAsk.locator('.assistant-scroll > details pre').textContent()).material.records.length,0);await decisionAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByText('包含已归档',{exact:true}).click();await page.locator('.entry-card').filter({hasText:'Pinned reference decision'}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(decisionAsk);await decisionAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await page.waitForFunction(()=>{const e=document.querySelector('.assistant-scroll > details pre');return e&&JSON.parse(e.textContent).material.filters.include_archived===true});const archivedMaterial=JSON.parse(await decisionAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(archivedMaterial.records.length,1);assert.equal(archivedMaterial.records[0].archived,true);assert.equal(archivedMaterial.referenced_research[0].record.revision,1);await decisionAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(const [symbol,market] of [['TEST','US'],['FXTEST','HK']])await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'candidate',data:{symbol,market,title:'Scoped candidate '+symbol,thesis:'Synthetic observation',review_on:new Date().toISOString().slice(0,10)}});
 await page.goto(base+'/research/screening');const candidateRow=page.locator('.el-table__row').filter({hasText:'Scoped candidate FXTEST'});await candidateRow.waitFor();await candidateRow.locator('.el-checkbox').click();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const researchAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(researchAsk);await researchAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await researchAsk.getByText('核对载入的材料',{exact:true}).waitFor();const screeningMaterial=JSON.parse(await researchAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(screeningMaterial.scope,'selected_screening_results');assert.equal(screeningMaterial.rows.length,1);assert.equal(screeningMaterial.rows[0].candidate.symbol,'FXTEST');assert.equal(screeningMaterial.rows[0].status,'needs_evidence');await researchAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByLabel('最低营收增长 %',{exact:true}).fill('99');assert.equal(await page.getByRole('button',{name:'交接为研究笔记',exact:true}).isEnabled(),false);await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(researchAsk);await researchAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await researchAsk.getByText('请先按当前条件重新筛选，并关闭编辑或历史窗口，再载入材料。',{exact:true}).waitFor();await researchAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 await page.goto(base+'/research/batch');await page.getByLabel('批量研究标的',{exact:true}).fill('TEST FXTEST');await page.getByRole('button',{name:'准备逐标的材料',exact:true}).click();await page.locator('.batch-summary').waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(researchAsk);await researchAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await researchAsk.getByText('核对载入的材料',{exact:true}).waitFor();const batchMaterial=JSON.parse(await researchAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(batchMaterial.scope,'prepared_batch_sources');assert.deepEqual(batchMaterial.items.map(i=>i.symbol),['TEST','FXTEST']);assert.ok(batchMaterial.items.every(i=>i.source.records.every(r=>r.symbol===i.symbol)));await researchAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByLabel('批量研究标的',{exact:true}).fill('OTHER');assert.equal(await page.getByRole('button',{name:'预览整批发送内容',exact:true}).isEnabled(),false);assert.equal(await page.locator('.batch-detail:visible').getByRole('button',{name:'预览发送内容',exact:true}).isEnabled(),false);await page.getByText('标的或研究问题已改变，请重新准备材料后再预览或发送。原批次草稿仍保留。',{exact:true}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(researchAsk);await researchAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await researchAsk.getByText('请先按当前标的和问题准备批次材料，并等待批次操作完成。',{exact:true}).waitFor();await researchAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 await page.goto(base+'/portfolio');await page.getByLabel('搜索标的',{exact:true}).fill('FXTEST');await page.locator('.command-row').filter({hasText:'FXTEST'}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const portfolioAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(portfolioAsk);await portfolioAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await portfolioAsk.getByText('核对载入的材料',{exact:true}).waitFor();const portfolioMaterial=JSON.parse(await portfolioAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(portfolioMaterial.scope,'filtered_portfolio_positions');assert.equal(portfolioMaterial.positions.length,1);assert.equal(portfolioMaterial.positions[0].symbol,'FXTEST');assert.equal(portfolioMaterial.positions[0].currency,'HKD');assert.ok(!('trades' in portfolioMaterial));await portfolioAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(const symbol of ['PREVIEWA','PREVIEWB','PREVIEWC'])await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:aid,symbol,side:'buy',quantity:'1',price:'1',fee:'0',executed_at:new Date().toISOString()});
 await page.goto(base+'/cockpit');await page.locator('.position-row').first().waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(portfolioAsk);await portfolioAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await portfolioAsk.getByText('核对载入的材料',{exact:true}).waitFor();const cockpitMaterial=JSON.parse(await portfolioAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(cockpitMaterial.scope,'cockpit_display_snapshot');assert.equal(cockpitMaterial.positions_preview.length,4);assert.ok(!('accounts' in cockpitMaterial));assert.match(cockpitMaterial.notice,/仅前四项/);await portfolioAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByRole('button',{name:'隐藏金额',exact:true}).click();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();await openAskMaterials(portfolioAsk);await portfolioAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await portfolioAsk.getByText('金额处于隐藏状态；如需载入驾驶舱材料，请先主动显示金额。',{exact:true}).waitFor();await portfolioAsk.getByRole('button',{name:'关闭助手',exact:true}).click();
 for(let i=0;i<2;i++)await api('/api/v1/owner/documents','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'note',title:'Long synthetic note '+i,symbol:'TEST',content:'Synthetic evidence '.repeat(700),support:'',counter_case:'',invalidation:'',risk_limit:'',review_on:'',research_ref:null});await page.goto(base+'/research/notes');await page.getByLabel('搜索记录',{exact:true}).fill('Long synthetic note 0');await page.locator('.entry-card').filter({hasText:'Long synthetic note 0'}).waitFor();await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const filteredNotesAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(filteredNotesAsk);await filteredNotesAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await filteredNotesAsk.getByText('核对载入的材料',{exact:true}).waitFor();const noteMaterial=JSON.parse(await filteredNotesAsk.locator('.assistant-scroll > details pre').textContent()).material;assert.equal(noteMaterial.scope,'filtered_research_documents');assert.equal(noteMaterial.records.length,1);assert.equal(noteMaterial.records[0].title,'Long synthetic note 0');assert.ok(!('trades' in noteMaterial));await filteredNotesAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.getByLabel('搜索记录',{exact:true}).fill('');await page.getByRole('button',{name:'打开 Ask Awesome 助手',exact:true}).click();const longAsk=page.getByRole('dialog',{name:'Ask Awesome',exact:true});await openAskMaterials(longAsk);await longAsk.getByRole('button',{name:'载入当前页面材料',exact:true}).click();await longAsk.getByRole('heading',{name:'整理长材料',exact:true}).waitFor();assert.ok((await longAsk.getByLabel('原始页面材料',{exact:true}).inputValue()).length>20000);const excerpt='Synthetic selected excerpt <script>window.untrustedExcerpt=true</script>';await longAsk.getByLabel('选取的材料片段',{exact:true}).fill(excerpt);await longAsk.getByRole('button',{name:'采用选取片段',exact:true}).click();await longAsk.getByRole('heading',{name:'整理长材料',exact:true}).waitFor({state:'hidden'});const excerptMaterial=JSON.parse(await longAsk.locator('.assistant-scroll > details pre').textContent());assert.equal(excerptMaterial.material_excerpt,excerpt);assert.equal(excerptMaterial.page,'/research/notes');assert.equal(excerptMaterial.selection,'user_selected_excerpt_not_complete_source');await longAsk.locator('.chat-material > summary').click();assert.equal(JSON.parse(await longAsk.getByLabel('对话附加材料',{exact:true}).inputValue()).material_excerpt,excerpt);assert.equal(await page.evaluate(()=>window.untrustedExcerpt),undefined);for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/context-excerpt-${width}.png`,animations:'disabled'});}
 await longAsk.getByRole('button',{name:'关闭助手',exact:true}).click();await page.goto(base+'/research');await page.getByLabel('标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();const localAssistant=page.locator('main .assistant-workbench');await localAssistant.getByRole('button',{name:'整理超长材料片段',exact:true}).click();assert.ok((await localAssistant.getByLabel('完整来源材料',{exact:true}).inputValue()).length>20000);await localAssistant.getByLabel('整理后的片段',{exact:true}).fill('Selected synthetic research evidence');await localAssistant.getByRole('button',{name:'采用此材料片段',exact:true}).click();const selectedContext=JSON.parse(await localAssistant.getByLabel('待发送上下文',{exact:true}).inputValue());assert.equal(selectedContext.material_excerpt,'Selected synthetic research evidence');assert.equal(selectedContext.source_label,'TEST 研究材料');assert.equal(selectedContext.selection,'user_selected_excerpt_not_complete_source');
 const directionDate=new Date().toISOString().slice(0,10);await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'evidence',data:{symbol:'PREVIEWA',title:'Synthetic thesis counter evidence',metric:'other',value:'',source:'Synthetic source',as_of:directionDate,expires_on:directionDate,verification:'verified'}});
 await page.goto(base+'/research/screening');await page.setViewportSize({width:1440,height:1000});const directionalCard=page.locator('.evidence-card').filter({hasText:'Synthetic thesis counter evidence'});await directionalCard.getByRole('button',{name:'更正证据',exact:true}).click();const directionDialog=page.getByRole('dialog').filter({has:page.getByRole('button',{name:'保存记录',exact:true})});await directionDialog.locator('.el-form-item').filter({hasText:'对当前判断的影响（人工标记）'}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:'削弱判断',exact:true}).click();await directionDialog.getByRole('button',{name:'保存记录',exact:true}).click();await directionDialog.waitFor({state:'hidden'});await directionalCard.getByText('人工方向：削弱判断',{exact:true}).waitFor();
 await page.goto(base+'/research');await page.getByLabel('标的代码',{exact:true}).fill('PREVIEWA');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.getByText('最新证据正在削弱原判断，需要复核持仓逻辑',{exact:true}).waitFor();const directionalReport=await api('/api/v1/owner/research-report-preview','POST',{symbol:'PREVIEWA',lenses:['position','risk']});assert.equal(directionalReport.packet.rule_report.summary.posture,'thesis_review');assert.equal(directionalReport.packet.rule_report.evidence_balance.counter,1);
 assert.deepEqual(errors.filter(e=>!/409/.test(e)),[]);fs.writeFileSync(root+'/qa/vue-browser-results.json',JSON.stringify({passed:true,routes,visual,checks:['account valuation missing/current/stale','currency separated totals','account valuation three viewports','FIFO account created through UI','default launcher','all shipped routes','settings root no legacy','template download','preview does not write','stale preview blocked','explicit import','duplicate skipped','conflict blocked','actual JSON download','invalid encoding','1440/390/320'],errors:errors.filter(e=>!/409/.test(e))},null,2));console.log('Default Vue browser checks passed');
} catch(e) {
 fs.writeFileSync(root+'/qa/vue-browser-results.json',JSON.stringify({passed:false,error:String(e)}));
 const page=browser?.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:root+'/qa/vue-browser-failure.png'});console.error(await page.locator('body').innerText());}throw e;
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}

async function openAskMaterials(panel){const options=panel.locator('.page-material-options');if(!await options.evaluate(e=>e.open))await options.locator(':scope > summary').click()}
