// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const resultPath=root+'/qa/company-browser-results.json';
const server=spawn(process.env.OWNER_PYTHON || 'python3',['tests/owner/serve_market_fixture.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const callCount=()=>fs.existsSync(path.join(dir,'calls.json'))?JSON.parse(fs.readFileSync(path.join(dir,'calls.json'),'utf8')).length:0;
 await page.goto(base+'/settings/connections');await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).fill('synthetic-browser-key');await page.getByRole('button',{name:'启用行情连接',exact:true}).click();await page.getByLabel('美国市场标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'主动查询公司资料',exact:true}).click();const company=page.locator('main .company-evidence');await company.getByRole('heading',{name:'公司资料 · Synthetic Company',exact:true}).waitFor();assert.equal((await api('/api/v1/owner/company-source','POST',{symbol:'TEST'})).snapshot,null);assert.equal(await page.evaluate(()=>window.companyExecuted),undefined);await company.getByText('Synthetic <script>window.companyExecuted=true</script>',{exact:true}).waitFor();assert.equal(await company.locator('dt').filter({hasText:'季度营收同比 %'}).evaluate(e=>e.nextElementSibling.textContent),'-1.200');assert.equal(await company.locator('dt').filter({hasText:'P/E'}).evaluate(e=>e.nextElementSibling.textContent),'待补');await page.getByRole('button',{name:'确认保存公司资料',exact:true}).click();await page.getByText('公司资料来源快照已保存',{exact:true}).waitFor();const saved=(await api('/api/v1/owner/company-source','POST',{symbol:'TEST'})).snapshot;assert.equal(saved.verification,'supplier_unverified');
 await page.goto(base+'/research');await page.getByLabel('标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await company.getByRole('heading',{name:'公司资料 · Synthetic Company',exact:true}).waitFor();await page.locator('main .memory-evidence').getByText('来源分级分数：未评估 · 记录时效分数：未评估',{exact:true}).waitFor();await page.getByRole('button',{name:'预览报告 · 查看历史',exact:true}).click();const report=page.getByRole('dialog',{name:'固定研究报告',exact:true});await report.getByRole('button',{name:'第一步：预览当前报告',exact:true}).click();await report.locator('.company-evidence').getByRole('heading',{name:'公司资料 · Synthetic Company',exact:true}).waitFor();await report.getByRole('button',{name:'第二步：确认保存这份报告',exact:true}).click();await report.getByText('已保存固定报告',{exact:true}).waitFor();const reports=(await api('/api/v1/owner/research-reports')).reports;assert.equal(reports[0].packet.research_memory.event_count,0);assert.equal(reports[0].packet.research_memory.earnings_window.confirmed,false);assert.equal(reports[0].packet.research_memory.earnings_window.source_evidence.id,saved.id);await report.getByRole('heading',{name:'预计财报窗口 · 未经公司公告确认',exact:true}).waitFor();assert.equal(reports[0].packet.company_source.id,saved.id);assert.equal(reports[0].packet.company_source.company.pe,null);await report.getByRole('button',{name:'关闭固定报告',exact:true}).click();await report.waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>window.companyExecuted),undefined);await page.getByRole('button',{name:'载入本地研究材料',exact:true}).click();await page.locator('main .memory-evidence').getByText('来源分级分数：65 · 记录时效分数：100',{exact:true}).waitFor();assert.equal((await api('/api/v1/owner/research-reports')).reports[0].packet.research_memory.event_count,0);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await company.scrollIntoViewIfNeeded();await page.screenshot({path:root+`/qa/company-source-${width}.png`,animations:'disabled'});await page.locator('main .estimated-window').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(os.tmpdir(),`awesome-earnings-window-${width}.png`),animations:'disabled'})}
 const heldAccount=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:heldAccount,operation_id:crypto.randomUUID(),name:'Synthetic USD Portfolio',currency:'USD',opening_cash:'1000'});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,account_id:heldAccount,symbol:'TEST',side:'buy',quantity:'2',price:'10',fee:'1',executed_at:new Date().toISOString()});
 const portfolioSources=(await api('/api/v1/owner/business')).company_sources;assert.equal(portfolioSources['TEST|USD'].name,'Synthetic Company');await page.goto(base+'/portfolio');await page.getByText('Synthetic Company · 未核验',{exact:true}).waitFor();assert.match(await page.locator('.command-symbol-copy small').getAttribute('title'),/Alpha Vantage.*供应商资料未核验/);await page.getByLabel('搜索标的',{exact:true}).fill('Synthetic Company');assert.equal(await page.locator('.command-row').count(),1);await page.getByLabel('搜索标的',{exact:true}).clear();await page.locator('.overview-title').click();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);if(width===1440)assert.equal(await page.getByLabel('横向滚动持仓表',{exact:true}).evaluate(el=>el.scrollWidth>el.clientWidth),false);await page.screenshot({path:root+`/qa/p175-portfolio-company-${width}.png`,animations:'disabled'})}
 await page.locator('.command-row').first().click();const portfolioDrawer=page.locator('.position-drawer-panel');await portfolioDrawer.getByText('Synthetic Company · 未核验',{exact:true}).waitFor();assert.equal(await portfolioDrawer.locator('.position-drawer-metrics article').count(),4);await portfolioDrawer.getByText('收益率待补',{exact:true}).waitFor();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/p176-portfolio-drawer-${width}.png`,animations:'disabled'})}await page.getByRole('button',{name:'关闭持仓详情',exact:true}).click();
 assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'calls.json'))).length,1);assert.deepEqual(errors,[]);fs.writeFileSync(resultPath,JSON.stringify({passed:true,provider_calls:1,preview_writes:0,saved_snapshots:1,real_provider:false,research_company:true,frozen_source_binding:true,escaped_supplier_text:true,memory_refresh_and_fixed_history:true,portfolio_saved_company:true,portfolio_drawer_source:true}));console.log('Company source browser passed');
} catch(e) {fs.writeFileSync(resultPath,JSON.stringify({passed:false,error:String(e)}));const page=browser?.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:root+'/qa/company-failure.png'});console.error(await page.locator('body').innerText())}throw e;
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}
