// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const server=spawn(process.env.OWNER_PYTHON || 'python3',['start_owner.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const aid=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:aid,name:'Simulation USD',currency:'USD',opening_cash:'1000',operation_id:crypto.randomUUID()});await api('/api/v1/owner/accounts','POST',{id:crypto.randomUUID(),name:'Empty HKD',currency:'HKD',opening_cash:'500',operation_id:crypto.randomUUID()});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),account_id:aid,symbol:'TEST',side:'buy',quantity:'2',price:'10',fee:'0',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:'TEST',currency:'USD',price:'20',as_of:new Date().toISOString().slice(0,10),source:'Synthetic price for simulation'}});


 await page.goto(base+'/plan/allocation');
 const overview=page.getByRole('region',{name:'账户配置概览'});await overview.waitFor();
 await page.getByRole('combobox',{name:'资金账户'}).press('Enter');await page.getByRole('option',{name:'Simulation USD · USD'}).click();
 const overviewMetric=label=>overview.locator('.summary-card').filter({has:page.locator('.summary-label').getByText(label,{exact:true})}).locator('.summary-value');
 await overviewMetric('持仓市值').getByText('40.00',{exact:true}).waitFor();
 assert.equal(await overviewMetric('持仓成本').innerText(),'20.00');
 assert.equal(await overviewMetric('未实现收益率').innerText(),'100.00%');
 assert.equal(await overviewMetric('已配置').innerText(),'0.00%');
 assert.equal(await overviewMetric('未分配').innerText(),'3.92%');
 assert.equal(await page.getByRole('combobox',{name:'资金账户'}).count(),1);
 await page.getByRole('combobox',{name:'资金账户'}).press('Enter');await page.getByRole('option',{name:'Empty HKD · HKD'}).click();
 assert.equal(await overviewMetric('持仓成本').innerText(),'0.00');assert.match(await overview.innerText(),/HKD · 未平仓成本/);
 await page.getByRole('combobox',{name:'资金账户'}).press('Enter');await page.getByRole('option',{name:'Simulation USD · USD'}).click();
 assert.equal(await overviewMetric('持仓市值').innerText(),'40.00');
 const order=await page.evaluate(()=>['.allocation-overview','.layers-container','.input-card'].map(selector=>document.querySelector(selector)?.getBoundingClientRect().top));
 assert.ok(order[0]<order[1]&&order[1]<order[2],`allocation first-fold order: ${order}`);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/p162-allocation-overview-${width}.png`,animations:'disabled'});}
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'新建配置层',exact:true}).click();await page.getByLabel('配置层名称',{exact:true}).fill('核心层');await page.getByLabel('目标占比 %',{exact:true}).fill('60');await page.getByLabel('归属标的（逗号分隔）',{exact:true}).fill('TEST');await page.getByLabel('备选股票池（逗号分隔）',{exact:true}).fill('NEW');await page.getByRole('button',{name:'保存配置层',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});const card=page.locator('.layer-card').filter({hasText:'核心层'});await card.waitFor();assert.match(await card.innerText(),/核心层/);assert.match(await card.innerText(),/3.92%/);assert.match(await card.innerText(),/40.00/);assert.equal(await page.locator('.stack-layer').evaluate(e=>e.style.getPropertyValue('--actual-width')),'3.92%');assert.match(await page.locator('.layers-container').innerText(),/目标合计 60%，尚未达到100%，不视为完整配置/);assert.match(await page.locator('.stack-delta').innerText(),/低配 56\.08%/);
 assert.equal(await overviewMetric('已配置').innerText(),'3.92%');assert.equal(await overviewMetric('未分配').innerText(),'0.00%');
 await page.clock.setFixedTime(new Date(Date.now()+86400000));await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
 await overviewMetric('持仓市值').getByText('—',{exact:true}).waitFor();await card.getByText('实际 —（评估日已变化）',{exact:true}).waitFor();assert.equal(await page.locator('.stack-actual').count(),0);assert.equal(await page.locator('.allocation-comparison-card .actual-bar').count(),0);
 await page.clock.setFixedTime(new Date());await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await card.getByText('实际 3.92%',{exact:true}).waitFor();assert.equal(await page.locator('.allocation-comparison-card .actual-bar').count(),1);
 await page.getByText('已保存配置层',{exact:true}).click();await page.getByLabel('现金目标占比 %',{exact:true}).fill('40');await page.getByRole('button',{name:'计算影响',exact:true}).click();await page.getByRole('heading',{name:'试算结果 · USD',exact:true}).waitFor();assert.match(await page.locator('.results-section').innerText(),/572.00/);await page.getByRole('button',{name:'保存固定试算快照',exact:true}).click();await page.getByRole('button',{name:'快照已保存',exact:true}).waitFor();const scenario=(await api('/api/v1/owner/business')).records.find(r=>r.kind==='scenario');assert.equal(scenario.result.layer_evidence[0].revision,1);assert.equal(scenario.result.rows[0].adjustment_value,'572');for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.results-section').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/layer-allocation-result-${width}.png`,animations:'disabled'});}
 await card.getByRole('button',{name:'编辑层',exact:true}).click();await page.getByLabel('目标占比 %',{exact:true}).fill('100');await page.getByLabel('策略说明',{exact:true}).fill('Synthetic layer strategy');await page.getByRole('button',{name:'保存配置层',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByText('Synthetic layer strategy',{exact:true}).waitFor();await page.locator('.results-section').waitFor({state:'hidden'});const contribution=page.locator('.contribution-card').filter({hasText:'核心层'});assert.match(await contribution.innerText(),/100.00%/);assert.match(await contribution.innerText(),/未实现盈亏 20.00/);assert.equal((await api('/api/v1/owner/ledger')).accounts.find(a=>a.id===aid).trades.length,1);

 const core=(await api('/api/v1/owner/business')).records.find(r=>r.kind==='allocation_layer');const keys=['account_id','title','tier','sector','target_percent','target_amount','max_single_percent','strategy_note','symbols','stock_pool'];const layerData=Object.fromEntries(keys.map(k=>[k,core[k]]));await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),revision:0,operation_id:crypto.randomUUID(),kind:'allocation_layer',data:{...layerData,title:'防守层',target_percent:'0',symbols:[]}});await page.getByRole('button',{name:'刷新账本',exact:true}).click();await page.locator('.layer-card').filter({hasText:'防守层'}).waitFor();
 for(const title of ['防守层','核心层']){await page.getByRole('button',{name:'调整持仓归属',exact:true}).click();const dlg=page.getByRole('dialog',{name:'调整持仓归属',exact:true});await dlg.getByLabel('归属配置层',{exact:true}).press('Enter');await page.getByRole('option',{name:title,exact:true}).click();await dlg.getByRole('button',{name:'保存持仓归属',exact:true}).click();await dlg.waitFor({state:'hidden'});await page.locator('.layer-card').filter({hasText:title}).getByText('归属标的：TEST',{exact:false}).waitFor();}
 assert.equal((await api('/api/v1/owner/ledger')).accounts.find(a=>a.id===aid).trades.length,1);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.locator('.allocation-stack-card').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/p48-layers-${width}.png`,animations:'disabled'});}
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await contribution.scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+`/qa/layer-contribution-${width}.png`,animations:'disabled'});}
 const q=(await api('/api/v1/owner/business')).records.find(r=>r.kind==='quote');await api('/api/v1/owner/business','POST',{id:q.id,revision:q.revision,operation_id:crypto.randomUUID(),kind:'quote',data:{symbol:q.symbol,currency:q.currency,price:q.price,as_of:new Date(Date.now()-7*86400000).toISOString().slice(0,10),source:'Synthetic expired'}});await page.getByRole('button',{name:'刷新账本',exact:true}).click();await card.getByText('实际 —（缺少有效价格）',{exact:true}).waitFor();assert.equal(await page.locator('.stack-actual').count(),0);assert.equal(await page.locator('.allocation-comparison-card .actual-bar').count(),0);assert.match(await contribution.innerText(),/未实现盈亏 —/);assert.equal(await contribution.locator('.bar-fill').count(),0);assert.equal(await overviewMetric('持仓市值').innerText(),'—');assert.equal(await overviewMetric('持仓成本').innerText(),'20.00');assert.equal(await overviewMetric('未实现收益率').innerText(),'—');assert.equal(await overviewMetric('已配置').innerText(),'—');assert.equal(await overviewMetric('未分配').innerText(),'—');
 await card.getByRole('button',{name:'版本历史',exact:true}).click();await page.getByRole('heading',{name:'核心层 · v1',exact:false}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 await card.getByRole('button',{name:'归档层',exact:true}).click();await page.getByRole('button',{name:'归档',exact:true}).click();await card.waitFor({state:'hidden'});await page.getByRole('button',{name:'查看归档配置层',exact:true}).click();await page.getByRole('dialog').getByText('核心层',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 const activeLayer=page.locator('.layer-card').filter({hasText:'防守层'});await activeLayer.waitFor();
 await page.route('**/api/v1/owner/business',route=>route.request().method()==='GET'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic allocation read failure',code:'synthetic_read_failure'}})}):route.continue());
 await page.getByRole('button',{name:'刷新账本',exact:true}).click();await page.getByText('试算未完成',{exact:true}).waitFor();await page.locator('.layers-container').waitFor({state:'hidden'});await activeLayer.waitFor({state:'hidden'});assert.deepEqual(await page.locator('.allocation-overview .summary-value').allInnerTexts(),['—','—','—','—','—']);assert.equal(await page.getByRole('combobox',{name:'资金账户'}).count(),0);assert.equal(await page.getByRole('button',{name:'新建配置层',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('button',{name:'计算影响',exact:true}).isDisabled(),true);await page.getByText('账本读取失败，请刷新',{exact:true}).first().waitFor();
 await page.setViewportSize({width:390,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+'/qa/p180-allocation-read-failed-390.png',animations:'disabled'});
 await page.unroute('**/api/v1/owner/business');await page.getByRole('button',{name:'刷新账本',exact:true}).click();await activeLayer.waitFor();await page.getByText('试算未完成',{exact:true}).waitFor({state:'hidden'});await page.evaluate(()=>scrollTo(0,0));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:root+'/qa/p180-allocation-recovered-390.png',animations:'disabled'});
 await page.route('**/api/v1/owner/business',route=>route.request().method()==='GET'?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Synthetic layer read failure',code:'synthetic_layer_failure'}})}):route.continue());
 await page.getByRole('combobox',{name:'资金账户'}).press('Enter');await page.getByRole('option',{name:'Empty HKD · HKD'}).click();await page.locator('.layers-container .el-alert--error').waitFor();assert.equal(await page.locator('.layer-card').count(),0);
 await page.unroute('**/api/v1/owner/business');await page.getByRole('combobox',{name:'资金账户'}).press('Enter');await page.getByRole('option',{name:'Simulation USD · USD'}).click();await activeLayer.waitFor();await page.locator('.layers-container .el-alert--error').waitFor({state:'hidden'});
 assert.deepEqual(errors,[]);console.log('P180 allocation browser passed');fs.writeFileSync(root+'/qa/p180-allocation-results.json',JSON.stringify({passed:true,checks:['account-scoped overview and switch','layer creation and assigned ratio','cross-date valuation rejection','stale quote rejection','layer target calculation and fixed source','layer edit clears result','actual attributed valuation','incomplete target warning','edit preserves ledger','history','archive retained','failed parent read withdraws stale allocation','failed layer read withdraws prior layer data','successful retry clears errors','three viewports']}));
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}
