import {workspaceNav} from './browser_navigation.mjs';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import os from 'node:os';
import net from 'node:net';
import {spawn,spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const req=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE||path.join(root,'package.json'));
const {chromium}=req('playwright');
const python=(process.env.OWNER_PYTHON||'python3');
const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-owner-browser-')));fs.chmodSync(temp,0o700);
const data=path.join(temp,'data'),qa=path.join(root,'qa');fs.mkdirSync(qa,{recursive:true});
const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`,password='Synthetic-browser-only-2026',newPassword='Synthetic-browser-new-2026';
let child,browser;
async function start(directory){child=spawn(python,['tests/owner/business_browser_server.py','--port',String(port),'--data-dir',directory],{cwd:root,stdio:'ignore',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1',PYTHONPATH:'backend/src'}});for(let i=0;i<100;i++){if(child.exitCode!==null)throw Error('server exited');try{if((await fetch(base+'/api/v1/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,50));}throw Error('server did not start');}
async function stop(){if(child&&child.exitCode===null){const p=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await p;}child=null;}
async function message(page,part){await page.waitForFunction(p=>document.getElementById('message').textContent.includes(p),part);}
async function login(page,pwd=password){await page.locator('#auth').waitFor({state:'visible'});await page.locator('#username').fill('synthetic-owner');await page.locator('#password').fill(pwd);await page.locator('#auth-submit').click();await message(page,'已登录本地账本');}
async function ledger(page){return page.evaluate(async()=>(await fetch('/api/v1/owner/ledger')).json());}
async function saveTrade(page,side,quantity,price,when){await page.locator('#symbol').fill('TEST');await page.locator('#side').selectOption(side);await page.locator('#quantity').fill(quantity);await page.locator('#price').fill(price);await page.locator('#fee').fill('1');await page.locator('#executed-at').fill(when);await page.locator('#save-trade').click();await message(page,'交易已保存');}
async function idle(page){await page.waitForFunction(()=>!busy);}
async function nav(page,name){await idle(page);await workspaceNav(page,name);await idle(page);if(await page.locator('#'+name+'-panel').isHidden())throw Error('Navigation failed: '+name+' '+await page.locator('#message').textContent());}
async function object(page,kind,values){await page.locator('#business-'+kind+'-form').evaluate(f=>f.parentElement.open=true);for(const [k,v]of Object.entries(values)){const l=page.locator('#b-'+kind+'-'+k);if(await l.evaluate(x=>x.tagName)==='SELECT')await l.selectOption(v);else await l.fill(v);}await page.locator('#b-'+kind+'-save').click();await idle(page);}
try{
 await start(data);browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(['error','warning'].includes(m.type()))errors.push(m.text());});
 await page.goto(base+'/ledger');await page.locator('#auth').waitFor({state:'visible'});await page.locator('#username').fill('synthetic-owner');await page.locator('#password').fill(password);await page.locator('#confirm-password').fill(password);await page.locator('#auth-submit').click();await message(page,'已登录本地账本');await idle(page);
 await page.locator('#account-name').fill('业务闭环测试账户');await page.locator('#opening-cash').fill('1000');await page.locator('#account-form button').click();await idle(page);await saveTrade(page,'buy','10','10','2026-01-02T12:00');await idle(page);
 await nav(page,'cockpit');await page.locator('#save-baseline').click();await idle(page);assert.match(await page.locator('#business-changes').textContent(),/本次核账基线/);
 const today=new Date().toISOString().slice(0,10);
 await nav(page,'portfolio');await object(page,'quote',{symbol:'TEST',currency:'USD',price:'20',as_of:today,source:'虚构价格来源'});assert.match(await page.locator('#business-positions').textContent(),/1099/);assert.match(await page.locator('#positions').textContent(),/200 \/ 99/);
 await nav(page,'screening');assert.equal(await page.title(),'Research · 候选与证据 · Awesome Stock');
 for(const sy of ['TEST','DEMO'])await object(page,'candidate',{symbol:sy,title:sy+' 虚构公司',market:'US',thesis:'仅用于隔离测试 <img src=x onerror=alert(1)>',review_on:today});
 for(const [metric,value]of [['revenue_growth','20'],['gross_margin','40'],['net_debt_ebitda','1']])await object(page,'evidence',{symbol:'TEST',title:'虚构证据 '+metric,metric,value,source:'Synthetic document',as_of:today,expires_on:today,verification:'verified'});
 assert.match(await page.locator('#screen-results').textContent(),/满足输入阈值/);assert.equal(await page.locator('#screen-results img').count(),0);
 await page.locator('#screen-results input[type=checkbox]').nth(0).check();await page.locator('#screen-results input[type=checkbox]').nth(1).check();await page.locator('#compare-candidates').click();assert.match(await page.locator('#candidate-comparison').textContent(),/虚构证据/);await page.locator('#handoff-candidates').click();await idle(page);await nav(page,'research');assert.equal(await page.locator('#document-list article').count(),2);
 await nav(page,'cockpit');assert.equal(await page.locator('#business-inbox form').count(),2);const action=page.locator('#business-inbox form').first();await action.locator('select').selectOption('ignored');await action.locator('input[type=text]').fill('虚构误报测试');await action.locator('button').click();await idle(page);assert.match(await page.locator('#business-inbox').textContent(),/已忽略/);
 await nav(page,'planning');await page.locator('#planning-symbol').fill('TEST');await page.locator('#planning-price').fill('15');await page.locator('#planning-quantity').fill('2');await page.locator('#planning-fee').fill('1');await page.locator('#planning-max').fill('100');const before=await ledger(page);await page.locator('#planning-form button').click();await idle(page);assert.match(await page.locator('#planning-result').textContent(),/868/);assert.deepEqual(await ledger(page),before);await page.locator('#save-scenario').click();await idle(page);assert.match(await page.locator('#business-scenarios').textContent(),/我的试算/);
 await page.locator('#planning-type').selectOption('allocation');await page.locator('#planning-targets').fill('TEST=50\n@CASH=50');await page.locator('#planning-form button').click();await idle(page);assert.match(await page.locator('#planning-result').textContent(),/349.5/);
 await page.locator('#planning-type').selectOption('build_up');await page.locator('#planning-budget').fill('100');await page.locator('#planning-price').fill('20');await page.locator('#planning-form button').click();await idle(page);assert.match(await page.locator('#planning-result').textContent(),/817/);
 await nav(page,'trends');await object(page,'rule',{title:'虚构仓位检查',condition:'每次试算前',action:'核对价格日期',scope:'个人账户'});assert.match(await page.locator('#business-rules').textContent(),/关闭/);await page.locator('#business-rules details').first().evaluate(d=>d.open=true);await page.getByRole('button',{name:'我确认启用',exact:true}).click();await idle(page);assert.match(await page.locator('#business-rules').textContent(),/启用/);assert.match(await page.locator('#trend-results').textContent(),/共 0 条复盘/);
 await nav(page,'settings');await page.locator('#settings-tab-connections').click();assert.match(await page.locator('#connection-ai-form').locator('..').textContent(),/Community不提供统一密钥、不代付/);assert.equal(await page.locator('#connection-data-key').locator('..').textContent(),'你自己的 Alpha Vantage API Key');await page.locator('#connection-ai-model').fill('demo@awesome.local');await page.locator('#connection-ai-key').fill('synthetic-invalid-only');await page.locator('#connection-ai-form button').first().click();await idle(page);assert.match(await page.locator('#message').textContent(),/不是登录账号或邮箱/);await page.locator('#connection-ai-provider').selectOption('ollama');assert.equal(await page.locator('#connection-ai-key').isVisible(),false);assert.match(await page.locator('#connection-ai-help').textContent(),/使用者自行安装/);await page.locator('#connection-ai-form').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(qa,'configuration-desktop.png')});await page.setViewportSize({width:390,height:844});await page.locator('#connection-ai-form').scrollIntoViewIfNeeded();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(qa,'configuration-mobile.png')});await page.setViewportSize({width:1440,height:960});await page.locator('#connection-ai-provider').selectOption('openai');assert.equal(await page.locator('#connection-ai-key').inputValue(),'');await page.locator('#connection-ai-model').fill('synthetic-model');await page.locator('#connection-ai-key').fill('synthetic-key-not-real');await page.locator('#connection-ai-form button').first().click();await idle(page);assert.equal(await page.locator('#connection-ai-key').inputValue(),'');
 await page.locator('#connection-data-key').fill('synthetic-data-key');await page.locator('#connection-data-form button').first().click();await idle(page);await page.locator('#fetch-symbol').fill('TEST');await page.locator('#quote-fetch-form button').click();await idle(page);await page.locator('#confirm-fetched-quote').click();await idle(page);assert.match(await page.locator('#fetch-result').textContent(),/已保存/);
 await page.locator('#ask-ai').click();await page.locator('#ai-question').fill('解释这段虚构资料');await page.locator('#ai-context').fill('TEST虚构持仓10股，仅测试');await page.locator('#ai-form button').click();await idle(page);assert.match(await page.locator('#ai-result').textContent(),/将发送到云端/);await page.locator('#ai-confirm-send').click();await idle(page);assert.match(await page.locator('#ai-result').textContent(),/离线浏览器测试替身/);assert.deepEqual(await ledger(page),before);await page.locator('#close-ai').click();
 const exported=await page.evaluate(async()=>await(await fetch('/api/v1/owner/export')).json());assert.equal(JSON.stringify(exported).includes('synthetic-key'),false);assert.ok(exported.documents.some(d=>d.kind==='scenario'));
 await nav(page,'screening');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(qa,'business-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(qa,'business-mobile.png'),fullPage:true});await page.setViewportSize({width:1440,height:960});
 await page.locator('#backup').click();await idle(page);const backupName=fs.readdirSync(path.join(data,'backups'))[0];await stop();await start(data);await page.reload();await login(page);await idle(page);assert.equal(await page.locator('#screen-results input[type=checkbox]').count(),2);const c=await page.evaluate(async()=>await(await fetch('/api/v1/owner/connections')).json());assert.equal(c.ai.enabled,false);assert.deepEqual(await ledger(page),before);
 await nav(page,'settings');await page.locator('#settings-tab-privacy').click();await page.locator('#preview-reset').click();await idle(page);await page.locator('#reset-password').fill(password);await page.locator('#reset-confirmation').fill('清空当前业务数据');await page.locator('#reset-business-form button').click();await page.waitForURL(base+'/settings');await page.locator('#auth').waitFor({state:'visible'});await login(page);await idle(page);assert.deepEqual((await ledger(page)).accounts,[]);await page.locator('#settings-tab-privacy').click();await page.locator('#list-backups').click();await idle(page);assert.match(await page.locator('#privacy-backups').textContent(),/backup-/);
 await stop();const restored=path.join(temp,'restored');const restore=spawnSync(python,['start_owner.py','--restore-from',path.join(data,'backups',backupName),'--data-dir',restored],{cwd:root,encoding:'utf8',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});assert.equal(restore.status,0,restore.stderr);await start(restored);await page.reload();await login(page);await idle(page);assert.deepEqual(await ledger(page),before);await nav(page,'planning');assert.match(await page.locator('#business-scenarios').textContent(),/我的试算/);
 assert.deepEqual(errors,[]);const summary={passed:true,consoleErrors:0,mobileOverflow:false,providerValidation:'explicit offline transport fixture, not real provider acceptance',checks:['baseline','price valuation and holdings details','two candidates and three verified metrics','threshold filtering','safe rendering','batch comparison and frozen note handoff','action feedback','three planning tools no ledger writes','scenario saved','rule starts disabled then manual enable','empty trend honest','memory-only connection config','quote preview confirmation','AI exact preview and manual send','JSON excludes keys','desktop and mobile','restart disables connections','logical reset retains login and backups','restore business snapshot']};fs.writeFileSync(path.join(qa,'business-browser-result.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary));
}finally{await browser?.close();await stop();fs.rmSync(temp,{recursive:true,force:true});}
