// Default shipped Vue runtime; all records and downloads are isolated synthetic fixtures.
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import net from 'node:net';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {setTimeout as delay} from 'node:timers/promises';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');const output=fs.mkdtempSync(path.join(os.tmpdir(),'awesome-diagnosis-portfolio-'));console.log('Portfolio diagnosis evidence: '+output);
const {chromium}=createRequire(process.env.OWNER_PLAYWRIGHT_PACKAGE || path.join(root,'package.json'))('playwright');
const dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'awesome-vue-browser-')));
fs.chmodSync(dir,0o700);
fs.mkdirSync(path.join(root,'qa'),{recursive:true});
const port=await new Promise(resolve=>{const socket=net.createServer();socket.listen(0,'127.0.0.1',()=>{const p=socket.address().port;socket.close(()=>resolve(p));});});
const base=`http://127.0.0.1:${port}`;
const resultPath=path.join(output,'result.json');
const server=spawn(process.env.OWNER_PYTHON || 'python3',['tests/owner/serve_market_fixture.py','--port',String(port),'--data-dir',path.join(dir,'data')],{cwd:root,stdio:['ignore','ignore','pipe'],env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serverErrors || 'server exited');try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/422|503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('portfolio-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-Portfolio-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(JSON.stringify(d));return d},{path,method,body});

 const aid=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:aid,operation_id:crypto.randomUUID(),name:'Synthetic sources',currency:'USD',opening_cash:'1000'});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,account_id:aid,symbol:'TEST',side:'buy',quantity:'2',price:'10',fee:'0',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol:'TEST',currency:'USD',price:'20',as_of:new Date().toISOString().slice(0,10),source:'Synthetic quote'}});
 await page.goto(base+'/settings/connections');await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'行情来源',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:'自有 API · Alpha Vantage / EODHD',exact:true}).click();await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).fill('Synthetic-source-key');await page.getByRole('button',{name:'启用行情连接',exact:true}).click();await page.getByLabel('美国市场标的代码',{exact:true}).fill('TEST');await page.getByRole('button',{name:'主动查询公司资料',exact:true}).click();await page.getByRole('button',{name:'确认保存公司资料',exact:true}).click();await delay(1100);await page.getByRole('button',{name:'主动查询相关新闻',exact:true}).click();await page.getByRole('button',{name:'确认保存新闻来源',exact:true}).click();await page.getByText('新闻来源快照已保存',{exact:true}).waitFor();
 const hkd=crypto.randomUUID();await api('/api/v1/owner/accounts','POST',{id:hkd,operation_id:crypto.randomUUID(),name:'Synthetic HKD',currency:'HKD',opening_cash:'1000'});await api('/api/v1/owner/trades','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,account_id:hkd,symbol:'TEST',side:'buy',quantity:'2',price:'10',fee:'0',executed_at:new Date().toISOString()});await api('/api/v1/owner/business','POST',{id:crypto.randomUUID(),operation_id:crypto.randomUUID(),revision:0,kind:'quote',data:{symbol:'TEST',currency:'HKD',price:'20',as_of:new Date().toISOString().slice(0,10),source:'Synthetic HKD quote'}});
 await page.goto(base+'/review/diagnosis');
 const selectScope=async label=>{await page.getByRole('button',{name:'刷新账本与历史',exact:true}).and(page.locator(':enabled')).waitFor();await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'诊断账户',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:label,exact:true}).click()};
 await selectScope('全部账户组合 · USD');await page.getByLabel('HKD:TEST 公司归属',{exact:true}).waitFor();await page.getByRole('button',{name:'运行诊断预览',exact:true}).click();await page.getByText('持仓价格或折算汇率缺失或过期',{exact:true}).waitFor();
 const today=new Date().toISOString().slice(0,10);await api('/api/v1/owner/fx-rates','POST',{operation_id:crypto.randomUUID(),revision:0,currency:'HKD',rate:'0.125',as_of:today,expires_on:today,source:'Synthetic FX'});
 await page.getByRole('button',{name:'刷新账本与历史',exact:true}).click();await page.getByRole('button',{name:'放弃',exact:true}).click();await page.getByRole('button',{name:'核对 USD:TEST 已保存来源',exact:true}).click();await page.getByRole('button',{name:'核对后采用 USD:TEST 来源',exact:true}).click();await page.getByLabel('HKD:TEST 公司归属',{exact:true}).fill('Synthetic HKD Company');await page.getByLabel('HKD:TEST 资料来源',{exact:true}).fill('Synthetic manual observation');
 await page.locator('.el-select').filter({has:page.getByRole('combobox',{name:'HKD:TEST 新闻观察',exact:true})}).locator('.el-select__wrapper').click();await page.getByRole('option',{name:'中性观察',exact:true}).click();
 await page.getByRole('button',{name:'运行诊断预览',exact:true}).click();await page.getByRole('button',{name:'生成并保存事实日报',exact:true}).click();await page.locator('.daily-entry').waitFor();
 let history=await api('/api/v1/owner/diagnosis-history','POST',{account_id:'portfolio:all'});assert.equal(history.reports[0].report.status,'complete');assert.equal(Number(history.reports[0].report.total_value),45);assert.equal(history.reports[0].report.position_count,2);assert.equal(history.reports[0].report.holding_context['USD:TEST'].source_evidence.verification,'supplier_unverified');const first=JSON.stringify(history.reports[0]);
 await page.getByRole('button',{name:'运行诊断预览',exact:true}).click();await page.getByRole('button',{name:'生成并保存事实日报',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.daily-entry').length===2);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:path.join(output,`diagnosis-portfolio-${width}.png`),animations:'disabled'})}
 await page.setViewportSize({width:1440,height:1000});assert.equal(await page.locator('.snapshot-point').count(),2);await page.locator('.snapshot-point').first().focus();await page.keyboard.press('Enter');await page.waitForURL(/id=/);await page.locator('.linked-daily').waitFor();await page.waitForFunction(()=>document.querySelectorAll('.diagnosis-page').length===1);await page.getByRole('button',{name:'刷新账本与历史',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.diagnosis-page .el-select__input')?.disabled);assert.equal(await page.getByRole('combobox',{name:'诊断账户',exact:true}).getAttribute('aria-expanded'),'false');
 await api('/api/v1/owner/fx-rates','POST',{operation_id:crypto.randomUUID(),revision:1,currency:'HKD',rate:'0.25',as_of:today,expires_on:today,source:'Synthetic revised FX'});history=await api('/api/v1/owner/diagnosis-history','POST',{account_id:'portfolio:all'});assert.ok(history.reports.some(r=>JSON.stringify(r)===first));assert.equal((await api('/api/v1/owner/diagnosis-history','POST',{account_id:aid})).reports.length,0);
 await selectScope('Synthetic sources · USD');await page.getByLabel('TEST 公司归属',{exact:true}).waitFor();assert.equal(await page.locator('.daily-entry').count(),0);
 await page.goto(base+'/portfolio');await page.getByRole('button',{name:/展开图表/}).click();const portfolioHistory=page.locator('#portfolio-distribution');await portfolioHistory.getByText('持仓市值快照趋势',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelectorAll('#portfolio-distribution .snapshot-point').length===2);assert.match(await portfolioHistory.innerText(),/不是剔除出入金后的投资回报率/);
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await portfolioHistory.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,`portfolio-history-${width}.png`),animations:'disabled'})}
 await page.route('**/api/v1/owner/daily-history',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Synthetic history unavailable'})}));await page.getByRole('button',{name:/收起图表/}).click();await page.getByRole('button',{name:/展开图表/}).click();await portfolioHistory.getByText('固定快照暂未读取',{exact:true}).waitFor();assert.equal(await portfolioHistory.locator('.snapshot-point').count(),0);await page.unroute('**/api/v1/owner/daily-history');await portfolioHistory.getByRole('button',{name:'重试',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('#portfolio-distribution .snapshot-point').length===2);
 await portfolioHistory.locator('.snapshot-point').first().focus();await page.keyboard.press('Enter');await page.waitForURL(/id=/);await page.locator('.linked-daily').waitFor();

 assert.deepEqual(errors,[]);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'calls.json'))).length,2);fs.writeFileSync(resultPath,JSON.stringify({passed:true,widths:[1440,390,320],missing_fx_unavailable:true,currency_groups_distinct:true,fixed_daily_total_usd:45,supplier_adoption_usd_only:true,historical_fx_immutable:true,snapshot_navigation:true,portfolio_history_visible:true,portfolio_history_failure_clears:true,portfolio_history_navigation:true,single_account_isolation:true,provider_calls:2,errors,real_provider:false}));console.log('Portfolio diagnosis browser passed');
} catch(e) {fs.writeFileSync(resultPath,JSON.stringify({passed:false,error:String(e)}));const page=browser?.contexts()[0]?.pages()[0];if(page){await page.screenshot({path:path.join(output,'failure.png')});console.error(await page.locator('body').innerText())}throw e;
} finally {
 if(browser)await browser.close();
 if(server.exitCode===null){const stopped=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGTERM');await stopped;}
 fs.rmSync(dir,{recursive:true,force:true});
}
