import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import net from 'node:net';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=process.env.OWNER_QA_DIR||path.join(os.tmpdir(),'as-yahoo-deferred-qa'),{chromium}=createRequire(root+'/package.json')('playwright'),dir=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'as-yahoo-deferred-')));
fs.mkdirSync(out,{recursive:true});
const port=await new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p))})});const base=`http://127.0.0.1:${port}`,server=spawn('python3',['tests/owner/serve_market_fixture.py','--port',String(port),'--data-dir',dir+'/data'],{cwd:root,stdio:['ignore','ignore','pipe']});let browser,serr='';server.stderr.on('data',d=>serr+=d);const calls=()=>fs.existsSync(dir+'/calls.json')?JSON.parse(fs.readFileSync(dir+'/calls.json')):[];
try {
 for(let i=0;i<100;i++){if(server.exitCode!==null)throw Error(serr);try{if((await fetch(base+'/api/v1/owner/status')).ok)break}catch{}await delay(100)}
 browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!/503/.test(m.text()))errors.push(m.text())});
 await page.goto(base+'/login');await page.getByLabel('用户名',{exact:true}).fill('withdrawal-check');await page.getByLabel('口令',{exact:true}).fill('Synthetic-withdrawal-2026');await page.getByLabel('确认口令',{exact:true}).fill('Synthetic-withdrawal-2026');await page.getByRole('button',{name:'创建账号',exact:true}).click();await page.getByRole('heading',{name:'账户管理'}).waitFor();await page.goto(base+'/settings/connections');
 const api=async(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const csrf=decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('__Host-awesome_owner_csrf=')).split('=').slice(1).join('='));const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'X-Requested-With':'awesome-owner'},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()}},{path,method,body});
 const market=page.locator('.market-panel');await market.getByText('关闭 · 尚未验证真实调用',{exact:true}).first().waitFor();
 assert.ok(page.url().endsWith('/settings/connections'));assert.ok((await page.title()).includes('Awesome Stock'));await page.getByRole('heading',{name:'个人连接设置',exact:true}).waitFor();
 assert.equal(await page.locator('vite-error-overlay').count(),0);assert.equal(await page.getByRole('combobox',{name:'行情来源',exact:true}).count(),0);
 await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).waitFor();await page.getByText(/本次首发暂不提供 Yahoo 免 Key 接口/).waitFor();assert.equal(calls().length,0);
 const before=(await api('/api/v1/owner/business')).body;
 for(const endpoint of ['quote-fetch-public','market-history-fetch-public']){const r=await api('/api/v1/owner/'+endpoint,'POST',{symbol:'AAPL',market:'US'});assert.equal(r.status,503);assert.equal(r.body.error.code,'public_market_deferred')}
 assert.deepEqual((await api('/api/v1/owner/business')).body,before);assert.equal(calls().length,0);
 await page.getByRole('button',{name:'前往持仓录入价格',exact:true}).click();await page.waitForURL(base+'/portfolio');await page.getByRole('button',{name:'管理持仓',exact:true}).click();await page.getByText('记录价格快照',{exact:true}).click();await page.getByRole('dialog',{name:'记录价格快照',exact:true}).waitFor();
 await page.goto(base+'/settings/connections');await page.getByRole('button',{name:'导入 CSV',exact:true}).click();await page.waitForURL(base+'/settings/transfer');await page.getByRole('heading',{name:'导入与导出',exact:true}).waitFor();assert.equal(calls().length,0);
 await page.goto(base+'/settings/connections');await page.getByLabel('你自己的 Alpha Vantage API Key',{exact:true}).fill('Synthetic-browser-key');await page.getByRole('button',{name:'启用行情连接',exact:true}).click();await market.getByText('alphavantage / 日级价格 · 尚未验证真实调用',{exact:true}).waitFor();assert.equal(calls().length,0);
 await page.getByLabel('美国市场标的代码',{exact:true}).fill('AAPL');await page.getByRole('button',{name:'主动查询日级价格',exact:true}).click();await page.getByRole('heading',{name:'AAPL · USD 20',exact:true}).waitFor();assert.equal(calls().length,1);assert.equal(calls()[0].host,'www.alphavantage.co');assert.deepEqual((await api('/api/v1/owner/business')).body,before);
 await page.getByRole('button',{name:'确认保存价格快照',exact:true}).click();await page.getByText('价格快照已保存',{exact:true}).last().waitFor();assert.notDeepEqual((await api('/api/v1/owner/business')).body,before);assert.equal(calls().length,1);
 await delay(3500);for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await market.locator('.panel-title').scrollIntoViewIfNeeded();await delay(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:out+`/deferred-${width}.png`})}
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'/result.json',JSON.stringify({passed:true,url:base+'/settings/connections',viewports:[1440,768,390,320],browser_plugin:'not available',provider_calls:1,real_provider:false,checks:['page identity','meaningful page','no framework overlay','console health','four screenshots','default own API and no Yahoo option','legacy endpoints reject with zero calls/writes','manual price entry and CSV navigation','explicit API configure/query/preview/save'],errors},null,2));console.log('Deferred Yahoo boundary and own API browser passed');
} catch(e){fs.writeFileSync(out+'/failure.json',JSON.stringify({passed:false,error:String(e)}));const page=browser?.contexts()[0]?.pages()[0];if(page)await page.screenshot({path:out+'/failure.png'});throw e;
} finally {if(browser)await browser.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}fs.rmSync(dir,{recursive:true,force:true})}
