'use strict';
let evolveData=null,reviewEdit=null,reviewBasis=null,reviewDirty=false;
const processLabels={followed:'遵守原计划',deviated:'偏离原计划',unclear:'尚不能判断'};
function selectedReviewCandidate(){return evolveData?.candidates.find(c=>referenceValue(c.ref)===$('review-decision').value);}
function lockReviewControls(){$('review-decision').disabled=!!reviewEdit;$('refresh-review-basis').disabled=!!reviewEdit;}
function resetReview(){reviewEdit=null;reviewBasis=null;reviewDirty=false;pending.delete('review');pending.delete('review-id');$('review-form').reset();$('review-date').value=localTime().slice(0,10);$('review-heading').textContent='新建复盘';$('review-version').textContent='尚未保存';$('review-outcome-note').required=false;lockReviewControls();if(evolveData){chooseReviewBasis();}}
function chooseReviewBasis(){const c=selectedReviewCandidate();reviewBasis=c?{snapshot:c.snapshot,fingerprint:c.fingerprint,ref:c.ref}:null;renderReviewBasis();}
function renderEvidence(target,snapshot){
 target.replaceChildren();if(!snapshot){target.append(element('p','尚无Decision依据。先在Plan中保存投资判断，再进入复盘。'));return;}
 const d=snapshot.decision;target.append(element('h3',`${d.title} · ${d.symbol} · v${d.revision}`));
 const details=element('details');details.append(element('summary','原判断与研究依据'));
 for(const [key,label] of [['content','行动原因'],['support','支持证据'],['counter_case','反方证据'],['invalidation','失效条件'],['risk_limit','风险上限'],['review_on','原定复核日期']]){details.append(element('h4',label),element('p',d[key]));}
 if(snapshot.research){details.append(element('h4',`研究：${snapshot.research.title} · v${snapshot.research.revision}`),element('p',snapshot.research.content));}else details.append(element('p','原Decision未引用研究笔记。'));
 target.append(details);target.append(element('p',`该Decision版本引用的成交：${snapshot.trades.length} 笔。这里只呈现成交事实，不计算决策收益率。`));
 if(snapshot.trades.length){const wrap=element('div');wrap.className='table-wrap';wrap.append(table(['账户','币种','成交时间','方向','数量','单价','费用','成交版本'],snapshot.trades.map(t=>[t.account_name,t.currency,new Date(t.executed_at).toLocaleString(),t.side==='buy'?'买入':'卖出',t.quantity,t.price,t.fee,`v${t.revision}`])));target.append(wrap);}else target.append(element('p','尚无引用成交。可以复核未执行的判断，不将其记为亏损或违规。'));
}
function renderReviewBasis(){renderEvidence($('review-basis'),reviewBasis?.snapshot);const current=evolveData?.candidates.find(c=>referenceValue(c.ref)===referenceValue(reviewBasis?.ref));const changed=current&&current.fingerprint!==reviewBasis?.fingerprint;$('review-basis-status').textContent=reviewEdit?(changed?'保存后的成交或引用已有变化。此复盘保留原快照；如需使用新依据，请新建复盘。':'保存时的固定快照；修订复盘文字不会改变依据。'):(changed?'当前成交或引用已变化。核对后点击“更新未保存依据”，再保存。':'保存前将核对当前引用是否变化，保存后固定该快照。');}
function showReviewHistory(r){const target=$('review-history');target.replaceChildren();target.append(element('h3',`${r.title} · 复盘v${r.revision}${r.archived?' · 已归档':''}`));for(const [label,value] of [['复盘日期',r.reviewed_on],['过程判断（人工）',processLabels[r.process_status]],['过程复核',r.process_note],['结果状态',r.outcome_status==='pending'?'待观察':'已有观察'],['结果备注',r.outcome_note||'未填写'],['下次改进',r.next_step]])target.append(element('h4',label),element('p',value));const box=element('div');renderEvidence(box,r.evidence);target.append(box);$('review-dialog').showModal();}
function editReview(r){if(busy)return;if(reviewDirty&&!confirm('放弃未保存复盘并载入此记录？'))return;resetReview();reviewEdit=r;reviewBasis={snapshot:r.evidence,fingerprint:r.evidence_fingerprint,ref:r.decision_ref};$('review-decision').value=referenceValue(r.decision_ref);$('review-date').value=r.reviewed_on;$('review-process').value=r.process_status;$('review-process-note').value=r.process_note;$('review-outcome').value=r.outcome_status;$('review-outcome-note').value=r.outcome_note;$('review-outcome-note').required=r.outcome_status==='observed';$('review-next').value=r.next_step;$('review-heading').textContent='编辑复盘：'+r.title;$('review-version').textContent=`当前版本 ${r.revision}；保存后保留旧版本。`;lockReviewControls();renderReviewBasis();$('review-process-note').focus();}
function renderReviewList(){const target=$('review-list');target.replaceChildren();const rows=evolveData.reviews.filter(r=>$('review-filter').value==='all'||!r.archived);if(!rows.length)target.append(element('p','暂无复盘。选择一个Decision版本开始。'));for(const r of rows){const card=element('article');card.className='document-card';card.append(element('h3',r.title),element('p',`${r.symbol} · ${r.reviewed_on} · v${r.revision}${r.archived?' · 已归档':''}`),element('p',`${processLabels[r.process_status]} / ${r.outcome_status==='pending'?'待观察':'已有观察'}`));if(r.evidence_changed)card.append(element('p','当前成交/引用已有变化；历史依据已保留。'));if(!r.archived){const actions=element('div');actions.className='row';const edit=element('button','编辑');edit.className='secondary';edit.onclick=()=>editReview(r);const archive=element('button','归档');archive.className='secondary';archive.onclick=()=>{if(busy||!confirm('归档这条复盘？历史版本和依据将保留。'))return;run(async()=>{await request('/api/v1/owner/evolve','DELETE',operation('review-archive-'+r.id,{id:r.id,revision:r.revision}));if(reviewEdit?.id===r.id)resetReview();await loadEvolve();message('复盘已归档，历史依据保留。');});};actions.append(edit,archive);card.append(actions);}const history=element('details');history.append(element('summary','历史复盘'));for(const v of evolveData.versions.filter(v=>v.id===r.id).reverse()){const b=element('button',`查看 v${v.revision}${v.archived?' · 归档':''}`);b.className='secondary history-button';b.onclick=()=>showReviewHistory(v);history.append(b);}card.append(history);target.append(card);}}
async function loadEvolve(){evolveData=await request('/api/v1/owner/evolve');const selected=referenceValue(reviewBasis?.ref)||$('review-decision').value;$('review-decision').replaceChildren();for(const c of evolveData.candidates){const o=element('option',`${c.snapshot.decision.title} · ${c.snapshot.decision.symbol} · v${c.ref.revision}${c.decision_archived?'（历史Decision）':''}`);o.value=referenceValue(c.ref);$('review-decision').append(o);}if([...$('review-decision').options].some(o=>o.value===selected))$('review-decision').value=selected;if(!reviewBasis)chooseReviewBasis();renderReviewList();renderReviewBasis();lockReviewControls();}
$('new-review').onclick=()=>{if(!reviewDirty||confirm('清空未保存的复盘并新建？'))resetReview();};
$('review-form').oninput=()=>{reviewDirty=true;};$('review-form').onchange=()=>{reviewDirty=true;};
$('review-decision').onchange=chooseReviewBasis;
$('review-filter').onchange=renderReviewList;
$('review-outcome').onchange=()=>{$('review-outcome-note').required=$('review-outcome').value==='observed';};
$('refresh-review-basis').onclick=()=>{if(!reviewEdit&&confirm('使用当前成交/引用更新依据？已输入的复盘文字保留，请重新核对。')){chooseReviewBasis();pending.delete('review');}};
$('close-review').onclick=()=>$('review-dialog').close();
$('review-form').onsubmit=e=>{e.preventDefault();run(async()=>{if(!reviewBasis)throw Error('请先保存Decision。');let id=reviewEdit?.id||pending.get('review-id');if(!id){id=crypto.randomUUID();pending.set('review-id',id);}const values={id,revision:reviewEdit?.revision||0,decision_ref:reviewBasis.ref,expected_evidence:reviewBasis.fingerprint,reviewed_on:$('review-date').value,process_status:$('review-process').value,process_note:$('review-process-note').value,outcome_status:$('review-outcome').value,outcome_note:$('review-outcome-note').value,next_step:$('review-next').value};reviewEdit=await request('/api/v1/owner/evolve','POST',operation('review',values));reviewDirty=false;pending.delete('review-id');pending.delete('review');$('review-heading').textContent='编辑复盘：'+reviewEdit.title;$('review-version').textContent=`已保存版本 ${reviewEdit.revision}；依据快照固定。`;await loadEvolve();message('复盘已保存，过程和结果分别记录。');});};
function clearEvolve(){evolveData=null;resetReview();$('review-list').replaceChildren();$('review-history').replaceChildren();$('review-basis').replaceChildren();}
window.addEventListener('DOMContentLoaded',()=>{if(!$('review-date').value)$('review-date').value=localTime().slice(0,10);});
window.addEventListener('beforeunload',e=>{if(reviewDirty){e.preventDefault();e.returnValue='';}});
