'use strict';
let planData=null,planEdit=null,planDirty=false;
const planLabels={draft:'草稿',ready:'待执行',paused:'暂停',completed:'手工标记完成'};
const planTypes={build_up:'分批建仓',rebalance:'调整仓位',reduce:'减仓退出'};
const planFields=['title','plan_type','status','trigger','risk_limit','stop_condition','review_on'];
function lockPlanControls(){$('plan-decision').disabled=!!planEdit;}
function resetPlan(){planEdit=null;planDirty=false;pending.delete('plan');pending.delete('plan-id');$('plan-form').reset();$('plan-heading').textContent='新建计划';$('plan-version').textContent='尚未保存';lockPlanControls();renderPlanBasis();}
function renderPlanBasis(){const target=$('plan-basis');target.replaceChildren();const d=planEdit?.evidence.decision||planData?.decisions.find(d=>referenceValue(d)===$('plan-decision').value);if(!d){target.append(element('p','请先在Decision中保存投资判断。'));return;}target.append(element('h3',`${d.title} · ${d.symbol} · v${d.revision}`),element('p',d.content));const detail=element('details');detail.append(element('summary','支持/反方证据与失效条件'));for(const [key,label] of [['support','支持证据'],['counter_case','反方证据'],['invalidation','失效条件'],['risk_limit','原风险上限']])detail.append(element('h4',label),element('p',d[key]));if(planEdit?.evidence.research){const n=planEdit.evidence.research;detail.append(element('h4',`研究依据：${n.title} · v${n.revision}`),element('p',n.content));}target.append(detail,element('p','保存后引用固定；如需改用另一版本判断，请新建计划。'));}
function editPlan(p){if(busy)return;if(planDirty&&!confirm('放弃未保存内容并载入此计划？'))return;resetPlan();planEdit=p;for(const key of planFields)$('plan-'+key).value=p[key];$('plan-steps').value=p.steps.join('\n');fillPlanDecisions();$('plan-decision').value=referenceValue(p.decision_ref);$('plan-heading').textContent='编辑计划：'+p.title;$('plan-version').textContent=`当前版本 ${p.revision}；历史依据固定。`;lockPlanControls();renderPlanBasis();$('plan-title').focus();}
function showPlanHistory(p){const target=$('plan-history');target.replaceChildren();target.append(element('h3',`${p.title} · v${p.revision}${p.archived?' · 已归档':''}`));for(const [label,value] of [['类型',planTypes[p.plan_type]],['状态（人工）',planLabels[p.status]],['触发条件',p.trigger],['执行步骤',p.steps.join('\n')],['风险上限',p.risk_limit],['停止条件',p.stop_condition],['复核日期',p.review_on],['固定Decision',`${p.evidence.decision.title} · v${p.decision_ref.revision}`],['原判断',p.evidence.decision.content]])target.append(element('h4',label),element('p',value));if(p.evidence.research)target.append(element('h4',`原研究：${p.evidence.research.title} · v${p.evidence.research.revision}`),element('p',p.evidence.research.content));$('plan-dialog').showModal();}
function fillPlanDecisions(){const selected=planEdit?referenceValue(planEdit.decision_ref):$('plan-decision').value;$('plan-decision').replaceChildren();const options=[...planData.decisions];if(planEdit&&!options.some(d=>referenceValue(d)===selected))options.push(planEdit.evidence.decision);for(const d of options){const o=element('option',`${d.title} · ${d.symbol} · v${d.revision}`);o.value=referenceValue(d);$('plan-decision').append(o);}if([...$('plan-decision').options].some(o=>o.value===selected))$('plan-decision').value=selected;}
function renderPlanList(){const target=$('plan-list');target.replaceChildren();const rows=planData.plans.filter(p=>$('plan-filter').value==='all'||!p.archived);if(!rows.length)target.append(element('p','暂无计划。先选择Decision，再填写计划步骤。'));for(const p of rows){const card=element('article');card.className='document-card';card.append(element('h3',p.title),element('p',`${p.symbol} · ${planTypes[p.plan_type]} · ${planLabels[p.status]} · v${p.revision}${p.archived?' · 已归档':''}`));if(p.decision_changed)card.append(element('p','Decision已有新版本或已归档；此计划保留原依据。'));if(!p.archived){const actions=element('div');actions.className='row';const edit=element('button','编辑');edit.className='secondary';edit.onclick=()=>editPlan(p);const archive=element('button','归档');archive.className='secondary';archive.onclick=()=>{if(busy||!confirm('归档计划？未保存编辑不写入，历史版本保留。'))return;run(async()=>{await request('/api/v1/owner/plans','DELETE',operation('archive-plan-'+p.id,{id:p.id,revision:p.revision}));if(planEdit?.id===p.id)resetPlan();await loadPlans();message('计划已归档，历史版本保留。');});};actions.append(edit,archive);card.append(actions);}const history=element('details');history.append(element('summary','历史计划'));for(const v of planData.versions.filter(v=>v.id===p.id).reverse()){const b=element('button',`查看 v${v.revision}`);b.className='secondary history-button';b.onclick=()=>showPlanHistory(v);history.append(b);}card.append(history);target.append(card);}}
async function loadPlans(){planData=await request('/api/v1/owner/plans');fillPlanDecisions();renderPlanList();renderPlanBasis();lockPlanControls();}
$('plan-form').oninput=()=>{planDirty=true;};$('plan-form').onchange=()=>{planDirty=true;};$('plan-decision').onchange=renderPlanBasis;$('plan-filter').onchange=renderPlanList;
$('new-plan').onclick=()=>{if(!planDirty||confirm('清空未保存内容并新建计划？'))resetPlan();};$('close-plan').onclick=()=>$('plan-dialog').close();
$('plan-form').onsubmit=e=>{e.preventDefault();run(async()=>{let id=planEdit?.id||pending.get('plan-id');if(!id){id=crypto.randomUUID();pending.set('plan-id',id);}const body={id,revision:planEdit?.revision||0,decision_ref:parseReference($('plan-decision').value),steps:$('plan-steps').value.split('\n').map(s=>s.trim()).filter(Boolean)};for(const key of planFields)body[key]=$('plan-'+key).value;planEdit=await request('/api/v1/owner/plans','POST',operation('plan',body));planDirty=false;pending.delete('plan');pending.delete('plan-id');$('plan-heading').textContent='编辑计划：'+planEdit.title;$('plan-version').textContent=`已保存版本 ${planEdit.revision}；未创建交易。`;await loadPlans();message('计划已保存，未创建交易或订单。');});};
function clearPlans(){planData=null;resetPlan();$('plan-list').replaceChildren();$('plan-history').replaceChildren();}
window.addEventListener('beforeunload',e=>{if(planDirty){e.preventDefault();e.returnValue='';}});
