<template><el-dialog append-to-body :model-value="true" title="成交决策资格" width="min(640px,96vw)" :close-on-click-modal="false" :close-on-press-escape="false" :before-close="close" :show-close="!busy"><el-alert v-if="error" type="error" :title="error" :closable="false"/><template v-if="data"><p>{{ data.trade.symbol }} · {{ data.trade.account_id }} · 成交 v{{ data.trade.revision }}</p><p>当前资格：{{ labels[data.qualification] }}</p><el-alert v-if="data.context_stale" title="成交已更正，请核对新事实后重新保存资格。" type="warning" :closable="false"/><p v-if="data.decision_link">已有明确决策关联。取消重要标记不会移除关联，也不会把它改成普通成交。</p><el-checkbox v-model="required" :disabled="busy">此成交需要决策依据</el-checkbox><el-form label-position="top"><el-form-item label="成交决策理由"><el-input v-model="reason" type="textarea" :rows="4" maxlength="4000" :disabled="busy"/></el-form-item></el-form><p>普通成交不强制填写理由。保存只记录复核资格，不改变成交、提交订单或生成评分。</p><el-button :disabled="busy" @click="save">保存成交资格</el-button><h4>资格历史版本</h4><p v-if="!data.versions.length">尚无标记记录。</p><article v-for="v in data.versions" :key="v.revision" class="context-version"><strong>v{{ v.revision }} · {{ v.decision_required?'需要决策依据':'普通成交标记' }}</strong><p>对应成交 v{{ v.trade_revision }} · {{ new Date(v.updated_at).toLocaleString('zh-CN') }}</p><p>{{ v.reason||'未记录理由' }}</p></article></template><template #footer><el-button :disabled="busy" @click="close">关闭成交资格</el-button></template></el-dialog></template>
<script setup lang="ts">
import {ref,onBeforeUnmount} from 'vue'
import {ElCheckbox,ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
type Version={revision:number;trade_revision:number;decision_required:boolean;reason:string;updated_at:string}
type Data={trade:{id:string;revision:number;symbol:string;account_id:string};context:Version|null;context_stale:boolean;qualification:string;decision_link:unknown;versions:Version[]}
const props=defineProps<{tradeId:string}>(),emit=defineEmits<{close:[]}>(),data=ref<Data|null>(null),required=ref(false),reason=ref(''),busy=ref(false),error=ref(''),ops=operationCache();let baseline='',alive=true
const labels:Record<string,string>={ordinary:'普通成交（不评分）',linked_decision:'已关联决策',required_without_context:'需要决策依据，尚未关联',needs_reconfirmation:'成交变化，待重新确认'},fingerprint=()=>JSON.stringify([required.value,reason.value])
async function load(){busy.value=true;try{const result=await request<Data>('/api/v1/owner/trade-context-history','POST',{trade_id:props.tradeId});if(!alive)return;data.value=result;required.value=result.context?.decision_required??false;reason.value=result.context?.reason||'';baseline=fingerprint()}catch(e){error.value=e instanceof Error?e.message:'读取失败'}finally{busy.value=false}}
async function save(){if(busy.value||!data.value)return;busy.value=true;error.value='';try{await request('/api/v1/owner/trade-context','POST',ops.body('trade-context',{trade_id:props.tradeId,trade_revision:data.value.trade.revision,revision:data.value.context?.revision||0,decision_required:required.value,reason:reason.value}));await load();ops.clear()}catch(e){error.value=e instanceof Error?e.message:'保存失败，编辑已保留'}finally{busy.value=false}}
async function close(){if(busy.value)return false;if(fingerprint()!==baseline){try{await ElMessageBox.confirm('放弃未保存的成交资格和理由？','关闭成交资格',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'})}catch{return false}}emit('close');return true}
const unload=(e:BeforeUnloadEvent)=>{if(busy.value||fingerprint()!==baseline){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',unload)});defineExpose({close});baseline=fingerprint();load()
</script>
<style scoped>p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}.context-version{padding:12px 0;border-top:1px solid var(--el-border-color)}</style>
