"""Owner-written investment journal. Draft text is never generated by a provider."""
from datetime import date, datetime, timedelta, timezone
import json
import re

from .local import Conflict, _canonical
from .owner import identifier, text
from .owner_business import symbol


def workspace(store):
    with store.connection() as db:
        db.execute('BEGIN')
        entries = [json.loads(row[0]) for row in db.execute('SELECT payload FROM documents')]
        entries = sorted((row for row in entries if row['kind'] == 'journal' and not row['archived']),
                         key=lambda row: (row['entry_date'], row['updated_at'], row['id']), reverse=True)
        cutoff = datetime.now(timezone.utc) - timedelta(days=7)
        trades = []
        for payload, account in db.execute('SELECT t.payload,a.name FROM trades t JOIN accounts a ON a.id=t.account_id'):
            trade = json.loads(payload)
            try:
                when = datetime.fromisoformat(trade['executed_at'].replace('Z', '+00:00'))
                if when.tzinfo is None:when = when.replace(tzinfo=timezone.utc)
            except (ValueError, KeyError, AttributeError):
                continue
            if when >= cutoff:
                trades.append({key: trade.get(key) for key in ('id', 'symbol', 'side', 'quantity', 'price', 'reason', 'executed_at')} | {'account_name': account})
        trades.sort(key=lambda row: (row['executed_at'], row['id']), reverse=True)
        return {'entries': entries, 'recent_trades': trades[:12], 'window_days': 7, 'manual_only': True}


def save(store, body, *, archive=False):
    common = {'id', 'revision', 'operation_id'}
    fields = {'title', 'content', 'entry_date', 'mood', 'tickers', 'tags'}
    if not isinstance(body, dict) or set(body) != (common if archive else common | fields):raise ValueError('invalid journal fields')
    identifier(body['id']);store._revision(body['revision'])
    if not archive:
        day = body['entry_date']
        if not isinstance(day, str) or not re.fullmatch(r'\d{4}-\d{2}-\d{2}', day):raise ValueError('invalid entry date')
        date.fromisoformat(day)
        if body['mood'] not in {'bullish', 'bearish', 'neutral'}:raise ValueError('invalid mood')
        if not isinstance(body['tickers'], list) or len(body['tickers']) > 30:raise ValueError('invalid tickers')
        tickers = [symbol(value) for value in body['tickers']]
        if len(set(tickers)) != len(tickers):raise ValueError('duplicate ticker')
        if not isinstance(body['tags'], list) or len(body['tags']) > 20:raise ValueError('invalid tags')
        tags = [text(value, 40) for value in body['tags']]
        if len(set(tags)) != len(tags):raise ValueError('duplicate tag')
        payload = {'title': text(body['title'], 120), 'content': text(body['content'], 20000),
                   'entry_date': day, 'mood': body['mood'], 'tickers': tickers, 'tags': tags}
    with store.transaction() as db:
        fingerprint, old = store._operation(db, body, 'journal_archive' if archive else 'journal_save')
        if old is not None:return old
        row = db.execute('SELECT payload,revision FROM documents WHERE id=?', (body['id'],)).fetchone()
        current = json.loads(row[0]) if row else None
        if (row[1] if row else 0) != body['revision'] or (archive and not row):raise Conflict('journal changed')
        if current and (current['kind'] != 'journal' or current['archived']):raise Conflict('journal unavailable')
        result = ({**current, 'archived': True} if archive else {**payload, 'id': body['id'], 'kind': 'journal', 'archived': False})
        result['revision'] = body['revision'] + 1
        result['updated_at'] = datetime.now(timezone.utc).isoformat()
        encoded = _canonical(result)
        db.execute('INSERT INTO documents VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,revision=excluded.revision', (body['id'], encoded, result['revision']))
        db.execute('INSERT INTO document_versions VALUES (?,?,?)', (body['id'], result['revision'], encoded))
        store._audit(db, 'journal_archived' if archive else 'journal_saved', body['id'], current, result)
        return store._result(db, body, fingerprint, result)
