<template><section class="coach-period"><h3>决策教练周期报告</h3><p>按 UTC 成交日期统计，同一成交取最新教练报告。缺资料及依据已变化的记录不进入完整评分；普通成交不评分。</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="教练统计开始日期"><el-input v-model="start" type="date" :disabled="busy"/></el-form-item><el-form-item label="教练统计结束日期"><el-input v-model="end" type="date" :disabled="busy"/></el-form-item></el-form><el-button :disabled="busy" @click="run">预览教练周期报告</el-button><el-button v-if="preview" :disabled="busy" @click="save">保存固定周期报告</el-button><el-button :disabled="busy" @click="refresh">刷新周期历史</el-button>
<template v-if="report"><p>{{ report.start }} — {{ report.end }} · {{ preview?'未保存预览':'固定历史' }}</p><div class="period-metrics"><article><span>过程规则均分</span><b>{{ report.summary.process_score??'—' }}</b></article><article><span>完整评分样本</span><b>{{ report.summary.scored_count }} / {{ report.summary.unique_trade_count }}</b></article><article><span>依据已变化</span><b>{{ report.summary.stale_count }}</b></article><article><span>资料不完整</span><b>{{ report.summary.incomplete_count }}</b></article></div><p>普通成交 {{ report.ordinary_trade_count }} 笔；已关联但未生成教练报告 {{ report.linked_without_report_count }} 笔；重要未关联且未生成报告 {{ report.important_without_report_count??0 }} 笔。方向性结果分不代表实际收益；两类分数分别统计有效样本，不以缺失补零。</p><div class="period-outcomes"><h4>方向性价格结果均分：{{ report.summary.outcome_score??'待验证' }}</h4><p>有效结果 {{ report.summary.outcome_scored_count??'未记录' }} / {{ report.summary.unique_trade_count }} · 依据变化 {{ report.summary.outcome_stale_count??'未记录' }} · 待验证 {{ report.summary.outcome_pending_count??'未记录' }}</p><p>每笔成交等权，报价观察日期可不同。旧报告没有这些统计时不补造历史。</p></div><h4>月度过程与结果趋势</h4><p v-if="!report.months.length">本期没有教练样本，不填充满分或零分。</p><div class="period-months"><article v-for="month in report.months" :key="month.month"><strong>{{ month.month }}</strong><p>过程 {{ month.process_score??'资料不足' }}</p><div class="trend-bar"><i v-if="month.process_score!==null" :style="{width:Number(month.process_score)+'%'}"/></div><p>结果 {{ month.outcome_score??'待验证' }} · 有效 {{ month.outcome_scored_count??'未记录' }}</p><div class="trend-bar outcome-bar"><i v-if="month.outcome_score!=null" :style="{width:Number(month.outcome_score)+'%'}"/></div><p>完整 {{ month.scored_count }} / {{ month.unique_trade_count }} · 已复核 {{ month.reviewed_count }}</p></article></div><h4>已知行为模式</h4><p v-if="!Object.keys(report.summary.patterns).length">完整样本未命中模式，不能据此推断全部决策正确。</p><p v-for="(count,code) in report.summary.patterns" :key="code">{{ labels[code]||code }}：{{ count }} 次</p><section v-if="report.conclusions" class="period-conclusions"><p>{{ report.conclusions.scope }}</p><h4>过程优势</h4><p v-if="!report.conclusions.strengths.length">没有足够完整样本，不生成优势结论。</p><article v-for="item in report.conclusions.strengths" :key="item.text"><p>{{ item.text }}</p><details><summary>查看结论依据</summary><pre>{{ JSON.stringify(item.basis,null,2) }}</pre></details></article><h4>行为风险</h4><p v-if="!report.conclusions.risks.length">完整样本未命中列出的模式，不等于没有风险。</p><article v-for="item in report.conclusions.risks" :key="item.text"><p>{{ item.text }}</p><details><summary>查看结论依据</summary><pre>{{ JSON.stringify(item.basis,null,2) }}</pre></details></article><h4>下次复核动作</h4><p v-for="action in report.conclusions.next_actions" :key="action">{{ action }}</p></section><details><summary>查看周期固定样本</summary><pre>{{ JSON.stringify(report.entries,null,2) }}</pre></details></template>
<h4>固定周期历史</h4><p v-if="!history.length">尚无固定周期报告。</p><div class="period-history"><el-button v-for="r in history" :key="r.id" :data-report-id="r.id" :class="{'is-selected':selected?.id===r.id&&!preview}" :aria-pressed="selected?.id===r.id&&!preview" :disabled="busy||!!preview" @click="selected=r">{{ r.title }} · {{ new Date(r.updated_at).toLocaleString('zh-CN') }}</el-button></div></section></template>
<script setup lang="ts">
import {ref,computed,watch,onBeforeUnmount} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate} from 'vue-router'
import {ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
type Summary={outcome_score?:string|null;outcome_scored_count?:number;outcome_stale_count?:number;outcome_pending_count?:number;process_score:string|null;scored_count:number;unique_trade_count:number;stale_count:number;incomplete_count:number;reviewed_count:number;patterns:Record<string,number>}
type Report={important_without_report_count?:number;conclusions?:{scope:string;strengths:{text:string;basis:unknown}[];risks:{text:string;basis:unknown}[];next_actions:string[]};start:string;end:string;summary:Summary;ordinary_trade_count:number;linked_without_report_count:number;months:(Summary&{month:string})[];entries:unknown[]}
type Saved={id:string;title:string;updated_at:string;report:Report}
const today=new Date().toISOString().slice(0,10),start=ref(today.slice(0,8)+'01'),end=ref(today),busy=ref(false),error=ref(''),history=ref<Saved[]>([]),selected=ref<Saved|null>(null),preview=ref<{report:Report;token:string}|null>(null),ops=operationCache();let id='',baseline=start.value+'|'+end.value,alive=true
const report=computed(()=>preview.value?.report||selected.value?.report),labels:Record<string,string>={overtrading:'交易频率',rapid_reversal:'短期方向反转',chasing:'买价上涨后加仓',averaged_down_unreviewed:'降价加仓缺更新理由',missing_reason:'缺少决策依据'}
watch([start,end],()=>{preview.value=null;ops.clear();id=''})
async function load(preferredId?:string){
 const activeId=preferredId??selected.value?.id;busy.value=true;error.value=''
 try{const h=await request<{reports:Saved[]}>('/api/v1/owner/coach-period');if(!alive)return false;history.value=h.reports;selected.value=h.reports.find(r=>r.id===activeId)||h.reports[0]||null;preview.value=null;baseline=start.value+'|'+end.value;return true}
 catch(e){if(alive){history.value=[];selected.value=null;preview.value=null;ops.clear();error.value=e instanceof Error?e.message:'周期历史读取失败'}return false}
 finally{busy.value=false}
}
async function leave(){if(busy.value)return false;if(!preview.value&&baseline===start.value+'|'+end.value)return true;try{await ElMessageBox.confirm('放弃未保存的周期范围与预览？','离开周期报告',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'});return true}catch{return false}}
async function refresh(){if(await leave())await load()}
async function run(){if(busy.value)return;busy.value=true;error.value='';preview.value=null;try{preview.value=await request('/api/v1/owner/coach-period-preview','POST',{start:start.value,end:end.value});id=crypto.randomUUID();ops.clear()}catch(e){error.value=e instanceof Error?e.message:'统计失败'}finally{busy.value=false}}
async function save(){if(busy.value||!preview.value)return;busy.value=true;error.value='';try{await request('/api/v1/owner/coach-period','POST',ops.body('period',{id,input:{start:start.value,end:end.value},expected_token:preview.value.token}));preview.value=null;ops.clear();if(!await load(id))error.value='周期报告已保存，但固定历史读取失败。请刷新历史确认，避免重复保存。'}catch(e){error.value=e instanceof Error?e.message:'保存失败，预览保留'}finally{busy.value=false}}
onBeforeRouteLeave(leave);onBeforeRouteUpdate(leave);const unload=(e:BeforeUnloadEvent)=>{if(busy.value||preview.value||baseline!==start.value+'|'+end.value){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',unload)});load()
defineExpose({getMaterial:()=>{if(busy.value||!report.value)throw Error('请先完成预览或选择历史报告');return {state:preview.value?'unsaved_preview':'fixed_report',record_id:preview.value?null:selected.value?.id,report:report.value}}})
</script>
<style scoped>.coach-period{padding:20px;margin:20px 0;border:1px solid rgba(99,164,218,.2);border-radius:16px;background:rgba(2,13,30,.28);min-width:0}.period-metrics,.period-months{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin:18px 0}.period-metrics article,.period-months article{min-width:0;padding:12px;border:1px solid rgba(99,164,218,.2);border-radius:10px}.period-metrics b{display:block;font-size:22px;margin-top:8px}.trend-bar{height:4px;background:rgba(255,255,255,.06)}.trend-bar i{display:block;height:100%;background:linear-gradient(90deg,#4b75ff,#49d4ff)}.outcome-bar i{background:linear-gradient(90deg,#a78bfa,#efb4ff)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.period-history{display:grid;gap:8px;margin-top:10px}.period-history .el-button{margin:0;justify-content:flex-start;text-align:left;padding:11px 12px;overflow-wrap:anywhere}.period-history .is-selected{border-color:rgba(73,190,255,.58);background:rgba(73,190,255,.09);color:#dceaff}.el-button{white-space:normal;height:auto;min-height:32px;margin:5px 5px 5px 0}@media(max-width:480px){.period-metrics,.period-months{grid-template-columns:1fr}}</style>
