<template><el-button class="constitution-trigger" :disabled="busy||disabled" @click="opened=true">我的投资纪律</el-button><el-dialog v-model="opened" append-to-body title="我的投资纪律" width="min(620px,96vw)" :close-on-click-modal="false" :close-on-press-escape="false" :show-close="!busy" :before-close="close"><section class="constitution-panel"><p>保存当前诊断阈值和自定义规则为全局版本，再主动选用于本次诊断。旧报告和定时配置保留原版本。</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-checkbox v-model="required" :disabled="busy||disabled">重要成交需要决策理由</el-checkbox><p>普通成交不强制填写。明确标记的重要成交未关联决策时，教练按所选纪律检查理由；此设置不阻止记录成交。</p><el-form label-position="top"><el-form-item label="禁止动作记录（每行一项）"><el-input v-model="prohibited" type="textarea" :rows="3" :disabled="busy||disabled"/></el-form-item></el-form><p>禁止动作仅作文字记录，不会自动阻止成交或执行交易。</p><el-button :disabled="busy||disabled" @click="save">将当前阈值保存为全局纪律</el-button><p v-if="!versions.length">尚无全局纪律版本。</p><article v-for="v in versions" :key="v.revision"><strong>纪律 v{{ v.revision }} · {{ new Date(v.updated_at).toLocaleString('zh-CN') }}</strong><el-button :disabled="busy||disabled" @click="emit('use',v)">选用纪律 v{{ v.revision }}</el-button><details><summary>查看此版纪律</summary><pre>{{ JSON.stringify(v.config,null,2) }}</pre></details></article></section><template #footer><el-button :disabled="busy" @click="close">关闭投资纪律</el-button></template></el-dialog></template>
<script setup lang="ts">
import {ref,onBeforeUnmount} from 'vue'
import {ElCheckbox,ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
type Policy={warning_percent:string;max_percent:string;shock_percent:string;custom_rules:{name:string;metric:string;operator:string;threshold:string;severity:string}[]}
type Version={revision:number;updated_at:string;config:{policy:Policy;require_reason_before_trade:boolean;prohibited_actions:string[]}}
const opened=ref(false)
const props=defineProps<{policy:Policy;disabled:boolean}>(),emit=defineEmits<{use:[Version]}>(),busy=ref(false),error=ref(''),required=ref(true),prohibited=ref(''),versions=ref<Version[]>([]),ops=operationCache();let revision=0,baseline='',alive=true
const fingerprint=()=>JSON.stringify([required.value,prohibited.value])
async function load(){busy.value=true;try{const h=await request<{versions:Version[];current:Version|null}>('/api/v1/owner/constitution');if(!alive)return;versions.value=h.versions;revision=h.current?.revision||0;required.value=h.current?.config.require_reason_before_trade??true;prohibited.value=h.current?.config.prohibited_actions.join('\n')||'';baseline=fingerprint()}catch(e){error.value=e instanceof Error?e.message:'读取失败'}finally{busy.value=false}}
async function save(){if(busy.value||props.disabled)return;busy.value=true;error.value='';try{await request('/api/v1/owner/constitution','POST',ops.body('constitution',{revision,config:{policy:JSON.parse(JSON.stringify(props.policy)),require_reason_before_trade:required.value,prohibited_actions:prohibited.value.split('\n').map(x=>x.trim()).filter(Boolean)}}));await load();ops.clear()}catch(e){error.value=e instanceof Error?e.message:'保存失败，编辑已保留'}finally{busy.value=false}}
async function leave(){if(busy.value)return false;if(fingerprint()===baseline){opened.value=false;return true;}try{await ElMessageBox.confirm('放弃未保存的纪律说明？','离开纪律设置',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'});required.value=versions.value[0]?.config.require_reason_before_trade??true;prohibited.value=versions.value[0]?.config.prohibited_actions.join('\n')||'';baseline=fingerprint();opened.value=false;return true}catch{return false}}
async function close(){await leave()}
const unload=(e:BeforeUnloadEvent)=>{if(busy.value||fingerprint()!==baseline){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',unload)});defineExpose({leave});baseline=fingerprint();load()
</script>
<style scoped>.constitution-trigger{margin-bottom:16px}.constitution-panel{min-width:0}.constitution-panel p{line-height:1.7;overflow-wrap:anywhere}article{padding:12px 0;border-top:1px solid var(--el-border-color)}pre{white-space:pre-wrap;overflow-wrap:anywhere}.el-button{white-space:normal;height:auto;margin:8px 0;min-height:32px}</style>
