<template>
<section class="decision-coach"><header class="coach-header"><div><span class="coach-kicker">DECISION COACH</span><h3>决策教练</h3><p>复核已关联决策或明确标记的重要成交，普通成交不自动评分。</p></div><el-button :disabled="busy" @click="refresh">刷新教练依据</el-button></header><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<div class="coach-scoreboard" aria-label="教练报告概览"><article><span>过程可评分</span><b>{{ report?processCount+' / '+report.checks.length:'—' }}</b><small>所选报告保存时的完整样本</small></article><article><span>结果可验证</span><b>{{ report?outcomeCount+' / '+report.checks.length:'—' }}</b><small>有成交后同币种报价的样本</small></article><article><span>固定报告</span><b>{{ records.length }}</b><small>每份报告保留原依据</small></article><article><span>人工已复核</span><b>{{ reviewedCount }}</b><small>已复核或存入教练日记</small></article></div>
<p v-if="!candidates.length&&!importantTrades.length&&!busy">先保存投资判断，再选择需要复核的版本。没有成交的判断保留为未执行。</p>
<el-form label-position="top"><el-form-item label="教练决策版本"><el-select v-model="choice" :disabled="busy" style="width:100%"><el-option v-for="c in candidates" :key="key(c.ref)" :value="key(c.ref)" :label="c.snapshot.decision.title+' · '+c.snapshot.decision.symbol+' · v'+c.ref.revision"/><el-option v-for="t in importantTrades" :key="t.id" :value="'trade:'+t.id" :label="'重要成交 · '+t.symbol+' · '+new Date(t.executed_at).toLocaleString('zh-CN')"/></el-select></el-form-item><el-form-item v-if="choice.startsWith('trade:')" label="教练采用的纪律版本"><el-select v-model="constitutionRevision" :disabled="busy"><el-option v-for="c in constitutions" :key="c.revision" :value="c.revision" :label="'纪律 v'+c.revision"/></el-select><p v-if="!constitutions.length">先在组合诊断页保存全局纪律，再刷新教练依据。</p></el-form-item><el-checkbox v-model="complete" :disabled="busy">我确认该账户同标的历史成交已完整录入</el-checkbox></el-form><p>未确认完整性时只展示已知模式，不输出完整过程分。分数是规则提示，不代表投资质量或收益。</p><el-button :disabled="busy||!choice" @click="run">预览教练报告</el-button><el-button v-if="preview" :disabled="busy" @click="save">保存固定教练报告</el-button>
<template v-if="report"><p class="coach-report-state">{{ preview?'未保存预览':'固定历史' }} · {{ states[report.status] }} · 关联成交 {{ report.checks.length }} 笔</p><div class="review-list"><article v-for="check in report.checks" :key="check.trade_id" class="review-row"><span class="review-score">{{ check.process_score??'—' }}</span><div class="review-main"><b>过程规则分</b><p v-for="p in check.patterns" :key="p.code">{{ labels[p.code] }} · 扣 {{ p.penalty }} 分</p><p v-if="!check.patterns.length">已知事实未命中上述模式，不代表决策已获人工认可。</p></div></article></div><div v-for="check in report.checks" :key="'outcome-'+check.trade_id" class="outcome-evidence"><h4>方向性价格结果分：{{ check.outcome?.outcome_score??'待验证' }}</h4><p>与过程分独立；按买入后上涨、卖出后下跌的方向计算，不是实际收益。未计数量、费用、分红或汇率。</p><p v-if="check.outcome?.status==='complete'">方向性价格变化 {{ check.outcome.outcome_return_pct }}%</p><p v-else>{{ outcomeReasons[check.outcome?.reason||'']||'旧报告未包含结果依据。' }}</p><details v-if="check.outcome"><summary>查看固定结果价格依据</summary><pre>{{ JSON.stringify(check.outcome,null,2) }}</pre></details></div><details v-if="report.evidence.qualification"><summary>查看重要成交资格与纪律依据</summary><pre>{{ JSON.stringify({qualification:report.evidence.qualification,constitution:report.evidence.constitution},null,2) }}</pre></details><ReviewEvidence :snapshot="report.evidence.decision_evidence"/><details><summary>查看固定历史成交依据</summary><pre>{{ JSON.stringify(report.evidence.history,null,2) }}</pre></details></template>
<h4>固定教练历史</h4><p v-if="!records.length">尚无固定教练报告。</p><div class="coach-history-list"><article v-for="r in records" :key="r.id" class="coach-history" :data-report-id="r.id" :class="{'is-selected':selected?.id===r.id&&!preview}"><div class="coach-history-head"><el-button :disabled="busy||!!preview" :aria-pressed="selected?.id===r.id&&!preview" @click="selected=r">{{ r.title }} · {{ new Date(r.updated_at).toLocaleString('zh-CN') }}</el-button><span>{{ r.annotation?reviewStates[r.annotation.status]:'待人工复核' }}</span></div><p v-if="r.evidence_changed">当前过程依据已变化，此报告保留原事实。</p><p v-if="r.outcome_evidence_changed">结果价格或核对日期已变化，保存的结果仍保留原时点。</p><div class="coach-history-actions"><el-button :disabled="busy||!!preview" @click="editReview(r)">编辑教练复核</el-button></div><details v-if="r.annotation_versions.length" class="annotation-history"><summary>查看人工复核版本（{{ r.annotation_versions.length }}）</summary><details v-for="version in r.annotation_versions" :key="version.revision" class="annotation-version"><summary>v{{ version.revision }} · {{ reviewStates[version.status] }} · {{ new Date(version.updated_at).toLocaleString('zh-CN') }} · {{ version.title }}</summary><p class="annotation-text">{{ version.content }}</p><p v-if="version.status==='journaled'">此版本已固定存入教练日记，后续修改不会覆盖它。</p></details></details></article></div>
<el-dialog :model-value="!!reviewTarget" title="编辑教练复核" width="min(680px,96vw)" :close-on-click-modal="false" :close-on-press-escape="true" :show-close="!busy" :before-close="closeReview"><el-alert v-if="error" :title="error" type="error" :closable="false"/><p>这里保存你的复核意见，原规则报告与事实保持不变。存入日记会固定本次文本及依据。</p><el-form label-position="top"><el-form-item label="教练复核标题"><el-input v-model="reviewForm.title" :disabled="busy" maxlength="120"/></el-form-item><el-form-item label="教练复核内容"><el-input v-model="reviewForm.content" type="textarea" :rows="7" :disabled="busy" maxlength="20000"/></el-form-item><el-form-item label="教练复核状态"><el-select v-model="reviewForm.status" :disabled="busy"><el-option v-for="(label,value) in reviewStates" :key="value" :value="value" :label="label"/></el-select></el-form-item></el-form><template #footer><el-button :disabled="busy" @click="closeReview">取消</el-button><el-button :disabled="busy" @click="saveReview">保存教练复核</el-button></template></el-dialog>
</section>
</template>
<script setup lang="ts">
import type {CoachEvidence} from './types'
import {ref,computed,watch,onBeforeUnmount,reactive} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate} from 'vue-router'
import {ElCheckbox,ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
import ReviewEvidence from './ReviewEvidence.vue'
import type {Evidence,Reference} from './types'
const outcomeReasons:Record<string,string>={missing_quote:'缺少同币种报价。',quote_not_after_trade:'报价日期未晚于成交日期，无法确认成交后价格。',stale_quote:'报价已超过三天，需更新后重新预览。',future_quote:'报价日期在未来。',quote_identity_mismatch:'标的或币种不匹配。',invalid_trade_price:'成交价无效。',invalid_quote_price:'报价无效。'}
type Report={status:string;checks:{trade_id:string;process_score:number|null;outcome?:{status:string;reason:string|null;outcome_score:number|null;outcome_return_pct:string|null;price_evidence:unknown};patterns:{code:string;penalty:number}[]}[];evidence:{qualification?:unknown;constitution?:unknown;decision_evidence:CoachEvidence;history:unknown[]}}
type Annotation={revision:number;updated_at:string;title:string;content:string;status:string}
type Saved={annotation_versions:Annotation[];annotation:Annotation|null;id:string;title:string;updated_at:string;evidence_changed:boolean;outcome_evidence_changed?:boolean;report:Report}
const emit=defineEmits<{saved:[]}>()
const importantTrades=ref<{id:string;symbol:string;executed_at:string}[]>([]),constitutions=ref<{revision:number}[]>([]),constitutionRevision=ref<number|null>(null)
const candidates=ref<{ref:Reference;snapshot:Evidence}[]>([]),records=ref<Saved[]>([]),choice=ref(''),complete=ref(false),busy=ref(false),error=ref(''),preview=ref<{report:Report;token:string}|null>(null),selected=ref<Saved|null>(null),ops=operationCache();let input:unknown=null,id='',alive=true,baseline=''
const reviewTarget=ref<Saved|null>(null),reviewForm=reactive({title:'',content:'',status:'draft'}),reviewStates:Record<string,string>={draft:'草稿',reviewed:'已复核',journaled:'已存入日记',dismissed:'不采用'}
const key=(r:Reference)=>r.id+'@'+r.revision,state=()=>JSON.stringify([choice.value,complete.value,constitutionRevision.value]),report=computed(()=>preview.value?.report||selected.value?.report),states:Record<string,string>={complete:'依据已确认',partial:'依据不完整',unexecuted:'尚未执行'},labels:Record<string,string>={overtrading:'14日内同标的交易频繁',rapid_reversal:'7日内方向反转',chasing:'买价较前次高于8%',averaged_down_unreviewed:'降价加仓缺少更新理由',missing_reason:'缺少决策依据'}
const processCount=computed(()=>report.value?.checks.filter(c=>c.process_score!==null).length||0),outcomeCount=computed(()=>report.value?.checks.filter(c=>c.outcome?.status==='complete').length||0),reviewedCount=computed(()=>records.value.filter(r=>r.annotation?.status==='reviewed'||r.annotation?.status==='journaled').length)
let reviewBaseline=''
const reviewDirty=()=>!!reviewTarget.value&&JSON.stringify(reviewForm)!==reviewBaseline
watch([choice,complete,constitutionRevision],()=>{preview.value=null;input=null;ops.clear();id=''})
function editReview(r:Saved){reviewTarget.value=r;Object.assign(reviewForm,{title:r.annotation?.title||r.title,content:r.annotation?.content||'',status:r.annotation?.status||'draft'});reviewBaseline=JSON.stringify(reviewForm);ops.clear()}
async function closeReview(){if(busy.value)return;if(reviewDirty()){try{await ElMessageBox.confirm('放弃未保存的教练复核内容？','放弃编辑',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'})}catch{return}}reviewTarget.value=null}
async function saveReview(){if(busy.value||!reviewTarget.value)return;const reportId=reviewTarget.value.id;busy.value=true;error.value='';try{await request('/api/v1/owner/coach-review','POST',ops.body('review',{report_id:reviewTarget.value.id,revision:reviewTarget.value.annotation?.revision||0,...reviewForm}));reviewTarget.value=null;if(!await load(reportId))error.value='教练复核已保存，但固定历史读取失败。请刷新教练依据确认，避免重复保存。';emit('saved')}catch(e){error.value=e instanceof Error?e.message:'复核保存失败'}finally{busy.value=false}}
async function load(preferredId?:string){const activeId=preferredId??selected.value?.id;busy.value=true;error.value='';try{const [w,h]=await Promise.all([request<{candidates:typeof candidates.value}>('/api/v1/owner/evolve'),request<{reports:Saved[];important_trades:typeof importantTrades.value;constitutions:typeof constitutions.value}>('/api/v1/owner/coach')]);if(!alive)return false;candidates.value=w.candidates;records.value=h.reports;importantTrades.value=h.important_trades;constitutions.value=h.constitutions;constitutionRevision.value=null;preview.value=null;selected.value=h.reports.find(r=>r.id===activeId)||h.reports[0]||null;baseline=state();return true}catch(e){if(alive){candidates.value=[];records.value=[];importantTrades.value=[];constitutions.value=[];selected.value=null;preview.value=null;reviewTarget.value=null;choice.value='';complete.value=false;constitutionRevision.value=null;input=null;id='';ops.clear();baseline=state();error.value=e instanceof Error?e.message:'读取失败'}return false}finally{busy.value=false}}
async function leave(){if(busy.value)return false;if(!preview.value&&state()===baseline&&!reviewDirty())return true;try{await ElMessageBox.confirm('放弃未保存的教练选择、预览或复核内容？','离开决策教练',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'});return true}catch{return false}}
async function refresh(){if(await leave())await load()}
async function run(){if(busy.value)return;const c=candidates.value.find(c=>key(c.ref)===choice.value);const direct=choice.value.startsWith('trade:');if(!c&&!direct)return;if(direct&&!constitutionRevision.value){error.value='请选择已保存的纪律版本';return}busy.value=true;error.value='';preview.value=null;try{input=direct?{trade_id:choice.value.slice(6),constitution_revision:constitutionRevision.value,history_complete:complete.value}:{decision_ref:c!.ref,history_complete:complete.value};preview.value=await request('/api/v1/owner/coach-preview','POST',input);id=crypto.randomUUID();ops.clear()}catch(e){error.value=e instanceof Error?e.message:'预览失败'}finally{busy.value=false}}
async function save(){if(busy.value||!preview.value||!input)return;busy.value=true;error.value='';try{await request('/api/v1/owner/coach','POST',ops.body('save',{id,input,expected_token:preview.value.token}));preview.value=null;input=null;ops.clear();if(!await load(id))error.value='教练报告已保存，但固定历史读取失败。请刷新教练依据确认，避免重复保存。'}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{busy.value=false}}
onBeforeRouteLeave(leave);onBeforeRouteUpdate(leave);const unload=(e:BeforeUnloadEvent)=>{if(busy.value||preview.value||state()!==baseline||reviewDirty()){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',unload)});baseline=state();load()
defineExpose({getMaterial:()=>{if(busy.value||!report.value)throw Error('请先完成预览或选择历史报告');return {state:preview.value?'unsaved_preview':'fixed_report',record_id:preview.value?null:selected.value?.id,report:report.value}}})
</script>
<style scoped>

.decision-coach { margin: 18px 0; padding: 17px; border: 1px solid rgba(73,190,255,.22); border-radius: 16px; background: linear-gradient(145deg, rgba(8,28,52,.96), rgba(8,20,42,.94)); color:#dceaff; }
.coach-header,.coach-scoreboard,.pattern-strip,.review-row,.review-actions { display:flex;align-items:center; }.coach-header { justify-content:space-between;gap:14px; }.coach-kicker { color:#47d9ff;font:700 11px/1.2 ui-monospace,SFMono-Regular,monospace;letter-spacing:.18em; }.coach-header h3 { margin:4px 0;font-size:20px; }.coach-header p { margin:0;color:#7994b1;font-size:12px; }
.coach-scoreboard { display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:14px; }.is-compact .coach-scoreboard { grid-template-columns:repeat(3,1fr); }.coach-scoreboard article { padding:11px 13px;border:1px solid rgba(102,170,222,.15);border-radius:11px;background:rgba(255,255,255,.035); }.coach-scoreboard span,.coach-scoreboard small { display:block;color:#7791ad;font-size:10px; }.coach-scoreboard b { display:block;margin:3px 0;color:#edf6ff;font:700 22px/1.1 ui-monospace,SFMono-Regular,monospace; }.is-good { color:#36d7a1!important; }.is-watch { color:#ffba55!important; }.is-risk { color:#ff6572!important; }
.pattern-strip { gap:7px;margin-top:10px;padding:9px 11px;border-radius:10px;background:rgba(255,255,255,.025); }.pattern-strip > span { margin-right:5px;color:#7995b2;font-size:11px;font-weight:700; }.review-list { margin-top:10px;border:1px solid rgba(99,164,218,.14);border-radius:11px;overflow:hidden; }.review-row { display:grid;grid-template-columns:42px 1fr 60px auto;gap:11px;padding:10px 12px;border-top:1px solid rgba(111,165,208,.1);background:rgba(2,13,30,.28); }.review-row:first-child { border-top:0; }.review-score { display:grid;place-items:center;width:38px;height:38px;border-radius:10px;background:rgba(255,255,255,.05);font:700 15px ui-monospace,SFMono-Regular,monospace; }.review-main > span,.review-outcome small { color:#6785a2;font:600 9px ui-monospace,SFMono-Regular,monospace;text-transform:uppercase; }.review-main b { display:block;margin:2px 0;color:#dceaff;font-size:12px; }.review-main p { margin:0;color:#8099b3;font-size:10px; }.review-outcome { text-align:right; }.review-outcome b { display:block;margin-top:4px;font:700 15px ui-monospace,SFMono-Regular,monospace; }.review-actions { justify-content:flex-end; }.weekly-grid { display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:10px; }.weekly-grid article { padding:11px;border:1px solid rgba(100,167,220,.13);border-radius:10px;background:rgba(255,255,255,.025); }.weekly-grid span { color:#58cfff;font-size:11px;font-weight:700; }.weekly-grid p { margin:6px 0 0;color:#8ca5bf;font-size:10px;line-height:1.45; }
.coach-summary { margin:10px 0 0;padding:10px 12px;border-left:2px solid #4cd5ff;background:rgba(72,197,255,.05);color:#9bb3cb;font-size:11px;line-height:1.55; }
.episode-list { margin-top:10px;border-top:1px solid rgba(100,167,220,.14); }.episode-list header,.episode-list article { display:grid;align-items:center;gap:12px; }.episode-list header { grid-template-columns:1fr auto;padding:9px 2px 7px;color:#6f8ba7;font-size:10px; }.episode-list header > span { color:#58cfff;font-weight:700;letter-spacing:.08em; }.episode-list article { grid-template-columns:64px minmax(180px,1fr) 145px minmax(180px,.7fr);padding:8px 2px;border-top:1px solid rgba(100,167,220,.09); }.episode-list article > b { color:#dceaff;font:700 12px ui-monospace,SFMono-Regular,monospace; }.episode-list article div strong,.episode-list article div small { display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.episode-list article div strong { color:#cfe1f3;font-size:11px; }.episode-list article div small,.episode-list article > span,.episode-list article > em { margin-top:2px;color:#6f8ba7;font-size:9px;font-style:normal;overflow:hidden;text-overflow:ellipsis;white-space:nowrap; }.episode-list article > span { text-align:right; }.episode-list article > em { color:#86a2bc; }
.trend-panel { margin-top:10px;padding:11px;border:1px solid rgba(100,167,220,.13);border-radius:10px;background:rgba(255,255,255,.025); }.trend-head { display:flex;align-items:center;justify-content:space-between;gap:12px; }.trend-head span,.trend-head small { display:block; }.trend-head span { color:#58cfff;font-size:11px;font-weight:700; }.trend-head small { margin-top:2px;color:#708ca8;font-size:9px; }.trend-points { display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin-top:10px; }.trend-points article { min-width:0;padding:7px;border-radius:8px;background:rgba(2,13,30,.28); }.trend-points span,.trend-points small { display:block;color:#66829e;font:600 8px ui-monospace,SFMono-Regular,monospace; }.trend-points b { display:block;margin:5px 0 2px;color:#dceaff;font:700 14px ui-monospace,SFMono-Regular,monospace; }.trend-bar { height:3px;margin-top:6px;border-radius:3px;background:rgba(255,255,255,.06);overflow:hidden; }.trend-bar i { display:block;height:100%;background:linear-gradient(90deg,#4b75ff,#49d4ff); }
.is-compact { padding:14px; }.is-compact .coach-header h3 { font-size:17px; }.is-compact .review-row { grid-template-columns:38px 1fr 52px auto; }.is-compact .review-actions :deep(.el-button) { padding:4px; }
@media (max-width:900px) { .coach-scoreboard,.is-compact .coach-scoreboard { grid-template-columns:1fr 1fr; }.review-row,.is-compact .review-row { grid-template-columns:38px 1fr auto; }.review-outcome { display:none; }.episode-list article { grid-template-columns:54px 1fr auto; }.episode-list article > em { display:none; }.weekly-grid { grid-template-columns:1fr; }.trend-points { grid-template-columns:repeat(3,1fr); } }

.decision-coach{margin:20px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere}.coach-history .el-button{height:auto;white-space:normal;text-align:left}.coach-scoreboard{display:grid;grid-template-columns:repeat(4,minmax(0,1fr))}.coach-scoreboard b{font-size:18px}.coach-scoreboard article{min-width:0}.coach-report-state{margin:15px 0 0;color:#9bb3cb;font-size:12px}.review-row{grid-template-columns:42px minmax(0,1fr)}.coach-header{flex-wrap:wrap}
.decision-coach :deep(.el-checkbox){height:auto;align-items:flex-start;max-width:100%;margin:12px 0}.decision-coach :deep(.el-checkbox__label){white-space:normal;overflow-wrap:anywhere;line-height:1.6}.decision-coach :deep(.el-checkbox__input){margin-top:4px}
.coach-history-list{display:grid;gap:10px;margin-top:10px}.coach-history{min-width:0;padding:12px;border:1px solid rgba(100,167,220,.16);border-radius:11px;background:rgba(255,255,255,.025)}.coach-history.is-selected{border-color:rgba(73,190,255,.58);background:rgba(73,190,255,.065)}.coach-history-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.coach-history-head .el-button{min-width:0;max-width:100%;margin:0;color:#dceaff;white-space:normal;text-align:left;overflow-wrap:anywhere}.coach-history-head span{flex:none;color:#7db4d5;font-size:11px}.coach-history>p{margin:8px 0;color:#ffba55;font-size:11px}.coach-history-actions{margin-top:8px}.coach-history-actions .el-button{margin:0}.annotation-history{margin:12px 0}.annotation-history .annotation-version{padding:10px 0;border-top:1px solid rgba(100,167,220,.16)}.annotation-version summary{cursor:pointer;overflow-wrap:anywhere;color:#cfe1f3;font-size:11px;line-height:1.6}.annotation-text{max-height:280px;overflow:auto;padding:10px;border-radius:8px;background:rgba(2,13,30,.25);white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.65}
@media(max-width:480px){.coach-history-head{align-items:flex-start;flex-direction:column;gap:4px}}@media(max-width:900px){.coach-scoreboard{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:390px){.coach-scoreboard{grid-template-columns:1fr 1fr}.coach-scoreboard article{padding:9px}.coach-scoreboard b{font-size:16px}}
</style>
