<template><el-dialog append-to-body :model-value="true" title="洞察有用性反馈" width="min(640px,96vw)" :close-on-click-modal="false" :close-on-press-escape="false" :show-close="!busy" :before-close="close"><p>{{ label }}。评价只记录你的反馈，不改变原始报告或计算分数。</p><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="洞察评价"><el-select v-model="form.rating" :disabled="busy||savedReadPending"><el-option label="有用" value="useful"/><el-option label="无用" value="not_useful"/></el-select></el-form-item><el-form-item label="评价原因"><el-input v-model="form.reason" :disabled="busy||savedReadPending" maxlength="500"/></el-form-item><el-form-item label="反馈备注"><el-input v-model="form.note" type="textarea" :disabled="busy||savedReadPending" maxlength="4000"/></el-form-item><el-checkbox v-model="form.action_taken" :disabled="busy||savedReadPending">我已采取相关动作</el-checkbox><el-form-item v-if="form.action_taken" label="已采取的动作"><el-input v-model="form.action_type" :disabled="busy||savedReadPending" maxlength="120"/></el-form-item></el-form><p>这只是你的动作记录，不会提交交易或修改规则。</p><el-button :disabled="busy||savedReadPending||!loaded||!form.rating" @click="save">保存洞察反馈</el-button><el-button v-if="error" :loading="busy" @click="load">重新读取反馈</el-button><h3>此洞察的反馈历史</h3><p v-if="!versions.length&&!error">尚无反馈。</p><article v-for="v in versions" :key="v.revision" class="feedback-version"><strong>v{{ v.revision }} · {{ v.rating==='useful'?'有用':'无用' }}</strong><p>{{ new Date(v.updated_at).toLocaleString('zh-CN') }}</p><p>{{ v.reason }}</p><p>{{ v.note }}</p><p v-if="v.action_taken">已记录动作：{{ v.action_type }}</p></article><p v-if="summary">全部固定洞察最新反馈：{{ summary.total }} 条，有用 {{ summary.useful }}，无用 {{ summary.not_useful }}。不代表投资绩效。</p><template #footer><el-button :disabled="busy" @click="close">关闭反馈</el-button></template></el-dialog></template>
<script setup lang="ts">
import {ref,reactive,onBeforeUnmount,watch} from 'vue'
import {ElCheckbox,ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
const props=defineProps<{targetId:string;targetSymbol:string;label:string}>(),emit=defineEmits<{close:[]}>(),busy=ref(false),error=ref(''),savedReadPending=ref(false),loaded=ref(false),form=reactive({rating:'',reason:'',note:'',action_taken:false,action_type:''}),versions=ref<(typeof form&{revision:number;updated_at:string})[]>([]),summary=ref<{total:number;useful:number;not_useful:number}|null>(null),ops=operationCache();let revision=0,baseline=JSON.stringify(form),alive=true
watch(()=>form.action_taken,v=>{if(!v)form.action_type=''})
async function load(){busy.value=true;error.value='';try{const [h,s]=await Promise.all([request<{current:(typeof form&{revision:number})|null;versions:typeof versions.value}>('/api/v1/owner/insight-feedback-history','POST',{target_id:props.targetId,target_symbol:props.targetSymbol}),request<typeof summary.value>('/api/v1/owner/insight-feedback')]);if(!alive)return false;versions.value=h.versions;summary.value=s;revision=h.current?.revision||0;if(h.current)for(const key of Object.keys(form) as (keyof typeof form)[]){Object.assign(form,{[key]:h.current[key]})}baseline=JSON.stringify(form);savedReadPending.value=false;loaded.value=true;return true}catch(e){versions.value=[];summary.value=null;loaded.value=false;error.value=e instanceof Error?e.message:'读取反馈失败';return false}finally{busy.value=false}}
async function save(){if(busy.value||savedReadPending.value||!loaded.value)return;busy.value=true;error.value='';try{await request('/api/v1/owner/insight-feedback','POST',ops.body('feedback',{target_id:props.targetId,target_symbol:props.targetSymbol,revision,...form}));ops.clear();savedReadPending.value=true;baseline=JSON.stringify(form);if(!await load())error.value='反馈已保存，但重新读取失败。请重新读取确认，避免重复保存。'}catch(e){error.value=e instanceof Error?e.message:'保存失败，编辑已保留'}finally{busy.value=false}}
async function close(){if(busy.value)return false;if(JSON.stringify(form)!==baseline){try{await ElMessageBox.confirm('放弃未保存的洞察反馈？','关闭反馈',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'})}catch{return false}}emit('close');return true}
const unload=(e:BeforeUnloadEvent)=>{if(busy.value||JSON.stringify(form)!==baseline){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',unload);onBeforeUnmount(()=>{alive=false;window.removeEventListener('beforeunload',unload)});defineExpose({close});load()
</script>
<style scoped>.feedback-version{padding:12px 0;border-top:1px solid var(--el-border-color)}p{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}</style>
