<template>
 <section class="journal-entries" aria-label="投资日记">
  <header class="journal-header"><div><h2>投资日记</h2><p>把交易动作沉淀成复盘、观察清单和下一次决策的文字资产。</p></div><div class="journal-header-actions"><el-button @click="draft('trade')">从最近交易生成草稿</el-button><el-button type="primary" :icon="Plus" @click="open()">新写一篇</el-button></div></header>
  <el-alert v-if="error" :title="error" type="error" :closable="false"><el-button @click="load">重试</el-button></el-alert>
  <div v-if="!error" class="journal-summary"><article><span>日记数量</span><b>{{ entries.length }}</b><small>{{ entries[0] ? formatEntryDate(entries[0].entry_date) : '最近还没有写下任何一篇复盘' }}</small></article><article><span>近 7 天交易</span><b>{{ trades.length }}</b><small>围绕最近 7 天的动作生成复盘</small></article><article><span>活跃标的</span><b>{{ tickers.length }}</b><small>{{ tickers.slice(0,3).join('、')||'暂无' }}</small></article><article><span>当前复盘倾向</span><b>{{ trades.length?moodLabels[tradeMood]:'暂无' }}</b><small>仅按买卖笔数归类，不跨币种加总金额</small></article></div>
  <slot/>
  <div class="template-grid"><button v-for="item in templates" :key="item.kind" type="button" class="template-card" @click="draft(item.kind)"><span>{{ item.kicker }}</span><b>{{ item.title }}</b><p>{{ item.copy }}</p></button></div>
  <div class="journal-filter"><el-input v-model="search" placeholder="搜索标题 / 内容 / 股票" aria-label="搜索投资日记" clearable/><el-select v-model="moodFilter" placeholder="心态筛选" aria-label="心态筛选" clearable><el-option v-for="(label,key) in moodLabels" :key="key" :value="key" :label="label"/></el-select></div>
  <p v-if="!loading&&!error&&!filtered.length" class="journal-empty">{{ entries.length?'没有符合条件的日记。':'还没有日记，先写下你的第一篇复盘吧。' }}</p>
  <div v-loading="loading" class="journal-list"><article v-for="entry in filtered" :key="entry.id" class="journal-card"><div class="journal-card-top"><span>{{ entry.entry_date }} · <el-tag size="small" :type="moodTypes[entry.mood]">{{ moodLabels[entry.mood] }}</el-tag></span><span><el-button link @click="view=entry">阅读</el-button><el-button link @click="open(entry)">编辑</el-button><el-popconfirm title="归档这篇日记并保留历史版本？" confirm-button-text="归档" cancel-button-text="取消" @confirm="archive(entry)"><template #reference><el-button link>归档</el-button></template></el-popconfirm></span></div><h4>{{ entry.title }}</h4><p>{{ entry.content.slice(0,140) }}{{ entry.content.length>140?'…':'' }}</p><div class="journal-tags"><el-tag v-for="ticker in entry.tickers.slice(0,5)" :key="ticker" size="small" type="info" effect="plain">{{ ticker }}</el-tag><el-tag v-for="tag in entry.tags.slice(0,3)" :key="tag" size="small" effect="plain">{{ tag }}</el-tag></div></article></div>
  <el-dialog v-model="dialog" :title="editing?'编辑日记':'新写一篇'" width="min(700px,calc(100vw - 24px))" :close-on-click-modal="false" :before-close="close" :show-close="!saving" :close-on-press-escape="!saving"><el-alert v-if="saveError" :title="saveError" type="error" :closable="false"/><el-form label-position="top"><el-form-item label="标题"><el-input v-model="form.title" maxlength="120" :disabled="saving"/></el-form-item><div class="form-row"><el-form-item label="日期"><el-input v-model="form.entry_date" type="date" :disabled="saving"/></el-form-item><el-form-item label="心态"><el-select v-model="form.mood" :disabled="saving"><el-option v-for="(label,key) in moodLabels" :key="key" :value="key" :label="label"/></el-select></el-form-item></div><el-form-item label="相关股票"><el-select v-model="form.tickers" multiple filterable allow-create default-first-option :disabled="saving" placeholder="输入股票代码后回车" style="width:100%"><el-option v-for="ticker in allTickers" :key="ticker" :label="ticker" :value="ticker"/></el-select></el-form-item><el-form-item label="内容"><el-input v-model="form.content" type="textarea" :rows="12" maxlength="20000" :disabled="saving"/></el-form-item><el-form-item label="标签"><el-select v-model="form.tags" multiple filterable allow-create default-first-option :disabled="saving" style="width:100%"><el-option v-for="tag in commonTags" :key="tag" :label="tag" :value="tag"/></el-select></el-form-item></el-form><p>草稿只填入编辑框；点击保存后才写入本机账本。</p><template #footer><el-button :disabled="saving" @click="close">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存日记</el-button></template></el-dialog>
  <el-dialog v-model="viewOpen" :title="view?.title||'阅读日记'" width="min(680px,calc(100vw - 24px))"><template v-if="view"><p>{{ view.entry_date }} · {{ moodLabels[view.mood] }} · v{{ view.revision }}</p><p class="full-text">{{ view.content }}</p><div class="journal-tags"><el-tag v-for="ticker in view.tickers" :key="ticker" size="small" type="info" effect="plain">{{ ticker }}</el-tag><el-tag v-for="tag in view.tags" :key="tag" size="small" effect="plain">{{ tag }}</el-tag></div></template></el-dialog>
 </section>
</template>
<script setup lang="ts">
import {computed,onMounted,onBeforeUnmount,reactive,ref} from 'vue'
import {onBeforeRouteLeave,onBeforeRouteUpdate} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {Plus} from '@element-plus/icons-vue'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
type Mood='bullish'|'bearish'|'neutral'
type Entry={id:string;revision:number;title:string;content:string;entry_date:string;mood:Mood;tickers:string[];tags:string[]}
type Trade={id:string;symbol:string;side:'buy'|'sell';quantity:string;price:string;reason?:string;executed_at:string;account_name:string}
const moodLabels:Record<Mood,string>={bullish:'看多',bearish:'看空',neutral:'中性'},moodTypes:Record<Mood,'success'|'danger'|'info'>={bullish:'success',bearish:'danger',neutral:'info'}
const templates=[{kind:'trade',kicker:'TRADE REVIEW',title:'交易复盘草稿',copy:'用最近几笔买卖生成一篇可继续编辑的初稿。'},{kind:'position',kicker:'POSITION LOGIC',title:'仓位逻辑检查',copy:'检查最近活跃标的的持仓逻辑是否仍然成立。'},{kind:'checklist',kicker:'AFTER CLOSE',title:'盘后观察清单',copy:'整理明天开盘前需要回看的价格、消息和风险。'}] as const
const commonTags=['复盘','交易流水','仓位','风险','观察','盘后']
const entries=ref<Entry[]>([]),trades=ref<Trade[]>([]),loading=ref(false),saving=ref(false),error=ref(''),saveError=ref(''),search=ref(''),moodFilter=ref(''),dialog=ref(false),view=ref<Entry|null>(null),editing=ref<Entry|null>(null),ops=operationCache()
const formatEntryDate=(value:string)=>{const date=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return date?`${Number(date[1])}年${Number(date[2])}月${Number(date[3])}日`:value}
const blank=()=>({title:'',content:'',entry_date:new Date().toLocaleDateString('en-CA'),mood:'neutral' as Mood,tickers:[] as string[],tags:[] as string[]})
const form=reactive(blank());let baseline='',id=''
const tickers=computed(()=>[...new Set(trades.value.map(t=>t.symbol))]),allTickers=computed(()=>[...new Set([...tickers.value,...entries.value.flatMap(e=>e.tickers)])].sort())
const tradeMood=computed<Mood>(()=>{const buy=trades.value.filter(t=>t.side==='buy').length,sell=trades.value.filter(t=>t.side==='sell').length;return buy>sell*1.25?'bullish':sell>buy*1.25?'bearish':'neutral'})
const filtered=computed(()=>entries.value.filter(e=>(!moodFilter.value||e.mood===moodFilter.value)&&(!search.value||[e.title,e.content,...e.tickers].join(' ').toLowerCase().includes(search.value.toLowerCase()))))
defineExpose({getMaterial:()=>{if(loading.value||error.value)throw Error('投资日记材料尚未就绪');return {search:search.value,mood:moodFilter.value||null,records:filtered.value,source:'owner_written_investment_journal'}}})
const viewOpen=computed({get:()=>!!view.value,set:(value:boolean)=>{if(!value)view.value=null}})
const dirty=()=>dialog.value&&JSON.stringify(form)!==baseline
async function load(){if(loading.value)return false;loading.value=true;error.value='';try{const data=await request<{entries:Entry[];recent_trades:Trade[]}>('/api/v1/owner/journal');entries.value=data.entries;trades.value=data.recent_trades;return true}catch(e){entries.value=[];trades.value=[];view.value=null;error.value=e instanceof Error?e.message:'日记读取失败';return false}finally{loading.value=false}}
function open(entry?:Entry){editing.value=entry||null;id=entry?.id||crypto.randomUUID();Object.assign(form,entry?{title:entry.title,content:entry.content,entry_date:entry.entry_date,mood:entry.mood,tickers:[...entry.tickers],tags:[...entry.tags]}:blank());baseline=JSON.stringify(form);ops.clear();saveError.value='';dialog.value=true}
function draft(kind:'trade'|'position'|'checklist'){open();const today=form.entry_date,focus=tickers.value.slice(0,kind==='checklist'?6:4),reasons=trades.value.filter(t=>t.reason?.trim()).slice(0,4).map(t=>`- ${t.symbol}：${t.reason}`);if(kind==='trade')Object.assign(form,{title:`${today} 交易复盘`,mood:tradeMood.value,tickers:[...tickers.value],tags:['复盘','交易流水'],content:[`本次复盘覆盖 ${trades.value.length} 笔交易，涉及 ${tickers.value.length} 个标的。`,`买入 ${trades.value.filter(t=>t.side==='buy').length} 笔，卖出 ${trades.value.filter(t=>t.side==='sell').length} 笔。`,'','建议重点回答：','- 哪一笔最能代表这周真正的主判断？','- 有没有哪笔加减仓更像价格情绪而不是逻辑兑现？','- 明天开盘前最应该再确认什么？','','最近动作理由摘录：',...reasons].join('\n')});else if(kind==='position')Object.assign(form,{title:`${today} 仓位逻辑检查`,tickers:focus,tags:['仓位','逻辑复核'],content:[`用这篇日记检查 ${focus.join('、')||'最近核心标的'} 的仓位逻辑是否还成立。`,'','检查清单：','- 从第一次买入到现在，核心逻辑变了什么？','- 当前仓位大小，还配得上现在的确定性和风险吗？','- 如果明天价格剧烈波动，预先承诺的动作是什么？'].join('\n')});else Object.assign(form,{title:`${today} 盘后观察清单`,tickers:focus,tags:['观察','盘后'],content:['明日开盘前观察清单：',...focus.map(t=>`- ${t}：回看价格位置、消息变化，以及下一步动作是否已经提前定义。`)].join('\n')});ElMessage.success('草稿已填入编辑框，保存前可继续修改')}
async function close(){if(saving.value)return;if(dirty()){try{await ElMessageBox.confirm('放弃未保存的日记内容？','放弃编辑',{confirmButtonText:'放弃',cancelButtonText:'继续编辑'})}catch{return}}dialog.value=false}
async function save(){if(saving.value||loading.value)return;saveError.value='';if(!form.title.trim()||!form.content.trim()||!form.entry_date){saveError.value='请填写标题、日期和内容。';return}saving.value=true;try{await request('/api/v1/owner/journal','POST',ops.body('save',{id,revision:editing.value?.revision||0,...form,tickers:form.tickers.map(v=>v.toUpperCase())}));dialog.value=false;ops.clear();if(await load())ElMessage.success('日记已保存');else ElMessage.warning('日记已保存，但重新读取失败。请刷新确认，避免重复保存。')}catch(e){saveError.value=e instanceof Error?e.message:'保存失败，输入已保留'}finally{saving.value=false}}
async function archive(entry:Entry){if(saving.value||loading.value)return;saving.value=true;try{await request('/api/v1/owner/journal','DELETE',ops.body('archive:'+entry.id,{id:entry.id,revision:entry.revision}));ops.clear();if(!await load())ElMessage.warning('日记已归档，但重新读取失败。请刷新确认。')}catch(e){error.value=e instanceof Error?e.message:'归档失败'}finally{saving.value=false}}
const beforeUnload=(e:BeforeUnloadEvent)=>{if(dirty()||saving.value){e.preventDefault();e.returnValue=''}}
onBeforeRouteLeave(async()=>{if(!dialog.value)return true;await close();return !dialog.value});onBeforeRouteUpdate(async()=>{if(!dialog.value)return true;await close();return !dialog.value});onMounted(()=>{load();window.addEventListener('beforeunload',beforeUnload)});onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
</script>
<style scoped>
.journal-entries{display:flex;flex-direction:column;gap:18px}.journal-header,.journal-header-actions,.journal-filter,.journal-card-top{display:flex;align-items:center;justify-content:space-between;gap:14px}.journal-header{align-items:flex-end}.journal-header h2{font-size:30px;font-weight:800;margin:0}.journal-header p,.journal-card p{color:var(--el-text-color-secondary);line-height:1.7;margin:8px 0 0}.journal-header-actions{justify-content:flex-end;flex-wrap:wrap}.template-card span{font-size:12px;letter-spacing:.08em;color:var(--el-text-color-secondary)}.journal-summary,.template-grid,.journal-list{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.journal-summary article,.template-card,.journal-card{min-width:0;background:var(--el-bg-color-overlay);border:1px solid var(--el-border-color-lighter);border-radius:20px;padding:18px 20px;box-shadow:0 16px 44px rgba(17,32,62,.08)}.journal-summary article{display:flex;flex-direction:column;gap:8px}.journal-summary article span,.journal-summary article small{color:var(--el-text-color-secondary)}.journal-summary article span{font-size:12px;letter-spacing:.08em}.journal-summary b{font-size:28px}.template-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.template-card{text-align:left;cursor:pointer;transition:transform .2s,border-color .2s}.template-card:hover{transform:translateY(-2px);border-color:var(--el-color-primary)}.template-card b{display:block;font-size:18px;margin-top:8px}.template-card p{font-size:13px;line-height:1.7;color:var(--el-text-color-secondary)}.journal-filter .el-input{max-width:320px}.journal-filter .el-select{width:160px}.journal-list{grid-template-columns:repeat(2,minmax(0,1fr))}.journal-card h4{font-size:19px;margin:12px 0}.journal-card-top{flex-wrap:wrap}.journal-card-top span:last-child{white-space:nowrap}.journal-tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.journal-empty{padding:25px;text-align:center;color:var(--el-text-color-secondary)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.form-row .el-form-item{min-width:0}.full-text{white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.8}@media(max-width:800px){.journal-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.journal-header{align-items:flex-start;flex-direction:column}.journal-list{grid-template-columns:1fr}}@media(max-width:768px){.journal-summary{grid-template-columns:1fr}.journal-header-actions{align-items:flex-start;flex-direction:column}}@media(max-width:390px){.template-grid{grid-template-columns:1fr}.journal-filter{align-items:stretch;flex-direction:column}.journal-filter .el-input,.journal-filter .el-select{width:100%;max-width:none}.form-row{grid-template-columns:1fr}}
</style>
