<template>
 <section class="assistant-workbench">
  <div class="assistant-heading"><h2>研究助手</h2><el-button v-if="route.path!=='/settings/connections'" :disabled="externalBusy||busy||saving" @click="openConnectionSettings">模型连接设置</el-button></div><p>使用你自行配置的云端服务或本地模型。预览后才发送；生成结果是未核验草稿。</p>
  <el-alert v-if="error" :title="error" type="error" :closable="false" />
  <p class="question-help">可直接在「研究问题」中自由输入或修改；快捷问题只是示例，材料可以留空。模型请求期间暂时不能编辑。</p>
  <el-form label-position="top"><el-form-item label="研究任务"><el-select v-model="task" :disabled="externalBusy||busy" style="width:100%"><el-option label="结构化研究综合" value="research_synthesis"/><el-option label="解释材料与证据缺口" value="explain"/><el-option label="寻找反方证据" value="counter_case"/><el-option label="梳理投资判断" value="decision"/><el-option label="检查计划" value="plan"/><el-option label="复盘检查" value="review"/></el-select></el-form-item><el-form-item label="研究问题"><el-input v-model="question" placeholder="直接输入你的问题，例如：用三个要点解释市盈率的局限。" type="textarea" :rows="3" maxlength="4000" :disabled="externalBusy||busy" /></el-form-item><el-form-item label="待发送上下文"><el-input v-model="context" placeholder="可选：粘贴需要核对的材料；不填也能询问通用概念。" type="textarea" :rows="8" maxlength="20000" :disabled="externalBusy||busy" /></el-form-item></el-form>
  <ContextExcerpt :source="sourceContext" :label="symbol?symbol+' 研究材料':'研究材料'" :disabled="!!externalBusy||busy||saving" :accept="acceptExcerpt" @dirty="excerptDirty=$event"/>
  <div class="assistant-actions"><el-button :disabled="externalBusy||busy||!sourceContext" @click="fill">填入当前研究材料</el-button><el-button :disabled="externalBusy||busy||!question.trim()" type="primary" @click="prepare">预览发送内容</el-button></div>
  <section v-if="preview" class="preview-panel"><h3>确认本次发送</h3><p>{{ preview.provider }} / {{ preview.model }} · {{ preview.sends_to_cloud?'将发送到你配置的云端服务':'请求你配置的本地 Ollama' }}</p><p>预览有效期 {{ preview.expires_seconds }} 秒。修改问题或上下文会使当前预览失效。</p><pre>{{ JSON.stringify(preview.payload,null,2) }}</pre><el-button type="primary" :loading="busy" :disabled="externalBusy" @click="generate">确认发送并生成草稿</el-button></section>
  <section v-if="result" class="draft-panel"><h3>AI 草稿 · 未经人工核验</h3><p>{{ result.provider }} / {{ result.model }} · {{ result.generated_at }}</p><p v-if="resultSymbol">本次研究标的：{{ resultSymbol }}</p><details><summary>本次生成依据</summary><pre>{{ JSON.stringify(result.context,null,2) }}</pre></details><section v-if="result.synthesis?.status==='structured'" class="structured-synthesis"><h4>研究综合 · 未核验</h4><el-button v-if="allowReportSynthesis" :disabled="!canApplySynthesis" @click="applySynthesis">采用到当前报告摘要</el-button><p v-if="allowReportSynthesis&&!canApplySynthesis">当前材料与生成依据不一致；请基于当前完整材料重新预览并生成。</p><p>{{ result.synthesis.decision_brief }}</p><h4>为何现在复核</h4><p>{{ result.synthesis.why_now||'未提供' }}</p><h4>不确定性</h4><p>{{ result.synthesis.uncertainty }}</p><h4>待验证条件</h4><ul><li v-for="(condition,index) in result.synthesis.decision_conditions" :key="index">{{ condition }}</li></ul><p v-if="!result.synthesis.decision_conditions?.length">未提供验证条件。</p></section><el-alert v-else-if="result.synthesis" :title="result.synthesis.reason||'保留原始草稿'" type="warning" :closable="false"/><details v-if="result.synthesis"><summary>模型原始草稿</summary><pre>{{ result.draft }}</pre></details><pre v-else>{{ result.draft }}</pre><el-button @click="copy">复制草稿</el-button><el-button :disabled="!resultSymbol||saving" :loading="saving" @click="saveDraft">保存为未核验研究笔记</el-button><p v-if="!resultSymbol">批量结果可复制后分别整理为研究笔记。</p></section>
 </section>
</template>
<script setup lang="ts">
import ContextExcerpt from './ContextExcerpt.vue'
import {ref,watch,onBeforeUnmount,nextTick,computed} from 'vue'
import {useRoute,useRouter,onBeforeRouteLeave,onBeforeRouteUpdate} from 'vue-router'
import {ElMessage,ElMessageBox} from 'element-plus'
import {request} from '@/api/owner'
import {operationCache} from '@/api/business'
const props=defineProps<{sourceContext:string;symbol?:string;managedNavigation?:boolean;initialQuestion?:string;externalBusy?:boolean;allowReportSynthesis?:boolean}>(),router=useRouter(),route=useRoute(),question=ref(props.initialQuestion||''),context=ref(''),task=ref('explain'),busy=ref(false),saving=ref(false),error=ref(''),operations=operationCache();let savedText='',noteId=''
async function openConnectionSettings(){if(props.externalBusy||busy.value||saving.value)return;try{const failure=await router.push('/settings/connections');if(!failure)emit('connectionSettings')}catch{error.value='无法打开模型连接设置，请刷新页面后重试。'}}
const excerptDirty=ref(false)
async function acceptExcerpt(value:string){if(context.value&&context.value!==props.sourceContext){try{await ElMessageBox.confirm('用选取片段替换当前编辑的上下文？','替换材料',{confirmButtonText:'替换',cancelButtonText:'保留'})}catch{return false}}context.value=value;return true}
type Preview={token:string;payload:{question:string;context:string;task:string};provider:string;model:string;sends_to_cloud:boolean;expires_seconds:number}
type Draft={receipt_id?:string;draft:string;provider:string;model:string;generated_at:string;context:Preview['payload'];synthesis?:{status:'structured'|'unstructured';decision_brief?:string;why_now?:string;uncertainty?:string;decision_conditions?:string[];reason?:string}}
const preview=ref<Preview|null>(null),result=ref<Draft|null>(null),resultSymbol=ref('')
watch([question,context,task],()=>{preview.value=null})
async function fill(){if(busy.value)return;if(context.value&&context.value!==props.sourceContext){try{await ElMessageBox.confirm('替换当前编辑的上下文？','替换材料',{confirmButtonText:'替换',cancelButtonText:'保留'});}catch{return}}if(props.sourceContext.length>20000){error.value='材料超过 20000 字，请缩小研究范围后再填入。';return}context.value=props.sourceContext}
async function prepare(){if(busy.value)return;busy.value=true;error.value='';preview.value=null;try{const body={question:question.value,context:context.value,task:task.value};if(new TextEncoder().encode(JSON.stringify(body)).length>60000)throw Error('待发送文字过多，请减少上下文。');preview.value=await request('/api/v1/owner/ai-preview','POST',body)}catch(e){error.value=e instanceof Error?e.message:'预览失败'}finally{busy.value=false}}
async function generate(){if(busy.value||!preview.value)return;const token=preview.value.token,symbol=props.symbol||'';busy.value=true;error.value='';try{result.value=await request('/api/v1/owner/ai-generate','POST',{token,confirm:true},false);preview.value=null;resultSymbol.value=symbol;noteId='';savedText='';operations.clear()}catch(e){preview.value=null;error.value=(e instanceof Error?e.message:'请求失败')+'。没有自动重试；重新预览并确认可能产生新的服务费用。'}finally{busy.value=false}}
async function copy(){if(!result.value)return;try{await navigator.clipboard.writeText(result.value.draft);ElMessage.success('草稿已复制，请核对来源')}catch{ElMessage.error('无法复制，可直接选择草稿文字')}}
async function saveDraft(){if(!result.value||!resultSymbol.value||saving.value)return;if(savedText===result.value.draft){ElMessage.info('这份草稿已保存');return}saving.value=true;noteId ||= crypto.randomUUID();try{const content=`AI草稿，未经人工核验\n服务：${result.value.provider} / ${result.value.model}\n生成时间：${result.value.generated_at}\n\n生成依据：\n${JSON.stringify(result.value.context,null,2)}\n\n${result.value.draft}`;if(content.length>20000)throw Error('草稿过长，请复制并整理后保存');await request('/api/v1/owner/documents','POST',operations.body('draft',{id:noteId,revision:0,kind:'note',title:resultSymbol.value+' · AI研究草稿',symbol:resultSymbol.value,content,support:'',counter_case:'',invalidation:'',risk_limit:'',review_on:'',research_ref:null}));savedText=result.value.draft;ElMessage.success('已保存为未核验笔记')}catch(e){error.value=e instanceof Error?e.message:'保存失败'}finally{saving.value=false}}
async function leave(){if(busy.value||saving.value)return false;if(!question.value&&!context.value&&!result.value&&!excerptDirty.value)return true;try{await ElMessageBox.confirm('离开会清除当前问题、上下文和未保存的生成内容。','离开研究助手',{confirmButtonText:'离开',cancelButtonText:'继续研究'});return true}catch{return false}}
onBeforeRouteLeave(()=>props.managedNavigation?true:leave());onBeforeRouteUpdate(()=>props.managedNavigation?true:leave())
const beforeUnload=(e:BeforeUnloadEvent)=>{if(!props.managedNavigation&&(busy.value||saving.value||question.value||context.value||result.value||excerptDirty.value)){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',beforeUnload);onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
const state=computed(()=>({busy:busy.value||saving.value,preview:!!preview.value,result:!!result.value,failed:!!error.value,dirty:!!question.value||!!context.value||!!result.value||excerptDirty.value}))
const emit=defineEmits<{connectionSettings:[];synthesis:[value:{receipt_id?:string;provider:string;model:string;generated_at:string;context:string;symbol:string;synthesis:NonNullable<Draft['synthesis']>}];state:[value:{busy:boolean;preview:boolean;result:boolean;failed:boolean;dirty:boolean}]}>()
const canApplySynthesis=computed(()=>!busy.value&&!saving.value&&!props.externalBusy&&result.value?.synthesis?.status==='structured'&&result.value.context.task==='research_synthesis'&&!!resultSymbol.value&&resultSymbol.value===props.symbol&&result.value.context.context===props.sourceContext)
function applySynthesis(){if(!canApplySynthesis.value||!result.value?.synthesis)return;emit('synthesis',{receipt_id:result.value.receipt_id,provider:result.value.provider,model:result.value.model,generated_at:result.value.generated_at,context:result.value.context.context,symbol:resultSymbol.value,synthesis:result.value.synthesis})}
watch(state,value=>emit('state',value),{immediate:true})
async function confirmMaterialChange(){if(busy.value||saving.value)return false;if(!state.value.dirty)return true;try{await ElMessageBox.confirm('切换或重新载入材料后，当前问题、编辑的上下文和助手草稿将被清除。已保存的笔记会保留。','重新载入研究材料',{confirmButtonText:'载入并清除',cancelButtonText:'保留当前研究'});return true}catch{return false}}
async function prepareBatch(){if(!context.value){if(props.sourceContext.length>20000){error.value='材料超过 20000 字，请手动缩小此标的上下文。';return}context.value=props.sourceContext;await nextTick()}await prepare()}
defineExpose({confirmMaterialChange,prepare:prepareBatch,generate,invalidatePreview:()=>{preview.value=null},setQuestion:(value:string)=>{if(!busy.value&&!saving.value){question.value=value;preview.value=null}}})
</script>
<style scoped>.structured-synthesis{overflow-wrap:anywhere;min-width:0}.assistant-workbench{padding:22px;border:1px solid rgba(112,202,255,.18);border-radius:18px;background:rgba(9,20,39,.8);min-width:0}.assistant-heading,.assistant-actions{display:flex;gap:12px;flex-wrap:wrap;align-items:center;justify-content:space-between}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit;line-height:1.7;background:rgba(0,0,0,.15);padding:16px;border-radius:12px}.preview-panel,.draft-panel{margin-top:24px;border-top:1px solid rgba(112,202,255,.18);padding-top:16px}h2{margin:0}p{line-height:1.7;color:#a5bad3}</style>
<style scoped>.assistant-workbench :deep(.el-alert--error){background:#321d2b;color:#ffb9c3;border:1px solid #70394d}</style>
