<template><section v-if="source.length>20000||opened" class="context-excerpt"><el-button v-if="!opened" :disabled="disabled" @click="open">整理超长材料片段</el-button><template v-else><h3>本地选取材料</h3><p>已固定打开时的 {{ labelSnapshot }}，共 {{ snapshot.length }} 字符。页面后续变化不会改写这份原文。选取片段不是完整来源。</p><el-alert v-if="error" type="error" :title="error" :closable="false"/><el-form label-position="top"><el-form-item label="完整来源材料"><el-input :model-value="snapshot" type="textarea" :rows="6" readonly/></el-form-item><el-form-item label="整理后的片段"><el-input v-model="excerpt" type="textarea" :rows="6" maxlength="18000" show-word-limit :disabled="disabled||working"/></el-form-item></el-form><el-button :disabled="disabled||working||!excerpt.trim()" @click="apply">采用此材料片段</el-button><el-button :disabled="disabled||working" @click="cancel">取消片段整理</el-button></template></section></template>
<script setup lang="ts">
import {ref,watch,onBeforeUnmount} from 'vue'
import {ElMessageBox} from 'element-plus'
const props=defineProps<{source:string;label:string;disabled:boolean;accept:(value:string)=>Promise<boolean>}>(),emit=defineEmits<{dirty:[boolean]}>(),opened=ref(false),snapshot=ref(''),labelSnapshot=ref(''),excerpt=ref(''),error=ref(''),working=ref(false);let capturedAt=''
function open(){snapshot.value=props.source;labelSnapshot.value=props.label;capturedAt=new Date().toISOString();excerpt.value='';error.value='';opened.value=true}
async function apply(){if(props.disabled||working.value||!excerpt.value.trim())return;const text=JSON.stringify({source_label:labelSnapshot.value,captured_at:capturedAt,original_characters:snapshot.value.length,selection:'user_selected_excerpt_not_complete_source',material_excerpt:excerpt.value},null,2);if(text.length>20000){error.value='来源说明和片段超过20000字符，请继续缩短。';return}working.value=true;try{if(await props.accept(text)){opened.value=false;excerpt.value=''}}finally{working.value=false}}
async function cancel(){if(excerpt.value){try{await ElMessageBox.confirm('放弃正在整理的片段？','取消片段整理',{confirmButtonText:'放弃片段',cancelButtonText:'继续整理'})}catch{return}}opened.value=false;excerpt.value=''}
watch([opened,excerpt,working],()=>emit('dirty',working.value||opened.value&&!!excerpt.value));onBeforeUnmount(()=>emit('dirty',false))
</script>
<style scoped>.context-excerpt{margin:16px 0;min-width:0}.context-excerpt p{line-height:1.7;overflow-wrap:anywhere}.el-button{margin:4px;white-space:normal;height:auto;min-height:32px}</style>
